### ISSUE TITLE
`imports => import` and white spaces

### ISSUE THREAD

**Issue by grosu** [kframework/kore#1]
I am playing with the KORE parser.  Specifically, trying to parse the imp.kore at https://github.com/grosu/kore-in-maude/blob/master/imp.kore.

First issue.  I get a parsing error for "import":
```
ERROR: Line 17: Column 10: Expected s, but B
  import BOOL []
         ^
```
Your syntax seems to be `imports`.  To me, `import` sounds more like a command than `imports`, so I would go with `import`.  If you have reasons for `imports`, please let me know and I will change the mode syntax accordingly.

Also, note that the carrot in under B and not under space.  It should be under the space, because it is there where the syntax is violated.  In fact, it looks like you ignore the white spaces, which explains it but is not right; the following parses:
```
  import s BOOL []
```

**Comment by daejunpark** [comment]
The current (full) K syntax has `imports`, which is only reason why I'm using it. I completely agree that `import` is much better. I can change if you have no concern about the incompatibility with full K.

**Comment by daejunpark** [comment]
Regarding the parsing white spaces, yes you're right. I'm just ignoring any white spaces. But I guess I need to be more careful when reading keywords or names. I'll fix it.

**Comment by daejunpark** [comment]
I close this since the bug was fixed. You can re-open it if you want.
