### ISSUE TITLE
Integration testing with KEVM semantics and K frontend

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1014]

**Comment by yzhang90** [comment]
please use https://github.com/kframework/k/tree/priority-group  this branch

**Comment by ttuegel** [comment]
This is actually related to the build failures on `evm-semantics` with the frontend and backend `master`s; that's for #988.

**Comment by yzhang90** [comment]
i see. I'll leave the comment there.

**Comment by ttuegel** [comment]
This was related to some build failures on `evm-semantics`, but I haven't heard any complaints about that.
