### ISSUE TITLE
Simplification step doesn't keep applying function/simplification rules until the term stabilizes

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1015]
When proving the following spec on KWASM semantics:
```
requires "kwasm-lemmas.k"

module SIMPLE-ARITHMETIC-SPEC
    imports WASM-TEXT
    imports KWASM-LEMMAS

    rule <k> (ITYPE:IValType . const X:Int) => . ... </k>
         <valstack> S:ValStack => < ITYPE > X : S </valstack>
      requires #inUnsignedRange(ITYPE, X)

endmodule
```
I found that in depth 2, after `deriveSeq` step, the top of k cell is `chop(...)`. In the following `simplify` step, the `chop` function gets evaluated to `modInt` and simplification step terminates. However, there is still a simplification rule about `modInt` can be applied. The simplification rule is applied in the next `simplification` step. The steps between two simplifications are `TrivivallyValid`, `CheckProven`, and `CheckRemainder`, which doesn't modify the term at all.

**Comment by ana-pantilie** [comment]
This issue should be fixed by https://github.com/kframework/kore/pull/1086
