### ISSUE TITLE
KEVM sum-to-n proof takes long time to finish

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1021]
https://github.com/kframework/evm-semantics/blob/master/tests/specs/examples/sum-to-n-spec.k takes around 20 mins to finish

**Comment by yzhang90** [comment]
I tried to modify the semantics and removed stackoverflow/underflow check.
```diff --git a/evm.md b/evm.md
index 9bd20a5..94ac014 100644
--- a/evm.md
+++ b/evm.md
@@ -308,22 +308,13 @@ The `#next [_]` operator initiates execution by:
          </k>
          <wordStack> WS </wordStack>
          <static> STATIC:Bool </static>
-      requires notBool ( #stackUnderflow(WS, OP) orBool #stackOverflow(WS, OP) )
-       andBool notBool ( STATIC andBool #changesState(OP, WS) )
+      requires notBool ( STATIC andBool #changesState(OP, WS) )
 
-    rule <k> #next [ OP ] => #end EVMC_STACK_UNDERFLOW ... </k>
-         <wordStack> WS </wordStack>
-      requires #stackUnderflow(WS, OP)
-
-    rule <k> #next [ OP ] => #end EVMC_STACK_OVERFLOW ... </k>
-         <wordStack> WS </wordStack>
-      requires #stackOverflow(WS, OP)
 
     rule <k> #next [ OP ] => #end EVMC_STATIC_MODE_VIOLATION ... </k>
          <wordStack> WS </wordStack>
          <static> STATIC:Bool </static>
-      requires notBool ( #stackUnderflow(WS, OP) orBool #stackOverflow(WS, OP) )
-       andBool STATIC andBool #changesState(OP, WS)
+      requires STATIC andBool #changesState(OP, WS)
```
By doing this the total run time reduces to ~5 mins. I think this is the best result we can get.
I'm still get confused why overflow/underflow check made such huge difference.
For the `sum-to-n` proof, there at most 10 elements on the stack and there are 17 opcodes in total.

**Comment by yzhang90** [comment]
Answer by @ttuegel :
You hit #sizeWordStack(_) four times (at least) per op code, times the number of branches. Then you hit #sizeWordStack(_, _) up to the depth of the stack, so that's at least 10 * 4 * number of branches.

**Comment by yzhang90** [comment]
I made some simple modification to EVM-semantics to store the result of #sizeWordStack... see https://github.com/kframework/evm-semantics/commit/71de70f5a5dcac99d9a653fbec0f6205e4964cc5.
however, this doesn't improve the performance at all...(even takes longer time)

**Comment by ttuegel** [comment]
>  however, this doesn't improve the performance at all...(even takes longer time)

Are you comparing to kframework/evm-semantics#508? I would expect that you can only beat performance there if the semantics is changed to _never_ calculate the length of a `WordStack`. Recall also that function evaluation has no operational semantics; there is absolutely no guarantee that `#sizeWordStack` will be evaluated before entering `#checkStack`, in which case it may be evaluated multiple times.
