### ISSUE TITLE
Expansion of non-function symbols

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1033]
The axiom registry happily registers axioms for non-function symbols (without the `function` attribute) as function evaluators.

**Comment by virgil-serbanuta** [comment]
Why is this a bug?

**Comment by ttuegel** [comment]
If the symbol is not a `function` symbol, then the pattern isn't a function pattern, so we cannot apply the simplified remainder logic.

**Comment by virgil-serbanuta** [comment]
Ah, ok. But what should be done about them? Reject them, or use the new stuff from @andreiburdusa and @traiansf for remainders?

**Comment by ttuegel** [comment]
I think we can safely ignore axioms that do not have an attribute tying them to a particular kind of evaluation. For example, select only `function` axioms for function evaluation, only `simplification` axioms for simplification evaluation (we already do that), only `overload` axioms for overloading. Function evaluation can use the checks from @andreiburdusa and @traiansf. I think it is OK to throw an error if the configuration or rules aren't function-like: the left- and right-hand sides of all such rules _must_ be function-like, or the definition has an error.
