### ISSUE TITLE
Synchronize with upstream KEVM tests

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1043]
Since #1001, we should be able to run the KEVM integration test proofs without manually completing the cells in the configuration.

**Comment by yzhang90** [comment]
I've tested the #1001 on the sum-to-n spec that removes the unnecessary `<static>` cell in the spec.
The spec finished in 12 mins

Here are some findings (I copied an intermediate config in the Appendix):
1. The fix doesn't work with kore-repl. It works on kore-exec ( we need to think about a way to call repl so that changes to kore-exec will automatically work on kore-repl?)
2. There are some useless substitution in the constraint like 
```    DotVar1
  #Equals
    <exit-code>
      DotVar10
    </exit-code>
```. since DotVar1 is alreadly been substituted, we can get rid of it.

Appendix
```
  <kevm>
    <k>
      #exec [ JUMPDEST ] ~> #pc [ JUMPDEST ] ~> #execute ~> DotVar2
    </k>
    <exit-code>
      DotVar10
    </exit-code>
    <mode>
      NORMAL
    </mode>
    <schedule>
      DEFAULT
    </schedule>
    <ethereum>
      <evm>
        <output>
          _70
        </output>
        <statusCode>
          _80
        </statusCode>
        <callStack>
          .List
        </callStack>
        <interimStates>
          _90
        </interimStates>
        <touchedAccounts>
          _100
        </touchedAccounts>
        <callState>
          <program>
            96 : 0 : 144 : 91 : 128 : 21 : 96 : 20 : 87 : 128 : 145 : 1 : 144 : 96 : 1 : 144 : 3 : 96 : 3 : 86 : 91 : .WordStack
          </program>
          <jumpDests>
            SetItem ( 3 )
            SetItem ( 20 )
          </jumpDests>
          <id>
            _10
          </id>
          <caller>
            _20
          </caller>
          <callData>
            _30
          </callData>
          <callValue>
            _40
          </callValue>
          <wordStack>
            I : S : WS
          </wordStack>
          <localMem>
            .Map
          </localMem>
          <pc>
            3
          </pc>
          <gas>
            G
          </gas>
          <memoryUsed>
            0
          </memoryUsed>
          <callGas>
            _0
          </callGas>
          <static>
            _50
          </static>
          <callDepth>
            _60
          </callDepth>
        </callState>
        <substate>
          <selfDestruct>
            _112
          </selfDestruct>
          <log>
            _111
          </log>
          <refund>
            _110
          </refund>
        </substate>
        <gasPrice>
          _120
        </gasPrice>
        <origin>
          _130
        </origin>
        <blockhashes>
          _140
        </blockhashes>
        <block>
          <previousHash>
            _1515
          </previousHash>
          <ommersHash>
            _1514
          </ommersHash>
          <coinbase>
            _1513
          </coinbase>
          <stateRoot>
            _1512
          </stateRoot>
          <transactionsRoot>
            _1511
          </transactionsRoot>
          <receiptsRoot>
            _1510
          </receiptsRoot>
          <logsBloom>
            _159
          </logsBloom>
          <difficulty>
            _158
          </difficulty>
          <number>
            _157
          </number>
          <gasLimit>
            _156
          </gasLimit>
          <gasUsed>
            _155
          </gasUsed>
          <timestamp>
            _154
          </timestamp>
          <extraData>
            _153
          </extraData>
          <mixHash>
            _152
          </mixHash>
          <blockNonce>
            _151
          </blockNonce>
          <ommerBlockHeaders>
            _150
          </ommerBlockHeaders>
        </block>
      </evm>
      <network>
        <activeAccounts>
          DotVar34
        </activeAccounts>
        <accounts>
          DotVar33
        </accounts>
        <txOrder>
          DotVar32
        </txOrder>
        <txPending>
          DotVar31
        </txPending>
        <messages>
          DotVar30
        </messages>
      </network>
    </ethereum>
  </kevm>
#And
  {
    DotVar0
  #Equals
    <generatedCounter>
      DotVar00
    </generatedCounter>
  }
#And
  {
    DotVar1
  #Equals
    <exit-code>
      DotVar10
    </exit-code>
  }
#And
  {
    DotVar3
  #Equals
    <network>
      <activeAccounts>
        DotVar34
      </activeAccounts>
      <accounts>
        DotVar33
      </accounts>
      <txOrder>
        DotVar32
      </txOrder>
      <txPending>
        DotVar31
      </txPending>
      <messages>
        DotVar30
      </messages>
    </network>
  }
#And
  {
    JUMPDESTS
  #Equals
    SetItem ( 3 )
    SetItem ( 20 )
  }
#And
  {
    _1
  #Equals
    <id>
      _10
    </id>
  }
#And
  {
    _2
  #Equals
    <caller>
      _20
    </caller>
  }
#And
  {
    _3
  #Equals
    <callData>
      _30
    </callData>
  }
#And
  {
    _4
  #Equals
    <callValue>
      _40
    </callValue>
  }
#And
  {
    _5
  #Equals
    <static>
      _50
    </static>
  }
#And
  {
    _6
  #Equals
    <callDepth>
      _60
    </callDepth>
  }
#And
  {
    _7
  #Equals
    <output>
      _70
    </output>
  }
#And
  {
    _8
  #Equals
    <statusCode>
      _80
    </statusCode>
  }
#And
  {
    _9
  #Equals
    <interimStates>
      _90
    </interimStates>
  }
#And
  {
    _10
  #Equals
    <touchedAccounts>
      _100
    </touchedAccounts>
  }
#And
  {
    _11
  #Equals
    <substate>
      <selfDestruct>
        _112
      </selfDestruct>
      <log>
        _111
      </log>
      <refund>
        _110
      </refund>
    </substate>
  }
#And
  {
    _12
  #Equals
    <gasPrice>
      _120
    </gasPrice>
  }
#And
  {
    _13
  #Equals
    <origin>
      _130
    </origin>
  }
#And
  {
    _14
  #Equals
    <blockhashes>
      _140
    </blockhashes>
  }
#And
  {
    _15
  #Equals
    <block>
      <previousHash>
        _1515
      </previousHash>
      <ommersHash>
        _1514
      </ommersHash>
      <coinbase>
        _1513
      </coinbase>
      <stateRoot>
        _1512
      </stateRoot>
      <transactionsRoot>
        _1511
      </transactionsRoot>
      <receiptsRoot>
        _1510
      </receiptsRoot>
      <logsBloom>
        _159
      </logsBloom>
      <difficulty>
        _158
      </difficulty>
      <number>
        _157
      </number>
      <gasLimit>
        _156
      </gasLimit>
      <gasUsed>
        _155
      </gasUsed>
      <timestamp>
        _154
      </timestamp>
      <extraData>
        _153
      </extraData>
      <mixHash>
        _152
      </mixHash>
      <blockNonce>
        _151
      </blockNonce>
      <ommerBlockHeaders>
        _150
      </ommerBlockHeaders>
    </block>
  }
#And
  {
    notBool 1 +Int ( 1 +Int #sizeWordStack ( WS , 0 ) ) +Int 0 >Int 1024
  #Equals
    true
  }
#And
  {
    true
  #Equals
    I >=Int 0 andBool S >=Int 0 andBool S +Int I *Int ( I +Int 1 ) /Int 2 <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 andBool #sizeWordStack ( WS , 0 ) <Int 1021 andBool G >=Int 52 *Int I +Int 21
  }```

**Comment by ttuegel** [comment]
>     There are some useless substitution in the constraint like

I don't think that substitutions involving claim variables are useless, at least not from the perspective of display in the frontend. @virgil-serbanuta can probably say more.

**Comment by ttuegel** [comment]
> we need to think about a way to call repl so that changes to kore-exec will automatically work on kore-repl?

The way to do this is to remove all the code from the executables to the libraries.

**Comment by virgil-serbanuta** [comment]
1. This should fix the replProve vs prove issue:
https://github.com/kframework/kore/pull/1048

**Comment by virgil-serbanuta** [comment]
2. Substitutions are not useless from a backend perspective, we receive a configuration, change it with the expansion thing, then add the substitution to the result to explain why we're proving something else. I think it would be incorrect to not return it.

I think that the (frontend?) code which takes the full configuration and removes some cells that it deems unrelevant should also remove the substitutions that only make sense in the context of those cells.

I also think that I can easily be wrong about these two, so what do you think?

**Comment by yzhang90** [comment]
@virgil-serbanuta What you said makes sense to me. Knowing the substitution can help debugging sometimes, but it is quite annoying to see those substitutions in repl every time i want to print the config. Can we log those substitutions at the beginning and get rid of them during symbolic execution?

When we generate the proof object, we need to show that proving
```
∀S. Cfg(S) => φ(S)
```
is equivalent to proving
```
∀p. Cfg(C(p)) => φ(C(p))
```
, Given that C is the only constructor of the sort.
I think we only need the substitution when showing the equivalence.
When we start to prove
```∀p. Cfg(C(p)) => φ(C(p))```, we no longer need the substitution. 
That's why i think we can get rid of it.

**Comment by virgil-serbanuta** [comment]
After some more thinking, my short-term concern is that the user asks us to prove that
```
∀S. Cfg(S) => φ(S)
```
and our backend gets stuck with some configuration deriving from `Cfg(C(p))`, and there's no explanation for where that `C(p)` came from, and what happened to `S`. That can, indeed, be solved by logging the substitution separately.

Doing proofs will anyway be different enough than what we currently do, so having the information available internally may be enough.

**Comment by yzhang90** [comment]
@virgil-serbanuta  Glad that we are on the same page. Are you going to open a PR for this?

**Comment by virgil-serbanuta** [comment]
Maybe, I need to have an explicit approval for this task, @ttuegel in case he is interested in assigning it to me.

**Comment by ttuegel** [comment]
@virgil-serbanuta I put this task on the Iteration board; you don't need my approval to pick it up. (Even if it wasn't on the board, it's bugging somebody who uses the backend, we should fix it.)

**Comment by yzhang90** [comment]
@virgil-serbanuta it seems that the extra substitution was eliminated in PR #1047, but are we keeping the substitution information in the log?

**Comment by virgil-serbanuta** [comment]
I looked into this, it seems that you were right, @yzhang90 , #1047 removed the substitutions. I created #1062 to finish the entire substitutions issue.

**Comment by ttuegel** [comment]
Needs #1069.
