### ISSUE TITLE
Investigate time limit on sum-to-n-spec.k

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1058]
The test exceeds the time limit after #1047; is this really a performance regression, or just inconsistency on Jenkins?

**Comment by virgil-serbanuta** [comment]
Is this about `sum-to-n-spec.k` as changed in #1000 , or the HEAD one?

**Comment by virgil-serbanuta** [comment]
I'm not sure this is related do #1047. This seems more like random noise. Here are the stats on my computer:

The unchanged sum-to-n-spec.k test:

before #1047: 3m4s
after #1047: 3m6s
at HEAD: 3m4s

sum-to-n-spec.k with the changes in #1000 patched in:
at HEAD: 15m12s
before #1407: 15m33s

Second claim in patched sum-to-n-spec.k:
at HEAD: 15m 44s
before #1407: 15m23s

**Comment by ttuegel** [comment]
Whoa, why do the changes from #1000 slow it down so much?

**Comment by virgil-serbanuta** [comment]
Because in #1000 we do a real proof. I think that, before, we were just doing the loop proof for a single iteration (i=0), with #1000 we have the full program proof and the loop proof for all i>=0 (I think that the full program proof is fast, the loop proof is slow, I'm investigating why).
