### ISSUE TITLE
Check that (concrete) map keys are distinct.

### ISSUE THREAD

**Issue by virgil-serbanuta** [kframework/kore#1077]
We check whether concrete map keys are not identical patterns, but that's not enough if we have unevaluated symbols.

As an example, say we have two total function symbols from int to int, `f` and `g`, that do not have any definition. Then, when taking the ceil of `{f(1) -> 1, g(1) -> 1}` we get `top`, but the map might still be bottom if `f(1) == g(1)`.

Also see the "ceil with map domain value" unit test.

**Comment by ttuegel** [comment]
I don't know what your thoughts are about this, but instead of allowing any concrete keys, we could allow only types of patterns that we know are fully evaluated—Int, Bool, String—but this might cause problems with semantics that use Maps from identifiers to values.

**Comment by virgil-serbanuta** [comment]
We can also allow anything that has a constructor or inj at the top.
