### ISSUE TITLE
Report errors in the execution graph

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1098]
We should catch and report errors in the execution graph as a [`ProofState`](https://github.com/kframework/kore/blob/master/kore/src/Kore/Strategies/ProofState.hs#L39). That is, one possible proof state is "encountered an error rewriting the parent configuration." This will make the REPL much more usable.

**Comment by vladciobanu** [comment]
Fixed by https://github.com/kframework/kore/pull/1111
