### ISSUE TITLE
Warn when introducing suspicious Implies

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1155]
We should emit a warning when a new node in the execution graph has an `\implies` predicate that does not occur as a subterm of the parent configuration. These predicates are intermediate states which should be simplified away; in every case we have seen, the persistence of such a predicate indicates a simplification error.

Suggestion from @yzhang90

**Comment by virgil-serbanuta** [comment]
BTW, do we have a way of telling whether our tests generate warnings? If yes, do we fail the test on warnings?

**Comment by ttuegel** [comment]
This is no longer a concern because the backend can correctly discharge these constraints.
