### ISSUE TITLE
Matching to iterate over Map and Set

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1183]
We need to support matching for functions to iterate over the keys of a Map or Set, as seen [here](https://github.com/kframework/evm-semantics/pull/532/files#diff-494b4c66d4128fe395a8c9607fab3629R1180-R1181).

~A sufficient and simple implementation is given [here](https://github.com/kframework/kore/issues/1045#issuecomment-539253453).~

The only thing we need to support right now is matching a single symbolic key with an opaque Map or Set term, something of the form `K |-> V M:Map`, against an arbitrary Map or Set. If `M` is also an opaque term in the Map or Set being matched, we should remove it from both and match the remainder. If `K` is a key in both, we should match the corresponding values and then match `M` against the remainder. Otherwise, we can pick an arbitrary key to match `K`, match the corresponding value to `V`, and match the remainder of the Map or Set to `M`.

See also: #1045

**Comment by denis-bogdanas** [comment]
@tomtomjhj `Set2List` and iterating over set still doesn't work in functions if Set elements are symbolic. Is this intended?

**Comment by ttuegel** [comment]
@denis-bogdanas No, can you provide a spec?

**Comment by denis-bogdanas** [comment]
turns out only `Set2List` doesn't work in functions, the rest works:
```
module ISSUE
  imports COLLECTIONS
  imports STRING

  configuration <k> $PGM:KItem </k>
                <theSet> .Set </theSet>

    syntax KItem ::= #checkArgWithList ( String )
                   | "#included"

    rule <k> #checkArgWithList(ARG) => #included ...</k>
         <theSet> S </theSet>
      requires ARG #in Set2List(S)

    syntax Bool ::= KItem "#in" List                                                       [function, functional]
    rule X #in ListItem(A) L:List => X ==K A orBool X #in L                                [simplification]
    rule X #in .List => false                                                              [simplification]
endmodule
```

```
module INCLUDEDLIST-SPEC
  imports ISSUE

  rule <k> #checkArgWithList("foo") => #included </k>
       <theSet> SetItem("foo") SetItem(A:KItem) </theSet>
    requires A =/=K "foo"
endmodule
```
Result:
```
  #Not ( {
    "foo" #in Set2List ( SetItem ( "foo" )
    SetItem ( A ) )
  #Equals
    true
  } )
#And
  #Not ( {
    A
  #Equals
    "foo"
  } )
#And
  <generatedTop>
    <k>
      #checkArgWithList ( "foo" )
    </k>
    <theSet>
      SetItem ( "foo" )
      SetItem ( A )
    </theSet>
  </generatedTop>
```

**Comment by ttuegel** [comment]
@denis-bogdanas It is expected that hook functions like `Set2List` would generally only work with concrete inputs, and in this particular case it looks like it would be better to use the `Set` directly, anyway.
