### ISSUE TITLE
kore-parser needs --version

### ISSUE THREAD

**Issue by radumereuta** [kframework/kore#123]
This should be fairly easy to add.
Working with multiple versions and switching from one branch to another can get confusing sometimes.
This should allow you to make sure you are working with the correct version.
As a reminder, this is how we used to do it for K:
```
c:\work\test>kompile --version
K framework version 4.0.1-SNAPSHOT
Git revision: 20d4249
Git branch: c-tests3
Build date: Mon Feb 19 14:36:51 EET 2018
```

**Comment by njohnwalker** [comment]
This feature is now in the master branch, I made some slight changes to the version string, and the "K framework version _________" does not yet work, but it doesn't seem like we are tracking version changes like that yet anyway.  Let me know what you think

**Comment by radumereuta** [comment]
```
c:\work\kore>kore-parser --version
K framework version UNKNOWN
Git:
  revision:     738fd5f86046b952af144139550839fa2aef0cb8
  branch:       master
  last commit:  2018 Jun 26 15:07:27 -0500
Build date:     2018 Jun 27 11:24:54 LOCAL
```
Looks great. #127 did the job. Thanks.
