### ISSUE TITLE
Boundary pattern matching

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1262]
We would like to accept a pattern, generated by the frontend, to match the current proof goal and immediately perform the implication check. Usually, this will be a pattern to match certain cells in the source and target configurations, such as:

```
// Only the <k> and <pc> cells will be matched:
<k> K </k> <pc> PC </pc> <env> _ </env> => <k> K </k> <pc> PC </pc> <env> _ </env>
```

I would like for the frontend to output the pattern to match the entire goal (rather than only the configuration) because it saves us from having to separately transmit the list of important variables. If matching the goal turns out to be too complicated in the frontend, though, we can do it some other way.

If we have a boundary pattern, we should *only* check the implication if it matches. This is a sound proof tactic, though incomplete; it places the burden of completeness on the proof engineer. That is, there are true theorems which cannot be proven with the wrong boundary pattern.

---

- [ ] Frontend produces the boundary pattern in Kore format
- [ ] `--boundary-pattern FILENAME` option
- [ ] Do not continue execution _after_ boundary pattern matches.
- [ ] Do not check implication _until_ boundary pattern matches.

**Comment by yzhang90** [comment]
I'm not sure that I understand the subtlety of the boundary pattern. In the current backend, we have a `removeDestination` step, which unifies the current configuration and the RHS of the claim. If unification succeed, then we will remove the destination from the proof goal (similar to check implication, but more general). If fail, we will continue the symbolic execution. Could you elaborate more on which part should be changed?

**Comment by ttuegel** [comment]
> Could you elaborate more on which part should be changed?

I think the `removeDestination` step is rather expensive and we should not do this until the boundary pattern matches. At least, we should have the _option_ to postpone it until the boundary pattern matches.

**Comment by ttuegel** [comment]
This was made unnecessary by #1270.
