### ISSUE TITLE
Simplify right-hand side of claims

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1278]
Should we simplify the right-hand side of claims at startup? Does it matter, if we implement #1270?

**Comment by yzhang90** [comment]
Suppose we have a claim
```
 rule <k> #start => #end </k> <a> X  => #fun2(X)</a>
```
and semantics rule
```
rule <k> #start => #step1 </k> <a> X </a> requires X > 0
```
In the `removeDestination` step after applying the semantics rule, even if we do unification first, and the unification in the <k> cell fails, we still need to evaluate  `#fun2(X)`, is it correct?

But in most cases, #fun2 would be either unsimplifiable or its argument is concrete. If it is the latter case, function memoization should be helpful. 

I would postpone the implementation of this until we met some concrete examples where simplifying  RHS will greatly improve the performance.

**Comment by ttuegel** [comment]
Related: #1278, #1304

**Comment by ttuegel** [comment]
We discussed this today. We might consider evaluating functions on the right-hand side, but avoiding other simplification which could cause branching.

**Comment by ttuegel** [comment]
> Does it matter, if we implement #1270?

The answer to this question, now that #1270 is finished, is "yes, it matters".

**Comment by ttuegel** [comment]
We presently cache all function evaluations with concrete (constructor-like) arguments. In the actual cases I have seen, this suffices to speed up proving, but I would like to investigate a little before closing this issue.

**Comment by ttuegel** [comment]
#1945 documents a case where a valid claim cannot be proven because the right-hand side is not evaluated. Specifically, an `ensures` condition must be used to apply a user-defined equation.

**Comment by ttuegel** [comment]
The solution here is to modify the internal representation of claims as follows:

```.hs
data ProtoReachabilityClaim =
    ProtoReachabilityClaim
    { left :: !(Pattern RewritingVariableName)
    , existentials :: ![RewritingVariable]
    , right :: !(OrPattern RewritingVariableName)
    }
```

When simplifying the left-hand side of the claim, the proof will branch when it encounters a disjunction. When simplifying the right-hand side of the claim, the backend will store any disjunction in the `OrPattern`. The `Simplify` step of the proof should simplify both sides, using the `requires` as a side-condition for simplifying the right-hand side.

**Comment by ehildenb** [comment]
One case where we think it may improve the performance is on the KEVM proof `tests/specs/benchmarks/overflow00-nooverflow-spec.k` on KEVM. It spends 4+min evaluated `#encodeArgs`, which shows up on the RHS of a claim, but should be simplifiable once and then left alone.

**Comment by ehildenb** [comment]
But my thought is that we shouldn't just simplify it once at startup. Every time you go to check if we're subsumed in the RHS it should be simplified as much as the path condition allows. Each step in the execution may add constraints to the path condition which allow further evaluation of the RHS of the claim.

**Comment by ttuegel** [comment]
This is undoubtedly important for performance, but it's not an improvement that will impact ERC20 proofs because these do not use functions on the right-hand side of claims: https://runtimeverification.slack.com/archives/CBNGEMMUP/p1594581215029700
