### ISSUE TITLE
Attribute to suppress `No evaluators for function symbol` warning

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1290]
It is very common to have constant functions that have no evaluators in the spec. It is very annoying to see a list of warning `No evaluators for function symbol: ...` in the command line.

**Comment by ttuegel** [comment]
@yzhang90 If the warning is not displayed by default, then there is no point in having it at all. How do you feel about these alternatives?

1. A symbol attribute that turns off the warning for the associated symbol.
1. Turn off the warning (always) for constant functions.

**Comment by yzhang90** [comment]
I think an attribute like `no-evaluator` will be more general.

**Comment by yzhang90** [comment]
another solution is to print 'No evaluators' warnings once at the beginning and do not print any `'No evaluators' warnings again during the execution.

**Comment by ttuegel** [comment]
We should:

- [ ] Add a symbol attribute `no-evaluators`.
- [ ] Turn off `WarnFunctionWithoutEvaluators` for symbols with this attribute.
