### ISSUE TITLE
Slow startup of ERC20 proof

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1310]
The `ds-token-erc20/totalSupply-spec.k` proof is very slow to start.

```
./kevm prove --backend haskell tests/specs/ds-token-erc20/totalSupply-spec.k -m VERIFICATION --depth 0
```

**Comment by ttuegel** [comment]
@yzhang90 Could you debug this with the [Kore profiling](https://github.com/kframework/kore/wiki/Profiling#kore-profiling) instructions on our Wiki?

**Comment by yzhang90** [comment]
Modify the semantics (https://github.com/kframework/evm-semantics/tree/bytes-optimized) and now the step 0 takes 3m28.525s to finish
