### ISSUE TITLE
Potential space leakage of Kore-repl/Kore-exec

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1335]
k-master: 413f849a889 + kore-master: b523da7 + kevm: https://github.com/kframework/evm-semantics/tree/edsl2

I ran the following command 
```
kprove --haskell-backend-command "/home/zy/workspace/kore/.build/kore/bin/kore-repl --repl-script /home/zy/workspace/kore/dist/kast.kscript " \
    ~/workspace/evm-semantics/tests/specs/erc20/ds/balanceOf-spec.k \
    -d ~/workspace/evm-semantics/.build/defn/haskell/ \
    --def-module VERIFICATION \
    --concrete-rules EDSL.#ceil32,EDSL.keccakIntList,EVM-DATA.#signed.positive,EVM-DATA.#signed.negative,EVM-DATA.#unsigned.positive,EVM-DATA.#unsigned.negative,EVM-DATA.powmod.nonzero,EVM-DATA.powmod.zero,EVM-DATA.signextend.invalid,EVM-DATA.signextend.negative,EVM-DATA.signextend.positive,EVM-DATA.keccak,EVM-DATA.#asWord.recursive,EVM-DATA.#asByteStack,EVM-DATA.#asByteStackAux.recursive,EVM-DATA.#padToWidth,EVM-DATA.#padRightToWidth,EVM-DATA.#newAddr,EVM-DATA.#newAddrCreate2,EVM-DATA.mapWriteBytes.recursive,EVM-DATA.#range,EVM-DATA.#lookup.some,EVM-DATA.#lookup.none,EVM.#memoryUsageUpdate.some,EVM.Cgascap,EVM.Csstore.new,EVM.Csstore.old,EVM.Rsstore.new,EVM.Rsstore.old,EVM.Cextra,EVM.Cmem
``` 
followed by
```
stepf 44
```
 REPL runs for a while and eats 96% of the memory (I have a 32G memory).
However, if i type `stepf 11`  every time, the memory consumption can be maintained at a reasonable ratio. (e.g., ~10% after executing 33 steps). 
I tried `kore-exec` with `--depth 33` and monitored it with `top`. memory peak: 68.1% time:~10mins. memory consumption is always increasing.

**Comment by yzhang90** [comment]
only `graph` command will reduce the memory consumption from ~80% to ~3%

**Comment by ttuegel** [comment]
> only `graph` command will reduce the memory consumption from ~80% to ~3%

Sorry, I'm not sure what this means. Did you run `stepf 33`, find memory usage about 80%, and then run `graph` and found memory usage dropped to about 3%?

**Comment by yzhang90** [comment]
yes

**Comment by ttuegel** [comment]
This smells like a space leak: some unevaluated thunks which can finally be collected after the graph is computed. The fact that it's the `graph` command which clears them suggests to me that it has something to do with keeping track of the applied rules, but we should measure instead of guess. 

The GHC manual has some [advice for detecting space leaks](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/sooner.html#thriftier-producing-a-program-that-gobbles-less-heap-space). Here is some [more opinionated advice](https://github.com/haskell-perf/checklist#have-you-checked-for-stack-space-leaks), in particular [this blog post](http://neilmitchell.blogspot.co.uk/2015/09/detecting-space-leaks.html?m=1). However, be aware that all the `recursion-schemes` algorithms—which we use extensively—seem to use linear stack space by design, so they are likely to produce false positives by this method. Therefore, I recommend starting with basic [heap profiling](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/profiling.html#profiling-memory-usage).

**Comment by ttuegel** [comment]
We were having trouble getting this to work with profiling enabled, so to figure out what the baseline profiling overhead is, I'm trying a profiled build with this in `stack.yaml`:

```
ghc-options:
  "$everything": -fno-prof-auto
```

and building with `stack build --copy-bins --profile`. This will turn on profiling but not create any cost centers. If the overhead (of `kore-exec` with `--depth 0`) is not too much, I can turn on a conservative set of automatic cost centers by building with `stack build --copy-bins --profile --ghc-options=-fprof-auto-top`. However, I'm rebuilding all dependencies with profiling now, so I won't get to try until morning.

**Comment by ttuegel** [comment]
My comment above doesn't work because Stack disrespects `-fno-prof-auto`. :angry:

**Comment by ttuegel** [comment]
- Use compacting garbage collection for older generations.

**Comment by ttuegel** [comment]
> However, if i type `stepf 11` every time, the memory consumption can be maintained at a reasonable ratio. (e.g., ~10% after executing 33 steps).

@yzhang90 Have you verified that `stepf 11` _actually_ executes 33 steps? Can you provide a REPL script which reproduces this behavior?

**Comment by ttuegel** [comment]
> only `graph` command will reduce the memory consumption from ~80% to ~3%

I also cannot reproduce this. :slightly_frowning_face:

**Comment by yzhang90** [comment]
@ttuegel `stepf 11` executes 11 steps. this is how I use REPL:
```
kprove --haskell-backend-command "/home/zy/workspace/kore/.build/kore/bin/kore-repl --repl-script /home/zy/workspace/kore/dist/kast.kscript " ~/workspace/evm-semantics/tests/specs/erc20/ds/balanceOf-spec.k -d ~/workspace/evm-semantics/.build/defn/haskell/ --def-module VERIFICATION
``` ( --concrete-rules flags are not needed)
in REPL mode:
1. stepf 11 (memory consumption ~78%)
2. graph (memory consumption 3.7G,  ~10%)
33 steps means that I invoke the procedure: `stepf 11` followed by `graph` three times. Sorry about my poor explanation.

**Comment by ttuegel** [comment]
> Have you verified that `stepf 11` _actually_ executes 33 steps? Can you provide a REPL script which reproduces this behavior?

Talked to @ana-pantilie: running `stepf 11` three times does not run 33 steps, it runs the same 11 steps three times.

**Comment by yzhang90** [comment]
sorry....I fogot to mention `select XX` which jumps to the frontier.
