### ISSUE TITLE
KEVM concrete tests time out

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#1348]
The following tests all time out on KEVM using Haskell backend (120s timeout, but longer runs gave no indication of them finishing):

```
tests/ethereum-tests/VMTests/vmLogTest/log3_logMemsizeZero.json
tests/ethereum-tests/VMTests/vmLogTest/log2_nonEmptyMem.json
tests/ethereum-tests/VMTests/vmLogTest/log3_nonEmptyMem_logMemSize1.json
tests/ethereum-tests/VMTests/vmLogTest/log_2logs.json
tests/ethereum-tests/VMTests/vmLogTest/log3_nonEmptyMem_logMemSize1_logMemStart31.json
tests/ethereum-tests/VMTests/vmLogTest/log1_nonEmptyMem_logMemSize1_logMemStart31.json
tests/ethereum-tests/VMTests/vmLogTest/log2_Caller.json
tests/ethereum-tests/VMTests/vmLogTest/log1_logMemsizeZero.json
tests/ethereum-tests/VMTests/vmLogTest/log4_emptyMem.json
tests/ethereum-tests/VMTests/vmLogTest/log1_MaxTopic.json
tests/ethereum-tests/VMTests/vmLogTest/log4_nonEmptyMem_logMemSize1.json
tests/ethereum-tests/VMTests/vmLogTest/log2_nonEmptyMem_logMemSize1.json
tests/ethereum-tests/VMTests/vmLogTest/log3_Caller.json
tests/ethereum-tests/VMTests/vmLogTest/log4_nonEmptyMem_logMemSize1_logMemStart31.json
tests/ethereum-tests/VMTests/vmLogTest/log3_emptyMem.json
tests/ethereum-tests/VMTests/vmLogTest/log1_nonEmptyMem_logMemSize1.json
tests/ethereum-tests/VMTests/vmLogTest/log2_emptyMem.json
tests/ethereum-tests/VMTests/vmLogTest/log3_PC.json
tests/ethereum-tests/VMTests/vmLogTest/log2_MaxTopic.json
tests/ethereum-tests/VMTests/vmLogTest/log1_Caller.json
tests/ethereum-tests/VMTests/vmLogTest/log4_MaxTopic.json
tests/ethereum-tests/VMTests/vmLogTest/log1_nonEmptyMem.json
tests/ethereum-tests/VMTests/vmLogTest/log2_logMemsizeZero.json
tests/ethereum-tests/VMTests/vmLogTest/log4_Caller.json
tests/ethereum-tests/VMTests/vmLogTest/log4_nonEmptyMem.json
tests/ethereum-tests/VMTests/vmLogTest/log0_nonEmptyMem_logMemSize1.json
tests/ethereum-tests/VMTests/vmLogTest/log1_emptyMem.json
tests/ethereum-tests/VMTests/vmLogTest/log4_PC.json
tests/ethereum-tests/VMTests/vmLogTest/log4_logMemsizeZero.json
tests/ethereum-tests/VMTests/vmLogTest/log3_nonEmptyMem.json
tests/ethereum-tests/VMTests/vmLogTest/log2_nonEmptyMem_logMemSize1_logMemStart31.json
tests/ethereum-tests/VMTests/vmLogTest/log3_MaxTopic.json
tests/ethereum-tests/VMTests/vmLogTest/log0_nonEmptyMem_logMemSize1_logMemStart31.json
tests/ethereum-tests/VMTests/vmLogTest/log0_nonEmptyMem.json
tests/ethereum-tests/VMTests/vmLogTest/log0_logMemsizeZero.json
tests/ethereum-tests/VMTests/vmLogTest/log0_emptyMem.json
```

These are not particularly long-running tests, and they all have to do with the `LOG(_)` opcode, so I suspect something is going on with one of the functions being evaluated in this rule:

```
    syntax LogOp ::= LOG ( Int ) 
 // ---------------------------- 
    rule <k> LOG(N) MEMSTART MEMWIDTH => . ... </k> 
         <id> ACCT </id> 
         <wordStack> WS => #drop(N, WS) </wordStack> 
         <localMem> LM </localMem> 
         <log> ... (.List => ListItem({ ACCT | WordStack2List(#take(N, WS)) | #range(LM, MEMSTART, MEMWIDTH) })) </log> 
      requires #sizeWordStack(WS) >=Int N 
```

Please add least add one of these tests to the `smoke_tests_run` variable in the KEVM `Makefile` to ensure this is tested on KEVM PRs once this issue is fixed.

**Comment by ehildenb** [comment]
Note that these tests correspond _exactly_ to those tests which take > 20% of their total execution time in _kernel_ time instead of in _user_ time.

```
0.27  tests/ethereum-tests/VMTests/vmLogTest/log_2logs.json
0.28  tests/ethereum-tests/VMTests/vmLogTest/log2_MaxTopic.json
0.28  tests/ethereum-tests/VMTests/vmLogTest/log3_nonEmptyMem.json
0.28  tests/ethereum-tests/VMTests/vmLogTest/log4_Caller.json
0.28  tests/ethereum-tests/VMTests/vmLogTest/log4_nonEmptyMem_logMemSize1_logMemStart31.json
0.28  tests/ethereum-tests/VMTests/vmLogTest/log4_PC.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log1_Caller.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log1_logMemsizeZero.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log1_MaxTopic.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log1_nonEmptyMem.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log1_nonEmptyMem_logMemSize1.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log1_nonEmptyMem_logMemSize1_logMemStart31.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log2_Caller.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log2_logMemsizeZero.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log2_nonEmptyMem.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log2_nonEmptyMem_logMemSize1.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log2_nonEmptyMem_logMemSize1_logMemStart31.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log3_Caller.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log3_logMemsizeZero.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log3_MaxTopic.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log3_nonEmptyMem_logMemSize1.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log3_nonEmptyMem_logMemSize1_logMemStart31.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log3_PC.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log4_logMemsizeZero.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log4_MaxTopic.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log4_nonEmptyMem.json
0.29  tests/ethereum-tests/VMTests/vmLogTest/log4_nonEmptyMem_logMemSize1.json
0.30  tests/ethereum-tests/VMTests/vmLogTest/log0_nonEmptyMem_logMemSize1_logMemStart31.json
0.30  tests/ethereum-tests/VMTests/vmLogTest/log1_emptyMem.json
0.30  tests/ethereum-tests/VMTests/vmLogTest/log2_emptyMem.json
0.30  tests/ethereum-tests/VMTests/vmLogTest/log3_emptyMem.json
0.30  tests/ethereum-tests/VMTests/vmLogTest/log4_emptyMem.json
0.31  tests/ethereum-tests/VMTests/vmLogTest/log0_logMemsizeZero.json
0.31  tests/ethereum-tests/VMTests/vmLogTest/log0_nonEmptyMem.json
0.31  tests/ethereum-tests/VMTests/vmLogTest/log0_nonEmptyMem_logMemSize1.json
0.32  tests/ethereum-tests/VMTests/vmLogTest/log0_emptyMem.json
```

Here the number on the left is what fragment of time is spent in kernel time before timing out at 120s.

**Comment by ttuegel** [comment]
These tests no longer time-out, but they do have a large number of added side conditions. The conditions are concrete and should be evaluated.

**Comment by ttuegel** [comment]
These tests now fail:

- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log0_emptyMem.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log0_logMemsizeZero.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log0_nonEmptyMem.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log0_nonEmptyMem_logMemSize1.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log0_nonEmptyMem_logMemSize1_logMemStart31.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log1_Caller.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log1_emptyMem.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log1_logMemsizeZero.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log1_MaxTopic.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log1_nonEmptyMem.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log1_nonEmptyMem_logMemSize1.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log1_nonEmptyMem_logMemSize1_logMemStart31.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log2_Caller.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log2_emptyMem.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log2_logMemsizeZero.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log_2logs.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log2_MaxTopic.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log2_nonEmptyMem.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log2_nonEmptyMem_logMemSize1.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log2_nonEmptyMem_logMemSize1_logMemStart31.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log3_Caller.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log3_emptyMem.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log3_logMemsizeZero.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log3_MaxTopic.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log3_nonEmptyMem.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log3_nonEmptyMem_logMemSize1.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log3_nonEmptyMem_logMemSize1_logMemStart31.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log3_PC.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log4_Caller.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log4_emptyMem.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log4_logMemsizeZero.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log4_MaxTopic.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log4_nonEmptyMem.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log4_nonEmptyMem_logMemSize1.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log4_nonEmptyMem_logMemSize1_logMemStart31.json`
- [ ] `tests/ethereum-tests/VMTests/vmLogTest/log4_PC.json`

And these tests now time-out:

- [ ] `tests/ethereum-tests/VMTests/vmIOandFlowOperations/BlockNumberDynamicJump0_foreverOutOfGas.json`
- [ ] `tests/ethereum-tests/VMTests/vmIOandFlowOperations/DynamicJump0_foreverOutOfGas.json`
- [ ] `tests/ethereum-tests/VMTests/vmIOandFlowOperations/JDfromStorageDynamicJump0_foreverOutOfGas.json`
- [ ] `tests/ethereum-tests/VMTests/vmIOandFlowOperations/jump0_foreverOutOfGas.json`
- [ ] `tests/ethereum-tests/VMTests/vmIOandFlowOperations/loop_stacklimit_1020.json`
- [ ] `tests/ethereum-tests/VMTests/vmIOandFlowOperations/loop_stacklimit_1021.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/ackermann31.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/ackermann32.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/ackermann33.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/fibonacci10.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/fibonacci16.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/loop-exp-16b-100k.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/loop-exp-1b-1M.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/loop-exp-2b-100k.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/loop-exp-32b-100k.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/loop-exp-4b-100k.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/loop-exp-8b-100k.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/loop-exp-nop-1M.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/loop-mul.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/loop-mulmod-2M.json`
- [ ] `tests/ethereum-tests/VMTests/vmPerformance/manyFunctions100.json`

**Comment by ttuegel** [comment]
@ehildenb I cannot reproduce the test failures in any of the tests listed above. Were these tests running at the same time as other tests? Maybe they were killed from resource contention, for example if another test had high memory use.
