### ISSUE TITLE
Comparatively bad performance on some concrete tests

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#1349]
When comparing the Haskell backend to the Java backend on KEVM concrete tests (574 tests total), we have:

-   392 tests which the Haskell backend finishes faster than the Java backend,
-   108 tests which finish within 2x the time of the Java backend (< 2x slowdown),
-   36 tests which timeout unexpectedly (see #1348 ), and
-   38 tests which take more than 2x the time of the Java backend.

This issue concerns the last category of tests, because it indicates that there are more efficient ways to handle those tests which the Java backend is taking advantage of but the Haskell backend is not. This is that list (note that we jump from 1.77x max slowdown in other tests to 2.82x slowdown in this list):

```
2.82 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_29.json
2.87 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_11.json
2.89 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_8.json
2.90 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_1.json
2.94 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_28.json
2.94 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_9.json
2.94 tests/ethereum-tests/VMTests/vmArithmeticTest/fibbonacci_unrolled.json
2.95 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_23.json
2.96 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_0.json
2.97 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_16.json
2.98 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_25.json
2.99 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_31.json
2.99 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_4.json
3.01 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_21.json
3.01 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_32.json
3.02 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_2.json
3.04 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_10.json
3.04 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_6.json
3.05 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_30.json
3.06 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_12.json
3.06 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_18.json
3.07 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_14.json
3.07 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_20.json
3.08 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_27.json
3.09 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_19.json
3.10 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_24.json
3.11 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_3.json
3.12 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_17.json
3.12 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_22.json
3.13 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_33.json
3.14 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_26.json
3.14 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_5.json
3.16 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_7.json
3.17 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_15.json
3.18 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_13.json
3.69 tests/ethereum-tests/VMTests/vmIOandFlowOperations/jumpdestBigList.json
4.86 tests/ethereum-tests/VMTests/vmIOandFlowOperations/byte1.json
5.37 tests/ethereum-tests/VMTests/vmIOandFlowOperations/jumpi_at_the_end.json
```

**Comment by ttuegel** [comment]
> This issue concerns the last category of tests, because it indicates that there are more efficient ways to handle those tests which the Java backend is taking advantage of but the Haskell backend is not.

This might be true if we believed that there are no performance bugs in the Haskell backend. :grinning: This merits some investigation if it persists after #1335, #1318, #1310, and #1065 are resolved.

**Comment by ttuegel** [comment]
The aforementioned issues being solved, this merits renewed investigation.

**Comment by ehildenb** [comment]
On KEVM version e3c2c54ca (current `master` at time of posting).

More tests were feasible this time, here are tests that are more than 2.11x slowdown over the java backend (everything else ramps up pretty smoothly to 2.11x):

```
2.58 tests/ethereum-tests/VMTests/vmArithmeticTest/arith1.json
3.71 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_25.json
3.74 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_6.json
3.75 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_4.json
3.76 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_0.json
3.83 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_22.json
3.84 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_11.json
3.84 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_18.json
3.86 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_13.json
3.86 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_14.json
3.86 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_29.json
3.88 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_16.json
3.89 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_27.json
3.89 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_8.json
3.90 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_2.json
3.90 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_31.json
3.91 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_12.json
3.91 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_21.json
3.91 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_24.json
3.91 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_30.json
3.92 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_15.json
3.92 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_32.json
3.92 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_33.json
3.95 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_3.json
3.98 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_5.json
3.99 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_19.json
3.99 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_26.json
4.00 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_17.json
4.00 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_1.json
4.08 tests/ethereum-tests/VMTests/vmArithmeticTest/fibbonacci_unrolled.json
4.09 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_23.json
4.11 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_7.json
4.13 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_10.json
4.20 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_28.json
4.21 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_9.json
4.26 tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_20.json
4.60 tests/ethereum-tests/VMTests/vmIOandFlowOperations/jumpdestBigList.json
5.92 tests/ethereum-tests/VMTests/vmIOandFlowOperations/byte1.json
6.26 tests/ethereum-tests/VMTests/vmIOandFlowOperations/jumpi_at_the_end.json
13.07 tests/ethereum-tests/VMTests/vmIOandFlowOperations/for_loop1.json
13.07 tests/ethereum-tests/VMTests/vmIOandFlowOperations/for_loop2.json
```

Here is the entire file of tests that ran on both Java and Haskell backend, and their relative slowdown: [haskell-slowdown.txt](https://github.com/kframework/kore/files/4411745/haskell-slowdown.txt). 94 run quicker on Haskell backend. 440 run within 1.5x the time of the Java backend. 501 run within 2.11x the time of the Java backend.

Note that more tests ran this time around with the Haskell backend to completion, so the list looks different. But still the `expPowerOf256Of256` tests are slow, so we should investigate those I guess.

**Comment by ttuegel** [comment]
This is the latest slow list:

- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/arith1.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/fibbonacci_unrolled.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_22.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_11.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_1.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_29.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_13.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_16.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_23.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_10.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_25.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_12.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_18.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_21.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_24.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_26.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_9.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_31.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_17.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_15.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_32.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_6.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_28.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_3.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_33.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_7.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_19.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_5.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_27.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_4.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_2.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_8.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_30.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_14.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_0.json`
- [ ] `tests/ethereum-tests/VMTests/vmArithmeticTest/expPowerOf256Of256_20.json`
- [ ] `tests/ethereum-tests/VMTests/vmIOandFlowOperations/jumpdestBigList.json`
- [ ] `tests/ethereum-tests/VMTests/vmIOandFlowOperations/jumpi_at_the_end.json`
- [ ] `tests/ethereum-tests/VMTests/vmIOandFlowOperations/byte1.json`
- [ ] `tests/ethereum-tests/VMTests/vmIOandFlowOperations/for_loop2.json`
- [ ] `tests/ethereum-tests/VMTests/vmIOandFlowOperations/for_loop1.json`
