### ISSUE TITLE
KEVM concrete tests with unusually high kernel-time

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#1350]
Other than the tests which time-out concretely in #1348 (which each exhibit crazy high kernel times), some of the tests which finish successfully spend quite a bit of kernel time too. Might be worth investigating.

This is the list of tests which spend > 15% kernel time, but finish correctly within 120s. The number of the left is the quantity `kernel / (user + kernel)`:

```
0.16  tests/ethereum-tests/VMTests/vmIOandFlowOperations/jump0_outOfBoundary.json
0.16  tests/ethereum-tests/VMTests/vmIOandFlowOperations/jumpInsidePushWithoutJumpDest.json
0.16  tests/ethereum-tests/VMTests/vmIOandFlowOperations/jumpiToUint64maxPlus1.json
0.16  tests/ethereum-tests/VMTests/vmIOandFlowOperations/sstore_underflow.json
0.16  tests/ethereum-tests/VMTests/vmSha3Test/sha3_bigSize.json
0.17  tests/ethereum-tests/VMTests/vmIOandFlowOperations/DynamicJumpPathologicalTest2.json
0.17  tests/ethereum-tests/VMTests/vmIOandFlowOperations/jump0_AfterJumpdest.json
0.17  tests/ethereum-tests/VMTests/vmPushDupSwapTest/dup2error.json
0.17  tests/ethereum-tests/VMTests/vmPushDupSwapTest/swap2error.json
0.17  tests/ethereum-tests/VMTests/vmRandomTest/201503110219PYTHON.json
0.17  tests/ethereum-tests/VMTests/vmSha3Test/sha3_4.json
0.17  tests/ethereum-tests/VMTests/vmSha3Test/sha3_bigOffset.json
0.18  tests/ethereum-tests/VMTests/vmIOandFlowOperations/DynamicJumpPathologicalTest3.json
0.18  tests/ethereum-tests/VMTests/vmIOandFlowOperations/jumpTo1InstructionafterJump_noJumpDest.json
0.18  tests/ethereum-tests/VMTests/vmIOandFlowOperations/pop1.json
0.19  tests/ethereum-tests/VMTests/vmArithmeticTest/mulUnderFlow.json
0.19  tests/ethereum-tests/VMTests/vmIOandFlowOperations/jumpOntoJump.json
0.19  tests/ethereum-tests/VMTests/vmRandomTest/201503110206PYTHON.json
```

**Comment by ttuegel** [comment]
GHC's RTS allocates memory by page faulting, so the high kernel time is not alarming by itself. This issue should not merit investigation before the high-allocation issue (#1335) is fixed. After that, we can check that allocation, kernel time, and page faults are correlated by running `kore-exec` under `env GHCRTS='-S' time kore-exec ...`. The `time` command (_not_ shell builtin) will report the number of page faults and kernel time, and `GHCRTS='-S'` will report the total number of bytes allocated.
