### ISSUE TITLE
Cannot write spec about arbitrary map

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#1376]
With the following specification:

```
module SET-BALANCE 
    imports INT 
    imports DOMAINS 
    imports COLLECTIONS 
 
    configuration 
      <set-balance> 
        <k> $ACTION:Action </k> 
        <accounts> 
          <account multiplicity="*" type="Map"> 
            <accountID> .AccountId:AccountId </accountID> 
            <freeBalance> 0 </freeBalance> 
            <reservedBalance> 0 </reservedBalance> 
          </account> 
        </accounts> 
      </set-balance> 
 
    syntax Action ::= ".Action" | EntryAction 
    syntax EntryAction ::= ".EntryAction" 
 
    syntax AccountId ::= ".AccountId" | Int 
 // --------------------------------------- 
 
    syntax Int ::= "total_balance" "(" AccountId ")" [function, functional] 
 // ----------------------------------------------------------------------- 
    rule total_balance(WHO) => free_balance(WHO) +Int reserved_balance(WHO) 
 
    syntax Int ::= "free_balance" "(" AccountId ")" [function, functional] 
 // ---------------------------------------------------------------------- 
    rule    free_balance(_)   => 0 [owise] 
    rule [[ free_balance(WHO) => FREE_BALANCE ]] 
         <account> 
           <accountID> WHO </accountID> 
           <freeBalance> FREE_BALANCE </freeBalance> 
           ... 
         </account> 
 
    syntax Int ::= "reserved_balance" "(" AccountId ")" [function, functional] 
 // -------------------------------------------------------------------------- 
    rule    reserved_balance(_)   => 0 [owise] 
    rule [[ reserved_balance(WHO) => FREE_BALANCE ]] 
         <account> 
           <accountID> WHO </accountID> 
           <reservedBalance> FREE_BALANCE </reservedBalance> 
           ... 
         </account> 
endmodule 
```

We cannot prove the following claim:

```

```requires "set-balance.k" 
 
module VERIFICATION 
    imports SET-BALANCE 
 
    syntax EntryAction ::= totalBalance ( AccountId ) 
    rule <k> totalBalance(AID) => total_balance(AID) ... </k> 
endmodule 
 
module SET-BALANCE-SPEC 
    imports VERIFICATION 
       
    rule <k> totalBalance(AID) => 50 ... </k> 
         <accounts> 
           <account> 
             <accountID> AID </accountID> 
             <freeBalance> 30 </freeBalance> 
             <reservedBalance> 20 </reservedBalance> 
             ... 
           </account> 
           ... 
         </accounts> 
endmodule 
```

Because it cannot prove that the `AccountCellMap` is well defined (I think):

```
  #Ceil ( <account>
    <accountID>
      AID
    </accountID>
    <freeBalance>
      30
    </freeBalance>
    <reservedBalance>
      20
    </reservedBalance>
  </account> DotVar3 )
#And
  <set-balance>
    <k>
      free_balance ( AID ) <set-balance>
        <k>
          totalBalance ( AID ) ~> DotVar2
        </k>
        <accounts>
          <account>
            <accountID>
              AID
            </accountID>
            <freeBalance>
              30
            </freeBalance>
            <reservedBalance>
              20
            </reservedBalance>
          </account> DotVar3
        </accounts>
      </set-balance> +Int reserved_balance ( AID ) <set-balance>
        <k>
          totalBalance ( AID ) ~> DotVar2
        </k>
        <accounts>
          <account>
            <accountID>
              AID
            </accountID>
            <freeBalance>
              30
            </freeBalance>
            <reservedBalance>
              20
            </reservedBalance>
          </account> DotVar3
        </accounts>
      </set-balance> ~> DotVar2
    </k>
    <accounts>
      <account>
        <accountID>
          AID
        </accountID>
        <freeBalance>
          30
        </freeBalance>
        <reservedBalance>
          20
        </reservedBalance>
      </account> DotVar3
    </accounts>
  </set-balance>
```

I think it should be safe to assume that we start in an initial state where the `*CellMap`s are well-defined, which means that the keys are distinct. If not, I can add explicit side-conditions to make it so, but what side conditions should I add?

Attaching the relevant `*.kore` files.
[kore.tar.txt](https://github.com/kframework/kore/files/3985366/kore.tar.txt)

**Comment by ehildenb** [comment]
Note that removing the `...` in the `<accounts>` cell makes the proof go through:

```
    rule <k> totalBalance(AID) => 50 ... </k> 
         <accounts> 
           <account> 
             <accountID> AID </accountID> 
             <freeBalance> 30 </freeBalance> 
             <reservedBalance> 20 </reservedBalance> 
             ... 
           </account> 
         </accounts> 
```

But we want to be able to prove this property for _any_ well-defined map where the given account is defined.

**Comment by ttuegel** [comment]
> I think it should be safe to assume that we start in an initial state where the `*CellMap`s are well-defined, which means that the keys are distinct.

That is what the `#Ceil` in the condition means: the backend has inferred the definedness of the initial condition. I don't think this has anything to do with definedness. The problem is evaluating the `freeBalance` function at the top of the `<k>` cell, by matching on the symbolic key. When there is no `...` in the `<accounts>` cell, matching works as expected.

**Comment by ttuegel** [comment]
@virgil-serbanuta Looking at the matcher code, it looks like we specifically reject cases that have an opaque variable in the term: [here](https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Axiom/Matcher.hs#L670). But, I recall an earlier version of your pull request that didn't do this?

**Comment by virgil-serbanuta** [comment]
I think that my earlier versions actually did more filtering (i.e. they also checked for excessAbstract2). IIRC the opaque term was there before my PR and I didn't touch it. I think we can't just remove it, we have to add some special cases where we can unify with it (e.g. when all the excess stuff is empty).

I can probably work on this, either preempting my current task, or after it.

**Comment by ttuegel** [comment]
> I can probably work on this, either preempting my current task, or after it.

I don't think either one is urgent because I doubt many people are going to be blocked over the holidays, but I think this is blocking some Polkadot work (@ehildenb please correct me if not). If that's the case, I would consider it slightly higher priority than the function evaluation task

**Comment by virgil-serbanuta** [comment]
Ok then, I'll try fixing this before my current task.

I'm adding this to the current iteration.
