### ISSUE TITLE
Support priority attribute for functional rules

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1389]
for example, if we want to apply the following rule only if one of the arguments is not concrete.
```
    rule BUF [START .. WIDTH] => #bufSeg(BUF, START, WIDTH)
```
In order to do that, we can mark the original rule as concrete, and give lower priority to the above rule.

**Comment by ttuegel** [comment]
The appetite for this issue explicitly includes time for refactoring `Kore.Step.Axiom.Registry.axiomPatternsToEvaluators`, including changes to make this reasonable to unit test. (Building an axiom registry with prioritized rules and observing the priority by applying the evaluators is _not_ a reasonable way to unit test this.)
