### ISSUE TITLE
Simplify "A ∧ A → B" to "A ∧ B"

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1391]
kevm: edsl2 branch
When running `kprove --haskell-backend-command "/home/zy/workspace/kore/.build/kore/bin/kore-exec " ~/workspace/evm-semantics/tests/specs/erc20/ds/totalSupply-spec.k -d ~/workspace/evm-semantics/.build/defn/haskell/ --def-module VERIFICATION --depth 0`, I found the result has
```  
{
    #isIntegerMap ( M )
  #Equals
    true
  }
#And
  ( {
      #isIntegerMap ( M )
    #Equals
      true
    }
  #Implies
    {
      true
    #Equals
      0 <=Int ACCT_ID andBool ACCT_ID <=Int 1461501637330902918203684832716283019655932542975 andBool ( 0 <=Int CALLER_ID andBool CALLER_ID <=Int 1461501637330902918203684832716283019655932542975 ) andBool ( 0 <=Int ORIGIN_ID andBool ORIGIN_ID <=Int 1461501637330902918203684832716283019655932542975 ) andBool ( 0 <=Int CALL_DEPTH andBool CALL_DEPTH <Int 1024 ) andBool ( 0 <=Int #lookup ( M , 0 ) andBool #lookup ( M , 0 ) <=Int 115792089237316195423570985008687907853269984665640564039457584007913129639935 ) andBool #isIntegerMap ( M )
    } )
```
, I think it's better to get rid of the implication.

**Comment by ttuegel** [comment]
Another option (besides solving the implication) is to simply not generate the implication in the first place. I am not aware of any case where we can simplify it, and it's not clear to me why we should generate implications we can't simplify.

**Comment by ttuegel** [comment]
@virgil-serbanuta Can you comment on this issue?

**Comment by virgil-serbanuta** [comment]
We do that when we have something like `a == (b or c)`. We can, in principle, send an `implies` to the SMT, but I don't think we can send that equality (though I may be wrong). If so, then simplifying as described in the issue title would be preferable.

On the other hand, fixing https://github.com/kframework/kore/issues/1065 may prevent the `a == (b or c)` thing from occurring in the first place.

If we wouldn't need to take commutativity+associativity for `∧` into account, we could use an axiom to simplify this (would also need identifiers for `and` and, most likely, `implies`)

**Comment by virgil-serbanuta** [comment]
Now that I thought a bit more about it, if my theory above is true, it's likely that we are still missing a side condition somewhere, i.e. we might have been able to solve this without a function split.
