### ISSUE TITLE
Unregistered log entry type

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#1400]
When updating KEVM to use latest K master (branch: https://github.com/kframework/evm-semantics/pull/642), we cannot run the Haskell backend on the tests anymore because of a strange logging error:

```
git clone 'https://github.com/kframework/evm-semantics'
cd evm-semantics
git checkout fc905fc2
make deps RELEASE=true
make build-haskell -j8 RELEASE=true
make test-vm TEST_CONCRETE_BACKEND=haskell
```

This results in:

```
kore-exec: Tried to log nonexistent entry type. It should be added to Kore.Logger.Registry.registry.
CallStack (from HasCallStack):
  error, called at src/Kore/Logger/Registry.hs:150:9 in kore-0.0.1.0-DbkIMgzV0BgCAECOqpj1DA:Kore.Logger.Registry
```

**Comment by ttuegel** [comment]
I am also now suddenly encountering this [here](https://office.runtimeverification.com/jenkins/blue/organizations/jenkins/haskell-backend/detail/PR-1379/10/pipeline/#step-74-log-792).

**Comment by virgil-serbanuta** [comment]
I can, but I'm running an erc-related proof.

**Comment by virgil-serbanuta** [comment]
See the reproduction instructions here: https://github.com/kframework/kore/issues/1393 (but add a `make defn` before compiling the semantics), and use this PR: https://github.com/kframework/kore/pull/1398 . Takes > 15 min to get the error.

**Comment by virgil-serbanuta** [comment]
Ok, the error seems to be caused by `LogMessage`, which, I guess, means that we still use old-style log messages, but we didn't register them...

**Comment by ana-pantilie** [comment]
I think @virgil-serbanuta is right, it looks like we still use `LogMessage` in the `SMT` and in the `Simplifier`.
