### ISSUE TITLE
`graph pic` command generate 0 bytes picture.

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1403]
To reproduce:
Kevm: https://github.com/kframework/evm-semantics/tree/edsl2
kompile:
```
make defn
kompile --debug --main-module ETHEREUM-SIMULATION --backend haskell --hook-namespaces KRYPTO --syntax-module ETHEREUM-SIMULATION .build/defn/haskell/driver.k --directory .build/defn/haskell -I .build/defn/haskell
```
kprove:
```
kprove --haskell-backend-command "/home/zy/workspace/kore/.build/kore/bin/kore-repl --repl-script /home/zy/workspace/kore/dist/kast.kscript " ~/workspace/evm-semantics/tests/specs/erc20/ds/totalSupply-spec.k -d ~/workspace/evm-semantics/.build/defn/haskell/ --def-module VERIFICATION
```
in REPL:
```
stepf 650
graph a
```
it produces a.jpeg whose size is 0. However, it works if the graph is small.

**Comment by ana-pantilie** [comment]
I wasn't able to reproduce getting an empty `.jpeg` but neither was I able to view the file using Ubuntu's Image Viewer app. I managed to view the graph by saving it as `.svg` and opening it in Firefox. PR https://github.com/kframework/kore/pull/1410 should allow the user to input different formats for saving the graph and changes the default to be `.svg`.
