### ISSUE TITLE
Unsuccessful removal of variable in `owise` rule application on concrete KEVM tests

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#1407]
On KEVM `master`, if you run:

```
git clone 'https://github.com/kframework/evm-semantics'
cd evm-semantics
git submodule update --init --recursive
make deps -B RELEASE=true
make build-haskell -j8
make test-vm TEST_CONCRETE_BACKEND=haskell
```

the tests there pass, but generate a bunch of warnings which don't make much sense:

```
[2020-01-08 14:26:13.577821392][Warning] : [LogMessage] : Failed to decide predicate:                           
    \not{SortGeneratedTopCell{}}(                                                    
        \equals{SortString{}, SortGeneratedTopCell{}}(                                                          
LblsubstrString'LParUndsCommUndsCommUndsRParUnds'STRING'Unds'String'Unds'String'Unds'Int'Unds'Int{}(
                Var'Unds'0:SortString{},                                             
                /* builtin: */ \dv{SortInt{}}("0"),
                /* builtin: */ \dv{SortInt{}}("2")                                                          
            ),                                    
            /* builtin: */ \dv{SortString{}}("0x")                                   
        )                                                                                                       
    ) []
```

Which makes it look like it's trying to decide `substrString(_:String, 0, 2) #Equals "0x"`.

This comes from the rules (from `serialization.md`):

```
    rule #parseWord("") => 0 
    rule #parseWord(S)  => #parseHexWord(S) requires lengthString(S) >=Int 2 andBool substrString(S, 0, 2) ==String "0x" 
    rule #parseWord(S)  => String2Int(S) [owise] 
```

Because it's using underbar variable `_:String` instead of variable `S:String`, we think it's coming from the `owise` rule, where it's not able to detect that the `owise` rule does/doesn't apply immediately.

Somehow this doesn't make much sense, because the test is concrete, so it should be able to definitively say which of the rules apply.

**Comment by ttuegel** [comment]
I remember discussing this with @yzhang90 and @xc93, but I don't think I ever created an issue for it.

When evaluating conditions, we should always evaluate logical predicates (such as `\in(_, _)` in the side-condition of an `owise` rule) before evaluating functions and sending the result to the solver. Evaluating logical connectives first allows for short-circuiting, which is essential in this case and others.

**Comment by ttuegel** [comment]
I am going to proceed with this by introducing a `Predicate` simplification pass which does no function evaluation. When we evaluate `requires` clauses, we will simplify once without function evaluation, then re-simplify the result with functions. I think I can solve [this TODO](https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Function/Evaluator.hs#L88) in passing.

**Comment by virgil-serbanuta** [comment]
You probably already thought about this, but, since I've debugged similar stuff recently (I'll file an issue): you should make sure that we don't mark subterms simplified without function evaluation as fully simplified, otherwise the resimplification step will not do anything.
