### ISSUE TITLE
Missing test coverage

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#141]
Jenkins produces a [coverage report](https://office.runtimeverification.com/jenkins/job/kore-pull-request/Coverage_20Report/) for each pull request. Unfortunately, Jenkins also mangles the marked-up source output, so if you need to work on one of these modules you will need to make your own coverage report. The most useful metric is expression coverage. (Top-level definition coverage is artificially lowered by missing coverage from derived instances, which are not useful to cover.)

### Problem modules

You are tagged next to a module if I determined that you are the original author or maintainer of a module.

- [Data.Kore.AST.Common](https://github.com/kframework/kore/tree/master/src/main/haskell/language-kore/src/Data/Kore/AST/Common.hs) (68% | 195/283) @traiansf 
- [Data.Kore.Building.Patterns](https://github.com/kframework/kore/tree/master/src/main/haskell/language-kore/src/Data/Kore/Building/Patterns.hs) (62% | 149/239) @virgil-serbanuta 
- [Data.Kore.Step.Function.Evaluator](https://github.com/kframework/kore/tree/master/src/main/haskell/language-kore/src/Data/Kore/Step/Function/Evaluator.hs) (58% | 145/248) @virgil-serbanuta 
- [Data.Kore.HaskellExtensions](https://github.com/kframework/kore/tree/master/src/main/haskell/language-kore/src/Data/Kore/HaskellExtensions.hs) (57% | 11/19) @traiansf 
- [Kore.MatchingLogic.Signature.Simple](https://github.com/kframework/kore/tree/master/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Simple.hs) (55% | 62/111) @bmmoore 
- [Data.Kore.AST.AstWithLocation](https://github.com/kframework/kore/tree/master/src/main/haskell/language-kore/src/Data/Kore/AST/AstWithLocation.hs) (50% | 52/102) @virgil-serbanuta 
- [Data.Kore.Building.Sorts](https://github.com/kframework/kore/tree/master/src/main/haskell/language-kore/src/Data/Kore/Building/Sorts.hs) (50% | 12/24) @virgil-serbanuta 
- [Data.Kore.Implicit.Verified](https://github.com/kframework/kore/tree/master/src/main/haskell/language-kore/src/Data/Kore/Implicit/Verified.hs) (50% | 20/40) @virgil-serbanuta 
- [Data.Kore.Parser.Parser](https://github.com/kframework/kore/tree/master/src/main/haskell/language-kore/src/Data/Kore/Parser/Parser.hs) (50% | 7/14) @virgil-serbanuta 
- [Kore.MatchingLogic.HilbertProof](https://github.com/kframework/kore/tree/master/src/main/haskell/matching-logic/src/Kore/MatchingLogic/HilbertProof.hs) (50% | 77/154) @bmmoore 
- [Data.Kore.AST.BuildersImpl](https://github.com/kframework/kore/tree/master/src/main/haskell/language-kore/src/Data/Kore/AST/BuildersImpl.hs) (48% | 123/255) @virgil-serbanuta 
- [Kore.MatchingLogic.ProofSystem.MLProofSystem](https://github.com/kframework/kore/tree/master/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs) (47% | 550/1151) @bmmoore 
- [Data.Kore.AST.PureML](https://github.com/kframework/kore/tree/master/src/main/haskell/language-kore/src/Data/Kore/AST/PureML.hs) (46% | 61/132) @traiansf 
- [Data.Kore.Step.Condition.Condition](https://github.com/kframework/kore/tree/master/src/main/haskell/language-kore/src/Data/Kore/Step/Condition/Condition.hs) (33% | 42/125) @virgil-serbanuta 
- [Kore.MatchingLogic.Error](https://github.com/kframework/kore/tree/master/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Error.hs) (14% | 2/14) @virgil-serbanuta 
- [Kore.MatchingLogic.AST](https://github.com/kframework/kore/tree/master/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs) (0% | 0/414) @bmmoore 
- [Kore.MatchingLogic.AST.Syntax](https://github.com/kframework/kore/tree/master/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST/Syntax.hs) (0% | 0/206) @bmmoore 
- [Kore.MatchingLogic.ProofSystem.Minimal](https://github.com/kframework/kore/tree/master/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/Minimal.hs) (0% | 0/540) @bmmoore 

I will report on our progress at the next weekly iteration meeting.

**Comment by virgil-serbanuta** [comment]
I'd argue that a coverage of 50% for modules with only 14 lines of code might not be that bad, and it will not change the overall coverage, but I'll try to improve it regardless.

**Comment by ttuegel** [comment]
> I'd argue that a coverage of 50% for modules with only 14 lines of code might not be that bad, and it will not change the overall coverage, but I'll try to improve it regardless.

This was the take-away from my conversation with Brian. Enforcing 100% coverage absolutely is probably not a good idea because it encourages us to write many tests without thinking just to check the "test coverage" box. Instead, we should take a hard look at each piece of code and think about its failure modes. If adding tests to a particular piece of code is not high-value, then make a note of that and move on.

**Comment by ttuegel** [comment]
I am closing this issue; the resolution is that test coverage is an item on the review checklist now, and I will update the team on test coverage at the weekly meeting.
