### ISSUE TITLE
Unification of injected constructors

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1413]
There is a missing unification case for constructors injected from different sorts:

```
\inj{Sub1, Super}(Ctor1()) ∧ \inj{Sub2, Super}(Ctor2()) = \bottom
```

See also: #1269

**Comment by traiansf** [comment]
@ttuegel : it turns that you were right with this one, of course :-)

This condition is handled in the implementation of `unifyInj` ( https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Simplification/InjSimplifier.hs#L196 ).
```
      -- If the child patterns are simplifiable, then they could eventually be
      -- simplified to produce matching sort injections, but if they are
      -- non-simplifiable, then they will never match.
      | hasConstructorLikeTop (injChild inj1) = Left Distinct
      | hasConstructorLikeTop (injChild inj2) = Left Distinct
```

Hence, the PR I opened for this is not needed. I'll close it and move to the next issue.
