### ISSUE TITLE
Include the side condition when evaluating functions in the side condition

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1416]
kevm: https://github.com/kframework/evm-semantics/tree/investigate

```
make clean
make defn

kompile --debug --main-module ETHEREUM-SIMULATION --backend haskell --hook-namespaces KRYPTO --syntax-module ETHEREUM-SIMULATION .build/defn/haskell/driver.k --directory .build/defn/haskell -I .build/defn/haskell

kprove --haskell-backend-command "/home/zy/workspace/kore/.build/kore/bin/kore-repl --repl-script /home/zy/workspace/kore/dist/kast.kscript " ~/workspace/evm-semantics/tests/specs/erc20/ds/balanceOf-spec.k -d ~/workspace/evm-semantics/.build/defn/haskell/ --def-module VERIFICATION
```
print the configuration at step 0 yields a very complicated predicate like:
```
  ( #Not ( {
        0 <=Int OWNER andBool OWNER <=Int 115792089237316195423570985008687907853269984665640564039457584007913129639935
      #Equals
        true
      } )
    #And
      {
        #lookup ( M , keccak ( #buf ( 32 , OWNER ) +Bytes b"0000000000000000000000000000000000000000000000000000000000000001" ) )
      #Equals
        #lookup ( M , keccak ( intList2ByteArray ( OWNER  1  .IntList ) ) )
      }
  #Implies
    {
      true
    #Equals
      0 <=Int ACCT_ID andBool ACCT_ID <=Int 1461501637330902918203684832716283019655932542975 andBool ( 0 <=Int CALLER_ID andBool CALLER_ID <=Int 1461501637330902918203684832716283019655932542975 ) andBool ( 0 <=Int ORIGIN_ID andBool ORIGIN_ID <=Int 1461501637330902918203684832716283019655932542975 ) andBool ( 0 <=Int CALL_DEPTH andBool CALL_DEPTH <Int 1024 ) andBool ( 0 <=Int OWNER andBool OWNER <=Int 1461501637330902918203684832716283019655932542975 ) andBool ( 0 <=Int #lookup ( M , keccak ( intList2ByteArray ( OWNER  1  .IntList ) ) ) andBool #lookup ( M , keccak ( intList2ByteArray ( OWNER  1  .IntList ) ) ) <=Int 115792089237316195423570985008687907853269984665640564039457584007913129639935 ) andBool #isIntegerMap ( M )
    } )
#And
  ( {
      0 <=Int OWNER andBool OWNER <=Int 115792089237316195423570985008687907853269984665640564039457584007913129639935
    #Equals
      true
    }
  #Implies
    {
      true
    #Equals
      0 <=Int ACCT_ID andBool ACCT_ID <=Int 1461501637330902918203684832716283019655932542975 andBool ( 0 <=Int CALLER_ID andBool CALLER_ID <=Int 1461501637330902918203684832716283019655932542975 ) andBool ( 0 <=Int ORIGIN_ID andBool ORIGIN_ID <=Int 1461501637330902918203684832716283019655932542975 ) andBool ( 0 <=Int CALL_DEPTH andBool CALL_DEPTH <Int 1024 ) andBool ( 0 <=Int OWNER andBool OWNER <=Int 1461501637330902918203684832716283019655932542975 ) andBool ( 0 <=Int #lookup ( M , keccak ( #buf ( 32 , OWNER ) +Bytes b"0000000000000000000000000000000000000000000000000000000000000001" ) ) andBool #lookup ( M , keccak ( #buf ( 32 , OWNER ) +Bytes b"0000000000000000000000000000000000000000000000000000000000000001" ) ) <=Int 115792089237316195423570985008687907853269984665640564039457584007913129639935 ) andBool #isIntegerMap ( M )
    } )
#And
  #Ceil ( SetItem ( ACCT_ID:Int )
  _34 )
#And
  #Not ( #Not ( {
      0 <=Int OWNER andBool OWNER <=Int 115792089237316195423570985008687907853269984665640564039457584007913129639935
    #Equals
      true
    } )
  #And
    #Not ( {
      #lookup ( M , keccak ( #buf ( 32 , OWNER ) +Bytes b"0000000000000000000000000000000000000000000000000000000000000001" ) )
    #Equals
      #lookup ( M , keccak ( intList2ByteArray ( OWNER  1  .IntList ) ) )
    } ) )
```

As @virgil-serbanuta pointed out, it may be caused by evaluating
```
andBool BAL ==Int #lookup(M, #hashedLocation("Solidity", 1, OWNER))
``` 
in the top level predicate of the spec. When evaluating `#hashedLocation`, it needs to apply the rule
```
    syntax ByteArray ::= intList2ByteArray( IntList ) [function, functional]
 // ------------------------------------------------------------------------
    rule intList2ByteArray(.IntList) => .ByteArray
    rule intList2ByteArray(V VS)     => #buf(32, V) ++ intList2ByteArray(VS)
      requires #rangeUInt(256, V)
```
And applying the rule requires using the following condition in the top level predicate:
```
andBool #rangeAddress(OWNER)
```

However, when evaluating the functions in top level predicate, we don't pass in side conditions.

**Comment by ttuegel** [comment]
@virgil-serbanuta Do you think this can be solved by iterating the simplifier over the top-level predicate?

**Comment by virgil-serbanuta** [comment]
I think we need https://github.com/kframework/kore/blob/master/design-decisions/2020-01-02-Side-conditions-for-predicates.md , either by itself, or with reevaluation.

**Comment by virgil-serbanuta** [comment]
Actually, I'm not fully sure, that predicate is a bit weird... but, from @yzhang90's comment, we probably need that design decision.

**Comment by ttuegel** [comment]
In a meeting today, we (myself, @traiansf, @virgil-serbanuta, and @mcalancea) decided on a design to evaluate functions in the top-level condition using conditions at the top-level.

The top-level condition is a conjunction of predicates:

```
P_top = P₁ ∧ P₂ ∧ ...
```

The simplifier will collect `Pᵢ` and simplify each individually, using the other conjoined terms (`Pⱼ, j ≠ i`) as the `SideCondition`. When a conjoined term is already simplified (`j < i`) it will use the simplified form (but see below). The simplifier will iterate this procedure until `P_top` stabilizes or until it reaches the maximum iteration threshold. The maximum number of iterations will be 4, and we expect that most `P_top` will be fully-simplified after the first pass. If the maximum iteration threshold is reached, the backend will emit a warning, but continue execution.

An alternative to using the simplified form of `Pⱼ` to simplify `Pᵢ`:

It is equally valid to use the un-simplified `Pⱼ` to simplify `Pᵢ`. At worst, this is a constant-factor slower because it may take one more iteration to stabilize. In the typical case, there will be no difference between implementations. However, this implementation would be significantly simpler, because there is no need to track separately the predicates that have or have not been simplified: just a `traverse` of the conjoined predicate. (Using a zipper-like structure to distinguish each `Pᵢ` from the other `Pⱼ`.) I think we should do this until we find a compelling performance reason to do otherwise.

**Comment by virgil-serbanuta** [comment]
It's not trivial to use the unsimplified predicates, because the simplification process may "lose constraints" in the predicate being simplified.

As an example, if we have two predicates that are equivalent, `P1` and `P2` (e.g. `a==b` and `b==a`), and we try to simplify `P1 and P2`, we would get `top` because `P1` implies `P2` and `P2` implies `P1`.

For the given example:

We simplify `a==b` with `b==a` as a side condition. `b==a` implies `a==b`, so we simplify it to `top`.

Then we simplify `b==a` using `a==b` as a side condition, and we get, again, top.

**Comment by denis-bogdanas** [comment]
@ttuegel Is the side condition used when evaluating function terms in configuration? I have an example where it looks not be the case.

**Comment by ttuegel** [comment]
> Is the side condition used when evaluating function terms in configuration?

Yes, the side condition is used to evaluate function terms in the configuration.

**Comment by denis-bogdanas** [comment]
> 
> 
> It's not trivial to use the unsimplified predicates, because the simplification process may "lose constraints" in the predicate being simplified.
> 
> As an example, if we have two predicates that are equivalent, `P1` and `P2` (e.g. `a==b` and `b==a`), and we try to simplify `P1 and P2`, we would get `top` because `P1` implies `P2` and `P2` implies `P1`.
> 
> For the given example:
> 
> We simplify `a==b` with `b==a` as a side condition. `b==a` implies `a==b`, so we simplify it to `top`.
> 
> Then we simplify `b==a` using `a==b` as a side condition, and we get, again, top.

In this case, when you simplify the 2nd equality, you should no longer use the first equality `a==b`, but the simplification result top. Then 2nd equality will no longer be simplified and no information loss would occur.

**Comment by virgil-serbanuta** [comment]
@denis-bogdanas You're right when referring to the main algorithm, but note that @ttuegel also mentioned an alternative, in which we'd still use `a==b` instead of `top`.

**Comment by denis-bogdanas** [comment]
@ttuegel Looks like ERC20 verifier depends on this issue. Too many workarounds to avoid it.

**Comment by ttuegel** [comment]
@denis-bogdanas Can you provide an example? So far, we haven't seen a case in practice that depends on it.

**Comment by denis-bogdanas** [comment]
@ttuegel Turns out the issue is different but is hard to isolate. And is really blocking this time. I'll open it later today. But it would be good to fix present issue to rule out this possibility in case problems appear in future.

**Comment by denis-bogdanas** [comment]
@ttuegel I believe this is the missing feature after all.
Here is the MWE equivalent to the issue I'm having in ERC20 verifier: https://github.com/kframework/k/pull/1339

It passes in Java backend.

**Comment by ttuegel** [comment]
@denis-bogdanas This looks to me like something that must be sent to Z3. Can you explain, what side condition you think the backend should evaluate internally?

**Comment by denis-bogdanas** [comment]
@ttuegel The 2 rules for `step` will create 3 branches: 2 for each rule + reminder. To eliminate the reminder you have to evaluate the side condition `notBool I <Int 1 andBool notBool I ==Int 1` using lemma that is effectively `I <Int 2`. One term of the side condition in the context of the lemma and the other term to result in false. So I supposed it relates to this bug.

If you believe my report is a separate bug, please open another issue. Note that it is blocking for ERC20 verifier.

**Comment by ttuegel** [comment]
> To eliminate the reminder you have to evaluate the side condition `notBool I <Int 1 andBool notBool I ==Int 1` using lemma that is effectively `I <Int 2`. One term of the side condition evaluated in the context of the lemma and the other term results in `false`.

There is no rule in that specification which applies to either of those terms. That side condition must go to Z3. I will open another issue for that.
