### ISSUE TITLE
Support for ? variables

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#1428]
I have three use-cases I need support for `?` variables for:

-   Fresh integer variable which is unconstrained:

    ```
    syntax Int ::= freshInt ( ) [kinda-function-like]
    rule freshInt() => ?X:Int
    ```

-   Fresh integer variable which is constrained (but has semantics that it takes on a _single_ value in the constrained region, and the constrained region is determined at runtime):

    ```
    syntax Int ::= freshBoundedInt ( Int , Int ) [kinda-function-like]
    rule freshBoundedInt(L, U) => ?X ensures L <=Int ?X andBool ?X <Int U
    ```

-   Arbitrary choice from a list (semantics that it takes on a _single_ undetermined value from the list, and the list is determined at runtime):

    ```
    syntax String ::= choice ( List ) [kinda-function-like]
    rule choice(LS) => ?S:String ensures ?S in LS
    ```

    The sort inference here might be a bit weird, might need to add a cast somewhere.

**Comment by ehildenb** [comment]
In particular, these come from the MKR semantics, where I have to disable `?` variables to update to newest Haskell backend: https://github.com/makerdao/mkr-mcd-spec/pull/137/files

**Comment by ttuegel** [comment]
Closing after some conversation because this is not needed for MKR.
