### ISSUE TITLE
Missing matching-logic documentation

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#143]
These modules and declarations are missing API documentation. I have tagged module maintainers or authors as I found them. Please update your documentation and/or decide if modules and declarations should be exported.

### Kore.MatchingLogic.Error
@virgil-serbanuta 

- [mlFailWhen](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Error.hs#L27)
- [mlFail](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Error.hs#L31)

### Kore.MatchingLogic.HilbertProof
@bmmoore 

- [Proof](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/HilbertProof.hs#L34)
- [ProofSystem](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/HilbertProof.hs#L69)
- [emptyProof](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/HilbertProof.hs#L42)
- [add](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/HilbertProof.hs#L45)
- [derive](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/HilbertProof.hs#L77)
- [renderProof](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/HilbertProof.hs#L60)

### Kore.MatchingLogic.ProofSystem.Dummy
@bmmoore 

- [DummyError](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/Dummy.hs#L26)

### Kore.MatchingLogic.ProverRepl
@bmmoore 

- [ProverState](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProverRepl.hs#L24)
- [Command](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProverRepl.hs#L27)
- [applyCommand](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProverRepl.hs#L32)
- [Parser](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProverRepl.hs#L41)
- [parseCommand](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProverRepl.hs#L43)
- [_](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProverRepl.hs#L53)
- [runProver](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProverRepl.hs#L57)

### Kore.MatchingLogic.Signature
@bmmoore 

- [IsSignature](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature.hs#L12)
- [CheckableSignature](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature.hs#L23)

### Kore.MatchingLogic.AST
@bmmoore 

- [visitPatternF](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L90)
- [IsSignature](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature.hs#L12)
- [fromWFPattern](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L124)
- [ToPattern](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L170)
- [FromPattern](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L172)
- [notFree](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L175)
- [VariableP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L197)
- [ApplicationP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L200)
- [AndP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L203)
- [NotP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L206)
- [ExistsP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L209)
- [variableP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L212)
- [applicationP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L214)
- [andP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L216)
- [notP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L218)
- [existsP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L220)
- [OrP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L223)
- [ImpliesP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L231)
- [IffP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L236)
- [ForallP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L242)
- [orP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L228)
- [impliesP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L233)
- [iffP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L239)
- [forallP](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L246)
- [andP'](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L277)
- [notP'](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L284)
- [orP'](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L277)
- [impliesP'](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L277)
- [iffP'](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L277)
- [forallP'](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L288)
- [existsP'](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs#L292)

### Kore.MatchingLogic.ProofSystem.Minimal
@bmmoore 

- [SubstitutedVariable](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/Minimal.hs#L20)
- [SubstitutingVariable](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/Minimal.hs#L22)
- [transformRule](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/Minimal.hs#L56)
- [dummyFormulaVerifier](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/Minimal.hs#L95)
- [substVar](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/Minimal.hs#L99)

### Kore.MatchingLogic.ProofSystem.MLProofSystem
@bmmoore 

- Module header
- [Var](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L39)
- [Symbol](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L40)
- [formulaVerifier](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L43)
- [_](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L61)
- [checkPropositional1Derivation](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L96)
- [checkPropositional2Derivation](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L129)
- [checkPropositional3Derivation](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L199)
- [checkModusPonensDerivation](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L246)
- [_](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L280)
- [MetaPatternSubstitution](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L284)
- [_](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L287)
- [checkVariableSubstitution](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L295)
- [checkForall](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L348)
- [checkGeneralizationDerivation](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L414)
- [checkPropagateOr](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L443)
- [checkPropagateExists](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L555)
- [checkFraming](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L660)
- [checkExistence](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L743)
- [SingvarPhi](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L771)
- [checkSingvar](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L773)
- [checkSingvarContext](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L816)
- [testExtraPatternsEquality](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L901)
- [testFormulaEquality](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/MLProofSystem.hs#L918)

### Kore.MatchingLogic.Signature.Poly
@bmmoore 

- [ValidatedSignature](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Poly.hs#L57)
- [fromValidated](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Poly.hs#L58)
- [validate](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Poly.hs#L77)
- [PolySignature](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Poly.hs#L62)
- [ReifiesSignature](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Poly.hs#L108)
- [resolveLabel](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature.hs#L26)
- [resolveSort](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature.hs#L27)
- [reifySignature](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Poly.hs#L161)
- [prettyPolyTerm](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Poly.hs#L90)

### Kore.MatchingLogic.Signature.Simple
@bmmoore 

- [fromValidated](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Simple.hs#L52)
- [validate](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Simple.hs#L62)
- [SimpleSignature](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Simple.hs#L55)
- [ReifiesSignature](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Simple.hs#L65)
- [resolveLabel](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature.hs#L26)
- [resolveSort](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature.hs#L27)
- [reifySignature](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/Signature/Simple.hs#L67)

### Kore.MatchingLogic.AST.Syntax
@bmmoore 

- [mlPattern](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST/Syntax.hs#L48)
- [prettyPat](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST/Syntax.hs#L100)
- [simpleSigPattern](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST/Syntax.hs#L72)
- [simpleSigLabel](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST/Syntax.hs#L84)
- [simpleSigSort](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST/Syntax.hs#L92)

### Kore.MatchingLogic.ProofSystem.Minimal.Syntax
@bmmoore 

- [parseId](http://github.com/kframework/kore/blob/55f89f0e5fb51fcecefe80476b7f1a954248e799/src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/Minimal/Syntax.hs#L46)

**Comment by bmmoore** [comment]
This issue is obsolete after merging the packages.
