### ISSUE TITLE
Quantifying anonymous variables?

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1460]
How does the frontend quantify anonymous variables on the right-hand side, if at all?

**Comment by traiansf** [comment]
Partial answer:  both `_` and `?_` turn out as universally quantified variables in the generated spec.

I'm still investigating what is happening with `?_` (I was actually surprised it is accepted by the parser)

**Comment by traiansf** [comment]
Ok, I found the culprit: https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/compile/ResolveAnonVar.java#L91

Here anonymous variables and "fresh anonymous variables" are flatten to "Dot" variables. Probably best thing would be to add a flag to Dot variables to signal they are of the `?` and to catch that when outputing KORE.
