### ISSUE TITLE
Hot-spot: Kore.Internal.SideCondition.fromCondition

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1472]
This function is a hot-spot due to its use of `unparseToText`.

**Comment by virgil-serbanuta** [comment]
Interesting. This was supposed to be used rarely...

**Comment by ttuegel** [comment]
I forgot to check how many times it is called, and I don't think I have the profile report around anymore. It accounts for about 9% of allocation and 5% of time. That's not huge, but it's big enough to be one of the biggest single cost centers.
