### ISSUE TITLE
Rule application failed

### ISSUE THREAD

**Issue by daejunpark** [kframework/kore#1511]
The following rule failed to be applied:
```
rule lookup(A, foo(A) |-> V:Val _:Map) => bar(V)
```
where `bar` requires its input to be of sort `Val`.

But the following equivalent but ugly ones succeeded to be applied:
```
rule lookup(A, M) => lookupAux(M[foo(A)])
rule lookupAux(V:Val) => bar(V)
```

----

A minimal example.

Given a definition:
```
$ cat b.k
module B

imports INT
imports MAP

configuration <T>
  <k> $PGM:Cmd </k>
</T>

syntax Int ::= lookup(Key, Map) [function]
rule lookup(A, foo(A) |-> V:Val _:Map) => bar(V)

syntax Int ::= foo(Key) [function]
syntax Int ::= bar(Val) [function]

syntax Key ::= "kk"
syntax Val ::= "vv"

rule foo(kk) => 1
rule bar(vv) => 2

syntax Cmd ::= "run"
rule run => lookup(kk, 1 |-> vv .Map)

endmodule
```

It failed to apply the lookup rule:
```
$ cat 1.b
run

$ kompile --backend haskell b.k

$ krun 1.b
<T>
  <k>
    lookup ( kk , 1 |-> vv )
  </k>
</T>
```

But if we replace the original lookup rule:
```
rule lookup(A, foo(A) |-> V:Val _:Map) => bar(V)
```
with the following equivalent but ugly ones:
```
rule lookup(A, M) => lookupAux(M[foo(A)])
syntax Int ::= lookupAux(K) [function]
rule lookupAux(V:Val) => bar(V)
```
then, it succeeded:
```
$ krun 1.b
<T>
  <k>
    2
  </k>
</T>
```

**Comment by ttuegel** [comment]
Functions are not evaluated during matching, so when applying the rule

```
rule lookup(A, foo(A) |-> V:Val _:Map) => bar(V)
```

although the backend would generate a substitution for `A`, and apply that substitution to subterm `foo(A)`, it would not evaluate `foo` in order to get the Map key. This is an intentional limitation; equation rules, including function rules, are applied by syntactic matching only.

**Comment by daejunpark** [comment]
You're right. My bad.
