### ISSUE TITLE
The Haskell backend takes too much time for HKG lemmas

### ISSUE THREAD

**Issue by virgil-serbanuta** [kframework/kore#1520]
Reproduce with:
0. Go to the evm-semantics repository
1. Patch https://github.com/kframework/evm-semantics/pull/724
2.
```
git submodule update --init --recursive
make deps
make build-haskell
```
3. deps/k/k-distribution/target/release/k/bin/kprove --haskell-backend-command "~/runtime-verification/kore/.build/kore/bin/kore-exec " --directory ./.build/defn/haskell -v --debug '' tests/specs/erc20/hkg/totalSupply-spec.k --def-module VERIFICATION

**Comment by yzhang90** [comment]
you can consider taking some lemmas from https://github.com/kframework/evm-semantics/blob/1ab0001124e6317a2adc2a8e59c748fcbdf0150d/tests/specs/erc20/verification.k#L16

**Comment by virgil-serbanuta** [comment]
FWIW: the backend finishes this in 485 steps, with a speed of ~11 sec/step.

**Comment by virgil-serbanuta** [comment]
Current guess: we don't cache the result of `computeValidJumpDests`

**Comment by yzhang90** [comment]
I added the `memo` attribute to `#computeValidJumpDests` for now (and https://github.com/kframework/kore/issues/1522 should be fixed) and the proof finishes in ~2m30s on my desktop. 

During the proof, I got two warnings:
```
kore-exec: [2020-02-06 20:57:54.711656538] Warning (WarnBottomHook): Evaluating 'BYTES.get' in pattern:
    /* Fn Spa */
    Lbl'UndsLSqBUndsRSqBUnds'BYTES-HOOKED'Unds'Int'Unds'Bytes'Unds'Int{}(
        /* Fl Fn D Sfa Cl */ \dv{SortBytes{}}(""),
        /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
    )
has resulted in \bottom.
kore-exec: [2020-02-06 20:59:12.235077019] Warning (WarnBottomHook): Evaluating 'BYTES.get' in pattern:
    /* Fn Spa */
    Lbl'UndsLSqBUndsRSqBUnds'BYTES-HOOKED'Unds'Int'Unds'Bytes'Unds'Int{}(
        /* Fl Fn D Sfa Cl */ \dv{SortBytes{}}(""),
        /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
    )
has resulted in \bottom.
```
Have you got the same issues?

**Comment by virgil-serbanuta** [comment]
I think I saw something like that in the output, I'm not fully sure since I was paying attention to other things.

**Comment by virgil-serbanuta** [comment]
Blocked by https://github.com/kframework/kore/issues/1522
