### ISSUE TITLE
Attributes to replace #isConcrete

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1557]
The `#isConcrete` symbol is unsound in Kore. We will replace it everywhere with axiom attributes because it is sound for the backend to use attributes as hints when a rule should or should not be applied.

- `concrete(X, Y, Z, ...)`: the rule will apply only if variables `X`, `Y`, `Z`, etc. are instantiated at constructor-like patterns. The named variables must appear free in the rule; this will be checked in the frontend.
- `concrete()` or `concrete`: the existing behavior becomes a special case of the above; the rule will apply only if all variables are instantiated at constructor-like patterns.
- `concrete(X), concrete(Y)` will be equivalent to `concrete(X, Y)`.
- The opposite attribute `symbolic(X, Y, Z, ...)` will also be defined.
- It is an error if the same variable is mentioned in a `concrete` and `symbolic` attribute.

#### Plan

The backend will receive variable names as strings, so some refactoring will be required to properly verify axiom sentence attributes.

Each of the listed steps should be workable as a pull request in its own right.

- [x] Remove the [`ParseAttributes`](https://github.com/kframework/kore/blob/master/kore/src/Kore/Attribute/Axiom.hs#L165) instance of `Kore.Attribute.Axiom.Axiom`. Lift the definition of `parseAttributes` to the top-level of that module as `parseAxiomAttributes`. Fix compilation errors by replacing `parseAttributes @Axiom` with `parseAxiomAttributes`.
- [x] Remove the [`ParseAttributes`](https://github.com/kframework/kore/blob/master/kore/src/Kore/Attribute/Axiom/Concrete.hs#L56) instance of `Kore.Attribute.Axiom.Concrete.Concrete`. Lift the definition of `parseAttributes` to the top-level of that module as `parseConcreteAttribute`. Fix compilation errors by replacing `parseAttributes @Concrete` with `parseConcreteAttribute`.
- [x] Give `Concrete` a phantom `variable` type parameter, and do the same for `Axiom`. Fix compilation errors.
- [x] Change the [representation](https://github.com/kframework/kore/blob/master/kore/src/Kore/Attribute/Axiom/Concrete.hs#L24) of `Concrete` to hold `FreeVariables variable` instead of being a `Bool` attribute. Give `parseConcreteAttribute` a new `FreeVariables` argument, which is the set of free variables in the axiom. Do not worry about the variable names yet. Continue to use `parseBoolAttribute` in `parseConcreteAttribute`; if the `Bool` is `True`, then _all_ the free variables are taken as `Concrete`, otherwise _none_ of the free variables are taken. Change the `From` instance so that it acts on `Set.null`. Fix compilation errors.
- [x] Change `parseConcreteAttribute` to filter its `FreeVariables` argument based on the variable names given as arguments to the `concrete` symbol. Change [`concreteAttribute`](https://github.com/kframework/kore/blob/master/kore/src/Kore/Attribute/Axiom/Concrete.hs#L53) to take a list of variables as an argument, and include them in the result. Also change the `From` instance to include the variable names as arguments. Add unit tests covering cases when only some of the variables are concrete.
- [x] Make a `Symbolic` attribute which looks like `Concrete` syntactically, but with the opposite behavior in the function evaluator.
- [x] Change the equation evaluation check to run after matching the left-hand side, and only require the specified variables to be concrete or symbolic.
- [x] Also check validity of the attributes in the frontend.

**Comment by yzhang90** [comment]
The proposal looks good to me!

**Comment by virgil-serbanuta** [comment]
Looks good to me! Would the people writing semantics prefer `notConcrete` instead of `symbolic`?

**Comment by grosu** [comment]
I think `notConcrete` is more intuitive than `symbolic`, indeed.

**Comment by daejunpark** [comment]
Looks good to me.  I prefer `symbolic`.

**Comment by ttuegel** [comment]
I realize now that we are going to need the frontend to apply the same transformation to the arguments of `concrete()` and `symbolic()` as it does to variables occurring in the rule. @traiansf Can you point me in the right direction?
