### ISSUE TITLE
Simplify sub-predicates that are implied by top-level ones.

### ISSUE THREAD

**Issue by virgil-serbanuta** [kframework/kore#1573]
If we have two predicates `P` and `Q` and `P` occurs inside of `Q`, e.g. `P` is `x==1` and `Q` is `\iff(x == 1, y == 2)` then, when simplifying `P and Q` we can first reduce it to `P and \iff(top, y == 2)`, which we can re-simplify to `P and y == 2`.

But we can do better than this. We can replace all predicates which are implied by `P` with `top`. As an example, if `P` is `x > 1` and `Q` is `\iff(x > 2, y == 3)` then, if we can figure out that `x>1` implies `x>2` then we could reduce `P and Q` to `P and \iff(top, y == 3)` and we can simplify that to `P and y == 3`.

However, checking implications (including the above) usually requires us to call the SMT solver. So, we should do this only in certain special cases. In the initial version, those special cases should include only things that are equal to `P`, but map/set ceils are good candidates in the future.

Of course, we should generalize this to any number of predicates `P1 and P2 and ...`. To do that, the simple solution is to sort them by length, then replace `Pi` in `Pi+1`, `Pi+2`, ... , `Pn`. It would probably be a good idea to cache the fingerprints of all predicate subterms of all `Pi`, then checking whether we need to bother to replace `Pi` in `Pj` would be logarithmic. In general this would be `O(n^2 log ?)`, but we can probably do better: We would create a map `subterm-fingerprint --> list(j))`, then for each Pi we would easily get all the relevant indexes j.

(Sorry if you would have liked to figure this out and I ruined it for you).

We should be careful when quantifiers are used.

After this, if we changed anything, we should resimplify the pattern.

This should probably replace `applyAndIdempotenceAndFindContradictions`:
https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Simplification/And.hs#L219

**Comment by ttuegel** [comment]
If we sort and substitute in reverse topological order, then this also gives us (the beginnings of) a framework for solving sequences of implications, such as simplifying `A ∧ A → B ∧ B → C` to `A ∧ C`.

**Comment by virgil-serbanuta** [comment]
The above should solve `A ∧ A → B ∧ B → C` by itself, though there's a difference from what you expected:
```
A ∧ A → B ∧ B → C
split and sort:       A, A → B, B → C
replace with top:  A, top → B, B → C
merge:                 A ∧ top → B ∧ B → C
simplify:               A ∧ B ∧ B → C
(it's probably a good idea to simplify directly, without merging)
split and sort:       A, B, B → C
replace with top:  A, B, top → C
merge:                 A ∧ B ∧ top → C
simplify:               A ∧ B ∧ C
```
In principle, since `A->B`, we should be able to also remove `B`, but, unless we know that the SMT is able to infer `B` form `A` by itself, it's probably a good idea to keep it.
