### ISSUE TITLE
Beacon Chain: a-spec.k

### ISSUE THREAD

**Issue by daejunpark** [kframework/kore#1576]
Here is [a spec](https://github.com/runtimeverification/beacon-chain-verification/blob/b3e37680555ddd4f92210458dee645e4a66d03f1/dynamic/a-spec.k) that kprove failed to prove, and here is [the failure output](https://github.com/runtimeverification/beacon-chain-verification/blob/b3e37680555ddd4f92210458dee645e4a66d03f1/dynamic/a-spec.k.out).

~It [got stuck](https://github.com/runtimeverification/beacon-chain-verification/blob/b3e37680555ddd4f92210458dee645e4a66d03f1/dynamic/a-spec.k.out#L741) in the middle, failing to apply the [`justify()` rule](https://github.com/runtimeverification/beacon-chain-verification/blob/b3e37680555ddd4f92210458dee645e4a66d03f1/dynamic/dynamic-abstract-beacon-chain.md#justification).~

To reproduce:
```
$ git clone git@github.com:runtimeverification/beacon-chain-verification.git
$ git checkout 62080be956a58f0af621abce31053c28e2c8b1eb
$ cd dynamic
$ make deps
$ make build
$ kprove -d .build/defn/static -m VERIFICATION a-spec.k
```

**Comment by ttuegel** [comment]
Fixed by #1583.
