### ISSUE TITLE
Use ceil implication for maps

### ISSUE THREAD

**Issue by virgil-serbanuta** [kframework/kore#1578]
Needs: https://github.com/kframework/kore/issues/1573
Has some overlap with https://github.com/kframework/kore/issues/1574 , so we may want to solve only one of these (see the trade-offs below).

Basically, we should be able to figure out that, say, `ceil(concat(a->??, b->??, c->??, m))` implies any of `ceil(concat(a->??, b->??, c->??))`, `ceil(concat(a->??, b->??, m))`, `ceil(concat(c->??, m))` and so on and remove those when possible, as described in https://github.com/kframework/kore/issues/1573

Tradeoffs:
Either https://github.com/kframework/kore/issues/1574 or this issue should solve the issues we are having right now (https://github.com/kframework/kore/issues/1576). They do not fully overlap because using only https://github.com/kframework/kore/issues/1576 would produce large terms which we would repeatedly process and send to the SMT, while using only the solution proposed in this issue would not work when
* the predicate is more complex than `and(ceil(...), phi(ceil(...)))`, e.g. something like `and(phi(ceil(...)), psi(ceil(...)))`.
* the maps have some overlap, but no inclusion relation, e.g. the following should be bottom, but we wouldn't be able to figure that out using only `ceil` implications.
```
and(
  ceil(concat(a, b, m)),
  not(ceil(concat(a, c, m)))
)
```

**Comment by ttuegel** [comment]
We should probably add axioms to `domains.k` to relate `#Ceil` to `in_keys`. However, this requires better matching on `Map` and `Set`. It also does not solve the entire problem, because the frontend generates Map sorts for cell collections that are not `Map`s.

**Comment by ttuegel** [comment]
Actually, I think this is not hard to support after all. We can add an internal representation like this:

```.hs
data MemberMap = { key :: TermLike, map :: BuiltinMap }
```

which is unparsed as

```
\forall(X, \ceil(concat(element(key, X), map)))
```

We will simplify any pattern that matches `\ceil(concat(element(key, X), map))` into the internal form. With my changes in #1583, and the changes by @virgil-serbanuta in #1584, that will automatically solve `Map` implication problems!

**Comment by virgil-serbanuta** [comment]
We could also make `Kore.Builtin.AssocComm.CeilSimplifier` output predicates based on `equals(in_keys(...), true)` instead of `ceil(concat())`. If `Set`s do not have `in_keys` then we may need to handle things a bit differently for maps and sets, but it should work.

**Comment by ttuegel** [comment]
> If `Set`s do not have `in_keys` then we may need to handle things a bit differently for maps and sets, but it should work.

`Set` has `in`, but cell collections based on `Map` and `Set` do not have either.

**Comment by ttuegel** [comment]
Upon further reflection, I think we can apply this generalization, instead of introducing an internal representation:

```
\ceil( K |-> V  M) = \ceil(K) \ceil(V) \ceil(M) \forall(x, \ceil(K |-> x  M))
```

The only complication I can see is that we may need to start lowering `\forall` over conjunctions of predicates to handle the case where we subsequently generate a substitution for `M`.
