### ISSUE TITLE
LOG: print Info when a strategy step starts

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1581]
In the log, I can only see `DebugProofState` when a strategy step finishes. However, there is no log entry gets printed when a strategy step starts.

**Comment by ttuegel** [comment]
@andreiburdusa For every case of [transitionRuleWorker](https://github.com/kframework/kore/blob/master/kore/src/Kore/Strategies/Goal.hs#L645) that has a `Profile.timeStrategy` step, there should also be a log entry. We will have a single sum type with a constructor for each strategy operation:

```.hs
data InfoReachability goal 
    = Simplify !goal
    | RemoveDestination !goal
    | DeriveSeq ![Rule goal] !goal
    | DerivePar ![Rule goal] !goal
```

When you have to define some instances like `Entry`, it's fine to use a concrete type for `goal`, for example, `instance Entry (InfoReachability (ReachabilityRule Variable))`.

For each constructor, define a wrapper like

```.hs
whileSimplify :: MonadLog log => Goal goal => goal -> log a -> log a
whileSimplify goal = logWhile (Simplify goal)
```

Use the corresponding wrapper whenever you see a call to `Profile.timeStrategy`.
