### ISSUE TITLE
LOG: improve the output for DeriveSeq

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1582]
The logging for `DeriveSeq`(or `DerivePar`) will print all the rules the prover has tried in kore format. It is very verbose to read.  It will be good enough to only print out the rule location in the .k file. What's more, we can also print out the successfully applied rule (location) as well

**Comment by ttuegel** [comment]
- [ ] The [`Pretty` instance](https://github.com/kframework/kore/blob/master/kore/src/Kore/Log/DebugAppliedRewriteRules.hs#L61) for `DebugAppliedRewriteRules` should print only the rule location

@yzhang90 Can you show me any example of what you mean by "The logging for DeriveSeq will print all the rules the prover has tried..."?
