### ISSUE TITLE
Delete `MiniToTextToMini.scala`

### ISSUE THREAD

**Issue by daejunpark** [kframework/kore#16]
The `assertequal` method is the only one used by others (`./kernel/src/main/java/org/kframework/kompile/KompileFrontEnd.java` in K),
which can be moved there.

**Comment by daejunpark** [comment]
@msaxena2 Could you help with this? The thing is that I have no good idea how to implement the Scala's structural equality (`==`) in Java. Or, we can simply put the structural equality operator between Definitions in some util file, and make K depend on it.

**Comment by grosu** [comment]
What's the status of this?  Can we close?

**Comment by daejunpark** [comment]
No, it is still there.

**Comment by cos** [comment]
I don't fully understand the problem, but Scala's `==` is an alias for the `equals` method in Java.

**Comment by cos** [comment]
deleted, we can recover the file from history if necessary.
