### ISSUE TITLE
PolyKinds shouldn't be on by default

### ISSUE THREAD

**Issue by bmmoore** [kframework/kore#163]
Apparently I was using the wrong extension, if KindSignatures suffices.
We have enough types with unused type parameters that we shouldn't turn on PolyKinds and silently change their meaning.

**Comment by ttuegel** [comment]
Actually, the GHC documentation is unclear about this. It seems that `PolyKinds` is required for polymorphism itself and not just inference. Unfortunately, there seems to be no way to have polymorphism and disable inference, so I'm not sure what we want to do.
