### ISSUE TITLE
Better map unification needed

### ISSUE THREAD

**Issue by daejunpark** [kframework/kore#1639]
A better map unification is needed especially for the Beacon chain verification.

Consider the following definition and its specs:

h.k:
```
module H

imports BOOL
imports INT
imports MAP

configuration <T> <k> $PGM:Cmd </k> <m> .Map </m> </T>

syntax Cmd ::= foo(Int)
rule <k> foo(X) => . ... </k>
     <m>
       .Map => (X |-> true)
     </m>

endmodule
```

h1-spec.k:
```
module H1-SPEC
imports H

rule <k> foo(X) => . </k>
     <m>
       .Map => (?Y |-> true)
     </m>
     requires X ==Int ?Y

endmodule
```

h2-spec.k:
```
module H2-SPEC
imports H

rule <k> foo(X +Int 1) => . </k>
     <m>
       .Map => (?Y |-> true)
     </m>
     requires X +Int 1 ==Int ?Y

endmodule
```

h3-spec.k:
```
module H3-SPEC
imports H

rule <k> foo(X) => . </k>
     <m>
       .Map => (?Y -Int 1 |-> true)
     </m>
     requires X ==Int ?Y -Int 1

endmodule
```

h4-spec.k:
```
module H4-SPEC
imports H

rule <k> foo(X +Int 1) => . </k>
     <m>
       .Map => (?Y -Int 1 |-> true)
     </m>
     requires X +Int 1 ==Int ?Y -Int 1

endmodule
```

The first two specs (h1-spec and h2-spec) are passed, but the last two (h3-spec and h4-spec) are failed.  I guess that the failure of h4-spec is due to the lack of a proper support for map unification.  But, the failure of h3-spec is quite surprising, because h2-spec and h3-spec are just dual, but only h2-spec is passed.

The Beacon chain verification requires the backend to be able to prove all the four specs.  Note that the equivalent expressions (e.g., `X +Int 1`, and `?Y -Int 1` in h4-spec) for the key are more complicated in the Beacon chain verification. For example, they are `X +Int N` and `(X /Int 32) *Int 32 + 31`,  or  `((X + 1) /Int 32) *Int 32 + 31` and `(X /Int 32) *Int 32 + 31`.

```
$ for i in h[1-4]-spec.k; do echo $i; kprove $i; done
h1-spec.k
#True

h2-spec.k
#True

h3-spec.k
<T>
  <k>
    .
  </k>
  <m>
    ?Y -Int 1 |-> true
  </m>
</T>

h4-spec.k
  <T>
    <k>
      .
    </k>
    <m>
      X +Int 1 |-> true
    </m>
  </T>
#And
  {
    X +Int 1
  #Equals
    ?Y -Int 1
  }
```

**Comment by ttuegel** [comment]
@virgil-serbanuta I thought these cases specifically would be supported. Do you know, off the top of your head, why not?

**Comment by virgil-serbanuta** [comment]
I don't know. the result for `h3-spec.k` is interesting because it contains `?Y` without it being related in any way to `X`, so, I guess, we should find out why we reach that state (we should probably not drop substitutions for symbolic variables). `h4-spec.k` should just work, though...
