### ISSUE TITLE
WarnSimplificationWithRemainder should be DebugSkipSimplification

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1642]
A simplification rule that does not apply due to the pre-condition being unmet is not a condition that requires a warning. This should be `Debug` severity, and I think the name and the text should reflect what the user cares about: that we are skipping a simplification rule.

**Comment by daejunpark** [comment]
Example.

i.k:
```
module I

imports INT

configuration <T> <k> $PGM:Cmd </k> <c> true </c> </T>

syntax Bool ::= foo(Int) [function, functional, no-evaluators]

syntax Int ::= super(Int) [function, functional, no-evaluators]

rule foo(super(X)) => true
    requires foo(X)
    [simplification]

syntax Cmd ::= bar(Int)

rule bar(X) => true
    requires foo(X)

endmodule
```

i-spec.k:
```
module I-SPEC
imports I

rule <k> bar(super(X)) => true </k>
     <c> foo(super(X +Int 1)) </c>
    requires foo(X)

endmodule
```

`kprove i-spec.k` passes, but it dumps nine `WarnSimplificationWithRemainder` warnings, consisting of > 600 lines, which is quite annoying.  (It is not a blocking issue, though.)  The use of the option `-w none` doesn't seem to help here.
