### ISSUE TITLE
Beacon chain: g-spec.k

### ISSUE THREAD

**Issue by daejunpark** [kframework/kore#1645]
The haskell-backend kprove hangs for [g-spec](https://github.com/runtimeverification/beacon-chain-verification/blob/master/dynamic/tests/symbolic/g-spec.k).  The REPL hangs even before starting the REPL command prompt.

The thing is that the g-spec is quite similar to [f2-spec](https://github.com/runtimeverification/beacon-chain-verification/blob/master/dynamic/tests/symbolic/f2-spec.k) in terms of the spec structure and the complexity, but f2-spec is passed.

To reproduce:
```
$ git clone git@github.com:runtimeverification/beacon-chain-verification.git
$ git checkout bd82ad69a2a8a414209149bb63bd70d5938bba30
$ cd dynamic
$ make deps
$ make build-static
$ kprove -d .build/defn/static -m VERIFICATION tests/symbolic/g-spec.k
```

**Comment by daejunpark** [comment]
It seems that this part (https://github.com/runtimeverification/beacon-chain-verification/blob/master/dynamic/tests/symbolic/g-spec.k#L77-L81) is problematic.  When they are commented out, the REPL quickly returned the command prompt. (Of course, the spec cannot be proved without them.)   Furthermore, among them, these two lines (https://github.com/runtimeverification/beacon-chain-verification/blob/master/dynamic/tests/symbolic/g-spec.k#L79-L80) seem to be most problematic --- if the two lines are commented out, the REPL returned the prompt in ~2min (with nine sub-claims split by the startup simplification).  But with the two lines, the REPL didn't return after 10min, and I killed it.

So, it seems that the startup simplification has a performance bug, when they are more than three equalities that split claims by case analysis.

**Comment by ttuegel** [comment]
The problem is an excessive number of branches created in the first step.

**Comment by ttuegel** [comment]
Sorry, my last comment was from looking at an old version of `g-spec.k`. I'm still not sure what the present issue is.
