### ISSUE TITLE
Add REPL option to see claim RHS

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1657]
Will help debug final implications from REPL.

**Comment by ana-pantilie** [comment]
@denis-bogdanas You can print any claim with the `claim <n>` command (or its `K` counterpart `kclaim <n>`); this will print the whole implication. You can see which claim you're proving using `claim` (with no arguments).

**Comment by ttuegel** [comment]
> You can see which claim you're proving using `claim` (with no arguments).

Maybe we could also have `claim` without arguments print the claim?

**Comment by ana-pantilie** [comment]
@ttuegel The help text for this is currently:
```
claim [n|<name>]                         shows the nth claim, the claim with <name> or if used without args shows the currently focused claim
```
I think the part which isn't clear here is that in the help text we use `[_]` to mean optional arguments ( I don't think we mention this explicitly).

I also checked if we have a command which prints the current claim and it looks like we don't. So I agree, it would be a good idea if `claim` would also unparse and print the current claim after specifying its number.

**Comment by ttuegel** [comment]
@andreiburdusa Is that clear?

**Comment by denis-bogdanas** [comment]
I guess that's enough then. With a few wishes:
1. The help introduction is worth expanding, explaining how to get the RHS with `claim`.
2. It would be good to have `kclaim-d`, similar to `konfig-d`.
3. I see all the options that do pretty-printing are not documented.

**Comment by andreiburdusa** [comment]
> @andreiburdusa Is that clear?

I can try to print the unparsed claim like Ana said, but Denis' list is not that clear for me

**Comment by ana-pantilie** [comment]
@andreiburdusa Item 2 refers to adding/modifying some aliases here https://github.com/kframework/kore/blob/master/dist/kast.kscript, and I think item 3 is about documenting these aliases. There already is this section in the wiki https://github.com/kframework/kore/wiki/Kore-REPL#k-output, maybe it would be worth adding some more details here.
