### ISSUE TITLE
Exponential behavior when parsing shared term

### ISSUE THREAD

**Issue by radumereuta** [kframework/kore#167]
I have this kore file: https://github.com/radumereuta/k-light/blob/evenLighter/src/test/k/unparametric_examples/imp/imp-rules.kore.info (about 300kB - the result of parsing IMP rules, with lots of sharing in them).
Sometime between June 6 and July 7 there has been a change which makes kore-parser take a HUGE amount of time to run (stopped it after 10 minutes).

**Comment by virgil-serbanuta** [comment]
1. Did you mean to point to another kore file? imp-rules.kore.info seems to be ~120k (github says `    
1638 lines (1625 sloc)  122 KB`).
2. Please provide reproduction steps. Here is what I tried:
```
$ cd src/main/haskell
$ git checkout master
$ git pull origin
<copy-pasted your file in test.kore>
$ rm .stack-work -r
$ rm kore/.stack-work -r
$ stack build
$ time stack exec kore-parser test.kore -- --no-print-definition --verify --chkattr
Reading the input file TimeSpec {sec = 0, nsec = 33802}
Parsing the file TimeSpec {sec = 0, nsec = 80521002}
Verifying the definition TimeSpec {sec = 0, nsec = 42824721}

real    0m0.222s
user    0m0.464s
sys     0m0.140s
$ ls -l test.kore
-rw-rw-r-- 1 virgil virgil 124451 iul 31 16:45 test.kore

```

**Comment by radumereuta** [comment]
1. That is the correct file. I estimated the size wrong. It's 122k
2.  A while back:
Version: ba56dd7 Jun 6
Usage: `kore-parser imp-rules.kore.info > imp-rules.out`
Time: 600 ms
Size of out file: ~8MB

Now:
Version: 9012a89
Usage: `kore-parser imp-rules.kore.info > imp-rules.out2`
Time: stopped it manually after ~5 minutes
Size of out file: ~25MB

Now that I know of the no print option, I guess I can use it since I don't use the output. But still, something happened in the last 2 months that made the printing much slower.

**Comment by traiansf** [comment]
@u-- @ttuegel could this be due to using the pretty printer?

**Comment by virgil-serbanuta** [comment]
@dfilaretti It seems that commit 6f5785df0e5ec488d9aed153513653a0ca5746fc introduced the issue.

**Comment by traiansf** [comment]
I'd bet it might be due to the change from 
```
      when willPrint  $ print parsedDefinition
```
to:
```
      when willPrint  $ putStrLn (prettyPrintToString parsedDefinition)
```
It seems such a benign change, though :-)

**Comment by njohnwalker** [comment]
Ignore that reference, sleep deprived.  I checked @traiansf 's suggestion; it is the issue.

**Comment by virgil-serbanuta** [comment]
We should have a performance test that runs the kore-parser tool on several inputs...

**Comment by bmmoore** [comment]
@traiansf That changes from using Show to using prettyPrintToString. It looks like that just exposed an existing performance problem with prettyPrintToString.

**Comment by virgil-serbanuta** [comment]
Commenting the last line in `betweenParentheses` changes the run time from 17 min to 4 min (on my computer). To be clear, I was going from this
```
betweenParentheses :: PrinterOutput w m => Flags -> m() -> m()
betweenParentheses NeedsParentheses thing = do
    write "("
    thing
    write ")"
```
to this
```
betweenParentheses :: PrinterOutput w m => Flags -> m() -> m()
betweenParentheses NeedsParentheses thing = do
    write "("
    thing
    --write ")"
```

**Comment by virgil-serbanuta** [comment]
The correct long-term solution is to fix `prettyPrintToString`. Right now the performance is acceptable for small files and we have a fix when processing large files (i.e. to use `--no-print-definition`), so we could leave it as-is until the proper solution is in place.

Does anyone object?

**Comment by radumereuta** [comment]
I'm already using the no-print option, so I'm ok for now.

**Comment by bmmoore** [comment]
PR #169 improves my time to parse and print that test file from 10 minutes to 1 second.
