### ISSUE TITLE
pretty printing claim RHS throws exception

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1671]
`java.util.NoSuchElementException: key not found: weakAlwaysFinally`
[Full claim and exception](https://gist.github.com/denis-bogdanas/51fb268f6becae60b45c6599219d90a4)

To reproduce:
- ERC20 branch `symb-testing`, commit `0478fd7c723fcfc5b08f094c38cb4958969c15ca`, latest K and latest Haskell backend. Command: `make tests/symb-test/demoSymbTest-spec.k.symb-prove`

This prevents debugging final implication but is not critical.

**Comment by ttuegel** [comment]
@traiansf Wasn't this fixed in the frontend?

**Comment by traiansf** [comment]
There is a PR open for it: https://github.com/kframework/k/pull/1209; however, it didn't managed to get past Jenkins.

**Comment by denis-bogdanas** [comment]
I see  https://github.com/kframework/k/issues/1203 is about `#KRewrite`. Will it fix this issue?

**Comment by traiansf** [comment]
Yes, it will: please see: https://github.com/kframework/k/pull/1209/files#diff-8e4c44f71f5c5716a531b78116cc6853R89

If the KRewrite patch does not work (I think it might trigger some termination / exponential behavior), then we could extract the patch for weakAlwaysFinally separately,

**Comment by traiansf** [comment]
Fixed by https://github.com/kframework/k/pull/1209
