### ISSUE TITLE
Removing top exists in predicates

### ISSUE THREAD

**Issue by ana-pantilie** [kframework/kore#1676]
When simplifying the configuration, we remove the top exists of the term, here:
https://github.com/kframework/kore/blob/13ce40513ff24a5f6a6c084ca6e804e6db9d6caa/kore/src/Kore/Step/Simplification/Pattern.hs#L43
We should do the same for the predicate (suggested by @virgil-serbanuta and @traiansf ).

Context: 
See `H3-SPEC` from https://github.com/kframework/kore/issues/1639 (the `requires` should be `ensures`) + https://runtimeverification.slack.com/archives/CC360GUTG/p1584350865139300?thread_ts=1584122164.136200&cid=CC360GUTG

**Comment by traiansf** [comment]
This does not seem to reproduce. Apparently whatever we are doing during the simplification process pushes the quantifier to the top where it already gets removed.
