### ISSUE TITLE
Update to K which specializes `==K` to others causes KEVM proof to fail

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#1686]
When we update the KEVM submodule for deps/k to `(84c0bcd) deps/k: 84c0bcd85 - Specialize ==K to sort-specific equality functions (#1151)`, it causes the `tests/specs/sum-to-n-spec.k` test to fail (or at least, take much much longer, 136s -> more than 900s).

To reproduce:

KEVM commit: `17841f999` which is current `upstream/master`
K commit: `84c0bcd85` which is before master, but contains Haskell backend commit `39608cd7`

In KEVM repo:

```
make deps RELEASE=true
make build -j4
make tests/specs/examples/sum-to-n-spec.k.prove
```

**Comment by ttuegel** [comment]
I suspect that we are now delegating something to Z3 (unintentionally) that we previously handled internally.

**Comment by ehildenb** [comment]
It would appear that this commit also affects the update to KWasm, which is blocking Polkadot project from updating KWasm version.

**Comment by ttuegel** [comment]
I confirmed that the problem is additional queries to Z3. I am still examining the queries themselves to determine the problem.
