### ISSUE TITLE
Underscore not supported in module name

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1695]
A module
```
module TEST_APPROVE-SPEC
```

Will generate the following in `spec.kore`:
```
module TEST'Unds'APPROVE-SPEC
```
And the following error when trying to run in kore-repl:
```
kore-repl: The main module, 'TEST_APPROVE-SPEC', was not found. Check the --module flag.
CallStack (from HasCallStack):
  error, called at app/share/GlobalMain.hs:442:13 in main:GlobalMain
```

**Comment by ttuegel** [comment]
The specification of Kore makes underscores illegal in all identifiers, so this is the intended behavior. What command did you use to run `kore-repl`?

**Comment by denis-bogdanas** [comment]
Then the error message has to be more specific. This is low priority of course.
The command was along the:
```
kore-repl --repl-script /mnt/d/k5/haskell-backend/src/main/native/haskell-backend/dist/kast.kscript .../vdefinition.kore --module SYMB-TEST-VERIFICATION --prove ... --spec-module <MODULE_NAME> --output ...
```

**Comment by ttuegel** [comment]
I see; the user's input from the command-line should go through the `ModuleName` parser.
