### ISSUE TITLE
Z3 error in symbolic testing full test-approve

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1702]
When running full test for `approve()` with `kore-repl` the following error appears:
```
user error (Unexpected result from the SMT solver:
  Command: (assert (= true (= (ite 32 <0> ) <0> ) ) )
  Expected: success
  Result: (error "line 2674728 column 31: invalid builtin application ite" )
```

How to reproduce:
- Latest k/kore/z3.
- KEVM branch `symb-testing`, commit https://github.com/kframework/evm-semantics/commit/f230d6f735d51e59cb0b21865e9c655dbcdf46c2
Command:
```
make tests/symb-test/test-approve-spec.k.symb-prove K_OPTIONS="-v --debug --haskell-backend-command \" kore-repl --repl-script <your K_HOME>/haskell-backend/src/main/native/haskell-backend/dist/kast.kscript \"" K_SUBMODULE=<your K_HOME>
```

Then in kore-repl:
```
stepf 11000
```
The task has to be left overnight. The last step alone that generates the error (on node 10857) seems to run in >2h.

**Comment by ttuegel** [comment]
This isn't valid SMT-LIB syntax: `(ite 32 <0> )`. `ite` takes three arguments, and the first must be a `Bool`. This was changed in the frontend recently, and I might have missed something when we updated it.

**Comment by denis-bogdanas** [comment]
Error is related to `minInt/maxInt`:
https://github.com/kframework/k/blob/3326d56e55547f489d2cbc7d6f2b0837794011ad/k-distribution/include/builtin/domains.k#L397-L398

**Comment by ttuegel** [comment]
The problem is that `SMT.AST.nameFromSExpr` is used, which discards the user-defined S-expression templates, keeping only the first symbol (in this case: `ite`). The arguments of the Kore symbol are applied to the S-expression symbol, rather than being used to complete the template. The transformation made by `nameFromSExpr` is always invalid and that function should be removed.

**Comment by denis-bogdanas** [comment]
This isn't really blocking. I solved the issue with a lemma that was necessary anyway.
