### ISSUE TITLE
Please check the KORE language syntax asap

### ISSUE THREAD

**Issue by grosu** [kframework/kore#18]
There were some inconsistencies in the KORE language syntax that @msaxena2 and I fixed.  We want 100% compliance between the KORE main interface and the KORE language, so we went through both and thus found the inconsistencies in the KORE language.  Please check: https://github.com/kframework/kore/wiki/KORE-Language-Syntax.

**Comment by msaxena2** [comment]
@grosu Our fixes to inconsistencies may have also introduced some inconsistencies - 
We changed 
```
syntax Pattern = Variable
```
to 
```
syntax Pattern = Name:Sort //Variable 
```
But now we have
```
Pattern = Name:Sort //Variable
                       ...
          | \exists(Variable, Pattern)
          | \forall(Variable, Pattern)
                       ...
```
With no reference to `Variable`. I guess we could have the following
```
Pattern = Name:Sort //Variable
                       ...
           | \exists(Name:Sort , Pattern)
           | \forall(Name:Sort, Pattern)
                       ...
```
But that means our quantifiers don't explicitly mention `Variable` anymore.

**Comment by grosu** [comment]
Actually it was good originally, I don't know why we changed that one ... since the target language (Scala) is order-sorted/typed, it is OK to regard the special productions of just one non-terminal as subsorts.  I'm going to change it back in a minute

**Comment by cos** [comment]
In that sense, it may be nice to give each production a sort name which will then correspond to the KORE trait/interface name. This way, all information would be there to generate the Scala/Java definition programmatically.

**Comment by msaxena2** [comment]
I think we changed it originally to have consistency with 
```
Pattern = Name: Sort   //Variable
    | Symbol(Pattern,*)  // Application
    | Symbol(Value)      // DomainValue
```
I think this is better - 
```
Pattern = Variable
      | Application
      | DomainValue
...

Application = Symbol(Pattern,*) 
DomainValue = Symbol(Value)
```

**Comment by grosu** [comment]
Fine with me.  @msaxena2 , feel free to go ahead and apply this change consistently (i.e., add sorts `And`, etc.)

**Comment by grosu** [comment]
This is irrelevant now, so closing.
