### ISSUE TITLE
No built-in rule for symbolic ==Int

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1886]
After adding a custom `==Int` rule to ERC0 verifier, we now see stuck terms like this:
```
#buf ( 32 , #if ?ACCT1 ==Int ?ACCT1 andBool ?ACCT ==Int ?ACCT #then ?SYMB_INT #else #lookup ( ?STORAGE0 , keccak ( #buf ( 32 , ?ACCT1 ) ++ #buf ( 32 , keccak ( #buf ( 32 , ?ACCT ) ++ b"0000000000000000000000000000000000000000000000000000000000000001" ) ) ) ) #fi )
```
https://github.com/runtimeverification/erc20-verification/pull/65
https://office.runtimeverification.com/jenkins/blue/organizations/jenkins/erc20-verification/detail/PR-65/4/pipeline/

All custom equality rules:
https://github.com/runtimeverification/erc20-verification/blob/9b50cc43e6daaf925ecaf4384bc0d85f7fd9d9e9/specs/symbolic/resources/symb-test-verification.k#L46-L53

**Comment by ttuegel** [comment]
We don't _have_ built-in rules for symbolic `==Int`. We also don't have a built-in rule for symbolic `#if _ #then _ #else _`, except in unification context. The simplest thing for us to do is add a built-in symbolic reflexivity rule for `==Int`, and we should do the same for any other built-in equalities.

**Comment by denis-bogdanas** [comment]
How are then `==Int` expressions evaluated? In another PR you said that `==Int` is not rewritten into `==K`. There is a lot of misunderstanding around these that should be documented.

**Comment by denis-bogdanas** [comment]
This implementation is not complete.
We have stuck terms like this:
```
#if ?ACCT1 ==Int ?ACCT3 andBool ?ACCT ==Int ?ACCT2
    #then ?SYMB_INT
    #else #lookup ( ?STORAGE0 , keccak ( #buf ( 32 , ?ACCT3 ) ++ #buf ( 32 , keccak ( #buf ( 32 , ?ACCT2 ) ++ b"0000000000000000000000000000000000000000000000000000000000000001" ) ) ) )
#fi
```
while top constraint contains:
```
#And
  {
    false
  #Equals
    ?ACCT3 ==Int ?ACCT1 ==Bool false ==Bool false
  }
```
Source: https://github.com/runtimeverification/erc20-verification/pull/70

@ttuegel Can you just rewrite `==Int` into `==K` and let full `==K` logic apply?

**Comment by ttuegel** [comment]
> Can you just rewrite `==Int` into `==K` and let full `==K` logic apply?

I don't think so; this has been a problem in the past for performance and for sending terms to the solver. I don't think it would help here, either: the top-level condition

```
  {
    false
  #Equals
    ?ACCT3 ==Int ?ACCT1 ==Bool false ==Bool false
  }
```

also wouldn't suffice to rewrite `?ACCT1 ==K ?ACCT3` to `false`.

Leaving that aside, the solver should be able to evaluate the `requires` of the [rule](https://github.com/kframework/k/blob/master/k-distribution/include/kframework/builtin/domains.k#L960) for `#if _ #then _ #else _ #fi`. If you can, I'd like to find out why it isn't.

**Comment by denis-bogdanas** [comment]
1. Why the condition wouldn't suffice for the rewrite? From the information contained there it should suffice.
2. How can I debug why requires is not applied?

**Comment by denis-bogdanas** [comment]
The side condition is not applied because `?ACCT1 ==Int ?ACCT3 andBool ?ACCT ==Int ?ACCT2` cannot be simplified to `false`. Question is why it's not simplified.

**Comment by ttuegel** [comment]
> The side condition is not applied because `?ACCT1 ==Int ?ACCT3 andBool ?ACCT ==Int ?ACCT2` cannot be simplified to `false`. Question is why it's not simplified.

That's not simplified because there is no rule that would rewrite that in a term context, with or without the side condition. The question is why `#if _ #then _ #else _ #fi` isn't simplified. One of the rules for that symbol should generate a condition

```
{
  false
#Equals 
  ?ACCT1 ==Int ?ACCT3 andBool ?ACCT ==Int ?ACCT2
}
```

which can be discharged by the solver.

You can debug equation evaluation with `--debug-equation "Lbl'Hash'if'UndsHash'then'UndsHash'else'UndsHash'fi'Unds'K-EQUAL-SYNTAX'Unds'Sort'Unds'Bool'Unds'Sort'Unds'Sort"`. In this case, it will be useful to debug the conditions sent to the solver with `--log-entries DebugEvaluateCondition`, but this will log everything sent to the solver (including irrelevant queries) so you will have to look for the conditions sent during function evaluation.

**Comment by denis-bogdanas** [comment]
I see option `--debug-equation` cannot be activated from `kore-repl` at runtime, like the others. Can it be added? `kore-repl` seems an order of magnitude slower if I activate both options above from the beginning.

**Comment by denis-bogdanas** [comment]
I did run with both options. Logs say `equation did not match term`. Kore doesn't attempt to evaluate the side conditions. Here is the relevant piece:
```
kore-repl: [2020-07-06 19:22:50.9406758] Debug (DebugEvaluateCondition):
    (InfoReachability) While simplifying the configuration:
    (DebugAttemptEquation) while applying equation at /mnt/d/erc20-verification/deps/evm-semantics/evm-types.md:671:28-671:117:
    (DebugEvaluateCondition) while evaluating predicate:
    solver returned satisfiable
kore-repl: [2020-07-06 19:22:50.946597] Debug (DebugAttemptEquation):
    (InfoReachability) While simplifying the configuration:
    applying equation at /mnt/d/k5/k-distribution/target/release/k/include/kframework/builtin/domains.k:960:8-960:67 to term:
        /* Fl Fn D Spa */
        Lbl'Hash'if'UndsHash'then'UndsHash'else'UndsHash'fi'Unds'K-EQUAL-SYNTAX'Unds'Sort'Unds'Bool'Unds'Sort'Unds'Sort{SortInt{}}(
            /* Fl Fn D Sfa */
            Lbl'Unds'andBool'Unds'{}(
                /* Fl Fn D Sfa */
                Lbl'UndsEqlsEqls'Int'Unds'{}(
                    /* Fl Fn D Sfa */ Var'Ques'ACCT1:SortInt{},
                    /* Fl Fn D Sfa */ Var'Ques'ACCT3:SortInt{}
                ),
                /* Fl Fn D Sfa */
                Lbl'UndsEqlsEqls'Int'Unds'{}(
                    /* Fl Fn D Sfa */ Var'Ques'ACCT:SortInt{},
                    /* Fl Fn D Sfa */ Var'Ques'ACCT2:SortInt{}
                )
            ),
            /* Fl Fn D Sfa */ Var'Ques'SYMB'Unds'INT:SortInt{},
            /* Fl Fn D Sfa */
            Lbl'Hash'lookup'LParUndsCommUndsRParUnds'EVM-TYPES'Unds'Int'Unds'Map'Unds'Int{}(
                /* Fl Fn D Sfa */ Var'Ques'STORAGE0:SortMap{},
                /* Fl Fn D Sfa */
                Lblkeccak'LParUndsRParUnds'SERIALIZATION'Unds'Int'Unds'ByteArray{}(
                    /* Fl Fn D Sfa */
                    Lbl'UndsPlusPlusUndsUnds'EVM-TYPES'Unds'ByteArray'Unds'ByteArray'Unds'ByteArray{}(
                        /* Fl Fn D Sfa */
                        Lbl'Hash'buf'LParUndsCommUndsRParUnds'EDSL'Unds'ByteArray'Unds'Int'Unds'Int{}(
                            /* Fl Fn D Sfa Cl */
                            /* builtin: */ \dv{SortInt{}}("32"),
                            /* Fl Fn D Sfa */ Var'Ques'ACCT3:SortInt{}
                        ),
                        /* Fl Fn D Sfa */
                        Lbl'Hash'buf'LParUndsCommUndsRParUnds'EDSL'Unds'ByteArray'Unds'Int'Unds'Int{}(
                            /* Fl Fn D Sfa Cl */
                            /* builtin: */ \dv{SortInt{}}("32"),
                            /* Fl Fn D Sfa */
                            Lblkeccak'LParUndsRParUnds'SERIALIZATION'Unds'Int'Unds'ByteArray{}(
                                /* Fl Fn D Sfa */
                                Lbl'UndsPlusPlusUndsUnds'EVM-TYPES'Unds'ByteArray'Unds'ByteArray'Unds'ByteArray{}(
                                    /* Fl Fn D Sfa */
                                    Lbl'Hash'buf'LParUndsCommUndsRParUnds'EDSL'Unds'ByteArray'Unds'Int'Unds'Int{}(
                                        /* Fl Fn D Sfa Cl */
                                        /* builtin: */ \dv{SortInt{}}("32"),
                                        /* Fl Fn D Sfa */
                                        Var'Ques'ACCT2:SortInt{}
                                    ),
                                    /* Fl Fn D Sfa Cl */
                                    \dv{SortBytes{}}(
                                        "0000000000000000000000000000000000000000000000000000000000000001"
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
kore-repl: [2020-07-06 19:22:50.9915671] Debug (DebugAttemptEquation):
    (InfoReachability) While simplifying the configuration:
    equation is not applicable:
    equation did not match term
```

**Comment by ttuegel** [comment]
You should double-check against your local copy of `domains.k`, but I think [this](https://github.com/kframework/k/blob/master/k-distribution/include/kframework/builtin/domains.k#L962) is the rule we are looking at. This equation can only be applied when the argument of `#if _ #then _ #else _ #fi` is injected into sort `K`. The symbol itself is parametric, so its arguments can be of any sort; in this term they are sort `Int` _not_ injected into `K`; therefore, this equation would not even match the term.

**Comment by denis-bogdanas** [comment]
It is the rule you mentioned.
1. What do you mean "injected into sort K"?
2. What should be done here?

**Comment by ttuegel** [comment]
As a workaround, these function rules should do the trick:

```
  rule #if C:Bool #then B1::Int #else _ #fi => B1 requires C
  rule #if C:Bool #then _ #else B2::Int #fi => B2 requires notBool C
```

By "injected into sort K", I mean [strictly casted](https://github.com/kframework/k/blob/master/pending-documentation.md#strict-casts).

**Comment by ttuegel** [comment]
See also: kframework/k#1415

**Comment by denis-bogdanas** [comment]
I fixed ERC20 in the meantime by not using `#if`. But speaking of this thread, is this a bug?
