### ISSUE TITLE
Unsatisfiable side condition not refuted by solver

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1887]
[Quote](https://github.com/kframework/kore/issues/1416#issuecomment-644174646):

> The 2 rules for step will create 3 branches: 2 for each rule + reminder. To eliminate the reminder you have to evaluate the side condition notBool I <Int 1 andBool notBool I ==Int 1 using lemma that is effectively I <Int 2. One term of the side condition evaluated in the context of the lemma and the other term results in false.

See also: https://github.com/kframework/k/pull/1339

**Comment by ttuegel** [comment]
Right now, this needs investigation. Is the unsatisfiable side condition sent to the solver? If so, why is it not refuted? Maybe: the simplification lemma is not sent to the solver?

**Comment by ttuegel** [comment]
This is the most blocking issue for the verification project.

**Comment by denis-bogdanas** [comment]
By the way, if you add `[smt-lemma]` to the lemma, the result is the same.

**Comment by ana-pantilie** [comment]
I can't reproduce the issue. The spec passes when the `smt-lemma` attribute is added to the `simplification` rule.

**Comment by denis-bogdanas** [comment]
Yes, that's right. I probably tested on Java backend.
@ttuegel what should we do with the test? I believe we don't have much tests for `[smt-lemma]`.

**Comment by ttuegel** [comment]
I think we should add it as a frontend regression test.
