### ISSUE TITLE
kore-repl: support a sequence of commands

### ISSUE THREAD

**Issue by daejunpark** [kframework/kore#1920]
It will be useful to have an operator to sequence multiple commands, say`;` like in a shell. That will allow users to create a new command by combining multiple commands.

For example, `step 11 ; config` will be a command that "runs a single opcode step, and prints the resulting configuration term" in the kevm setting (in kevm, a single opcode execution involves 10~11 semantic rules).

**Comment by ehildenb** [comment]
@daejunpark duplicate of #1826 , pick one to close.
