### ISSUE TITLE
Simplify double negation: `rule (B ==Bool false) ==Bool false => B`

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1944]
In top constraint we have terms like:
```
#And
  {
    false
  #Equals
    ?ACCT ==Int ?ACCT1 ==Bool false ==Bool false
  }
```

They might be source of performance issues. I'll add the rule in the title in the meantime.

**Comment by ehildenb** [comment]
Why don't we just use rules for this permanently? Is there any benefit to having the backend look out for this special case instead of just dealing with it via rewriting?

To me it seems that the backend should have as few special cases like this as possible.

**Comment by denis-bogdanas** [comment]
@ttuegel What's your opinion on this? Should we simplify double negation in the backend or with a rule?

**Comment by ttuegel** [comment]
I suggest we add a rule. Right now, the only special cases in the backend are cases where the backend wouldn't accept a rule, but I want to lift that limitation eventually and move as much as possible out of the backend.

**Comment by ehildenb** [comment]
It can go in a module `BOOL-SYMBOLIC` in `domains.k`.

**Comment by denis-bogdanas** [comment]
I added this rule to erc20:
```
rule (B ==Bool false) ==Bool false => B
```
But there is this type of double negation remaining:
```
#And
  {
    false
  #Equals
    0 <Int ?SYMB_INT ==Bool false
  }
```
How to simplify it?

**Comment by ttuegel** [comment]
> How to simplify it?

How about this rule?

```
rule X ==Bool false => notBool X
```

The backend has a built-in rule for `{_ #Equals notBool _}` which should handle it from there.

**Comment by denis-bogdanas** [comment]
Thanks. How can I simplify this:
```
#And #Not ( { A <Int B #Equals true } )
```
Would this rule work?
```
rule notBool (X  <Int Y ==Bool true) => Y <=Int X
```
Or this:
```
rule notBool (B ==Bool true) => notBool B
```

**Comment by ttuegel** [comment]
Rules for `notBool` and `==Bool` won't simplify `#Not` and `#Equals` (which are matching logic constructions). What do you want to simplify that predicate to?

**Comment by denis-bogdanas** [comment]
To `A >=In B`

**Comment by denis-bogdanas** [comment]
There is already this rule:
```
rule notBool (X  <Int Y) => Y <=Int X
```

**Comment by ttuegel** [comment]
The backends doesn't apply simplification rules over most Matching Logic constructions. (`#Ceil` is the only exception.) There might be a workaround we can apply until it does. The SMT solver understands that `#Not ( { A <Int B #Equals true } )` is the same as `A >=Int B #Equals true`, but if you are trying to simplify the `#Not` in the backend, I assume there is another rule you want to apply after?

**Comment by denis-bogdanas** [comment]
I added this rule and it seems to work, in combination with rule above.
```
rule #Not (B ==Bool true) => notBool B
```
Or it must be something else?

**Comment by ttuegel** [comment]
It's something else, the backend will not apply rules that have a Matching Logic connective at the top of the left-hand side.

**Comment by denis-bogdanas** [comment]
Fixed with lemmas.
