### ISSUE TITLE
Evaluate the right-hand side of claims

### ISSUE THREAD

**Issue by daejunpark** [kframework/kore#1945]
~The failed spec: https://github.com/kframework/evm-semantics/blob/edc36a77f4f34eb647ff54a0ea175c1e41a026ee/tests/specs/benchmarks/overflow00-nooverflow-spec.k~
The failed spec: https://github.com/kframework/evm-semantics/blob/kore-issue-1945/tests/specs/benchmarks/overflow00-nooverflow-spec.k

~The K version: 71d191fd6c2ad22b9e86fa9a4f962ffc5825e911~
The K version: ca462606e1ae2e564fb63d95cc7ef8d9cadbec44

The relevant part is:
```
<output> _ => #encodeArgs(#uint256(?N)) </output>
...
ensures true
andBool ?N ==Int A0 +Int 1
andBool #rangeUInt(256, ?N)
```

In the kore-repl, `claim` shows that the RHS of the <output> cell is not fully evaluated, but only partly evaluated to
```
#encodeArgsAux ( .TypedArgs , 32 , b"" ++ #buf ( 32 , #getValue ( #uint256 ( ?N ) ) ) , b"" )
```
where `#getValue ( #uint256 ( ?N ) )` should have been evaluated to `?N`, by applying the following rule in `edsl.md`:

```
    rule #getValue(#uint256( DATA )) => DATA
      requires #rangeUInt(256, DATA)
```

And, in the end, it reaches a stuck state, which includes the following `#Not` term:
```
#And
  #Not ( #Exists ?N . {
      #buf ( 32 , chop ( A0 +Int 1 ) )
    #Equals
      #encodeArgsAux ( .TypedArgs , 32 , b"" ++ #buf ( 32 , #getValue ( #uint256 ( ?N ) ) ) , b"" )
    }
  #And
    {
      true
    #Equals
      0 <=Int ?N
    }
  #And
    {
      true
    #Equals
      ?N <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936
    }
  #And
    {
      true
    #Equals
      ?N ==Int A0 +Int 1
    } )
```

If we modify the spec to not use the RHS only symbol `?N`, as follows, the proof is passed:
```
<output> _ => #encodeArgs(#uint256(A0 +Int 1)) </output>
```

**Comment by daejunpark** [comment]
Hmm, it's strange that the RHS of the <output> cell is not fully evaluated even if I changed it to not use the RHS-only variable. That is, this term `#getValue ( #uint256 ( A0 +Int 1 ) )` is not evaluated, even if we have:
```
#And
  {
    true
  #Equals
    0 <=Int A0
  }
#And
  {
    true
  #Equals
    A0 <Int 115792089237316195423570985008687907853269984665640564039457584007913129639935
  }
```
(Note that the last condition means `A0 <Int 2 ^Int 256 -Int 1`, so it is clear that `#rangeUInt(256, A0 +Int 1)`.

**Comment by daejunpark** [comment]
Seems to be related to: https://github.com/kframework/kore/issues/1916

**Comment by daejunpark** [comment]
From @ttuegel:
> Where should we put constraints over RHS-only variables? requires or ensures?

They must go in ensures, and the frontend should produce a warning if you put them in requires.

**Comment by daejunpark** [comment]
The proof is still failed with the latest K version (that includes the fix to #1916).

**Comment by ttuegel** [comment]
I realize now that this is a manifestation of #1278. I have added it to the list of known limitations (#1631).

**Comment by daejunpark** [comment]
An workaround would be to avoid using RHS-only variables, by replacing all RHS-only variables with specific terms. For example, from this original spec:
```
<cell> ... => foo(?X) </cell>
...
ensures ?X ==K bar(...)
```
to:
```
<cell> ... => foo(bar(...)) </cell>
...
```
But this is less ideal especially when `?X` appears in multiple places and `bar(...)` is a large term, because replacing all of them will make the spec harder to read.


Also, note that this workaround is not applicable, when we cannot specify terms for RHS-only variables. For example,
```
<cell> ... => foo(?X) </cell>
...
ensures ?X >Int 0
```
In this case, `?X` can be any positive integer, and we cannot avoid using the RHS-only variable.
