### ISSUE TITLE
kore-repl: Do not terminate process on (sub-process) error

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1992]
Right now if I run `konfig-d <inexisting file>`, result is:
```
[Error] Critical: Does not exist or not a directory:
<inexisting file>
```
This terminates `kore-repl` that might have run for a couple hours to this point.
Expected: error message should be printed but repl should not be terminated. Similar for any other command and error.

**Comment by andreiburdusa** [comment]
I wasn't able to reproduce the error:
```
Kore (0)> load /home/andrei/kore/kore/data/kast.kscript
Kore (0)> konfig-d inexistent_file
Config at node 0 is:
[Error] Critical: Does not exist or not a directory:
/home/andrei/kore/test/tiny/./inexistent_file
Kore (0)> load inexistent_file
Cannot find inexistent_file
Kore (0)> 
Could not parse command, try using 'help'.
Kore (0)>
```
I think it got fixed in the meantime
