### ISSUE TITLE
Option to print final state on success

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1994]
Please add an option to pretty-print final states, those on which final implication got proved. This would help inspect path condition in final state and how it got simplified by various lemmas. A workaround for this is to put an unreachable RHS into `<k>` cell but it would be cleaner to have an option.

**Comment by ttuegel** [comment]
While this would obviously be useful, I don't think we will get to it soon, because they backend doesn't have a mechanism for pretty-printing.

**Comment by denis-bogdanas** [comment]
Actually the workaround above would only work if proof has one path. If it has multiple paths kore backend will stop at the first final state reached.

Would it be possible to pass to front-end the union of all final states, instead of `#True`?

**Comment by ttuegel** [comment]
> Would it be possible to pass to front-end the union of all final states, instead of `#True`?

What does "final" mean in this context?

**Comment by denis-bogdanas** [comment]
All states for which initial rule RHS is implied.
