### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by grosu** [kframework/kore#2]
After a few slight changes to the regex (for example, adding `.` to the symbol syntax), I managed to parse the exact imp.kore that was generated by Maude.  Nice!

I didn't look deep into it, but here is a first comment regarding the performance.  It takes 0.7s to parse an empty definition, while 0.9s to parse a 25,000 lines definition!  Here is how I measured:
```
    val now = java.lang.System.nanoTime()
    val d = new TextToMini().parse(file)
    println(java.lang.System.nanoTime() - now)
```

Not bad at all.  I hope we can get rid of the 0.7s for empty definitions, though.  I'll look into it myself when I get a chance.

**Comment by grosu** [comment]
Found the culprit:
```
Scanner.init(file)
```
takes 0.5s even for an empty `file`.  This is ridiculously much.  We should find some other ways to read the file.  I'll look into this, because it is fun :)

**Comment by daejunpark** [comment]
Hmm, that's interesting. You might also want to try to use another Scanner using directly Java. That is, you can use:
```
class TextToMini {
  val Scanner = new ScannerJava() 
```
instead of:
```
class TextToMini {
  val Scanner = new ScannerScala() // ...
```

**Comment by daejunpark** [comment]
Could you push your changes? I guess my fix of white spaces could be conflict to your change.

**Comment by grosu** [comment]
ok, just pushed them.  nothing major.

**Comment by grosu** [comment]
> You might also want to try to use another Scanner using directly Java.

That does not seem to make a difference.
