### ISSUE TITLE
Please check KORE language wiki

### ISSUE THREAD

**Issue by grosu** [kframework/kore#20]
Please check this out and report any issues that you may find:
https://github.com/kframework/kore/wiki/KORE-Language-Syntax
@msaxena2 we need to add a link to code once we merge #19 
@cos please free to change my terminology for Scala notions if inconsistent.

**Comment by daejunpark** [comment]
A concern regarding the language syntax grammar. The `RegEx3` should represent the Java String (with escaping characters). Note that it should be enclosed by quotes (`"`).

Not sure though whether we should provide the exact regex for the Java strings, or simply say like:
```
RegEx3 == <java-string-literals>
```

**Comment by grosu** [comment]
Thanks, @daejunpark .  Fixed and closing.

**Comment by daejunpark** [comment]
@grosu Thanks. I also fixed another relevant part. https://github.com/kframework/kore/wiki/KORE-Language-Syntax/_compare/a8ccf958e8c93518becfdbfed2bd7928c67c79c5...5ed630ba52bc3c10d403ab237168eb26cb9a0acb
