### ISSUE TITLE
KRYPTO.keccak256 hook: No evaluators for function symbol

### ISSUE THREAD

**Issue by ReedOei** [kframework/kore#2004]
Using the following file (`test.k`):

```
module TEST-SYNTAX
    imports STRING-SYNTAX
    syntax String ::= keccak256(String) [function, hook(KRYPTO.keccak256)]

    syntax Program ::= run(String)
endmodule

module TEST
    imports TEST-SYNTAX

    configuration
        <k> $PGM:Program </k>

    rule run(S) => keccak256(S)
endmodule
```

And the following input file (`test.in`):
```
run("test")
```

I get:
```
kore-exec: [81011] Warning (WarnFunctionWithoutEvaluators):
    No evaluators for function symbol:
        Lblkeccak256'LParUndsRParUnds'TEST-SYNTAX'Unds'String'Unds'String{}
<k>
  keccak256 ( "test" ) ~> .
</k>
```

As far as I can tell, this is supported (I see there are definitions for the hooks, at least). When I run this with the Java backend, I get the expected result of:
```
<k>
  "9c22ff5f21f0b81b113e63f7db6da94fedef11b2119b4088b89664fb9a3cb658"
</k>
```

**Comment by ttuegel** [comment]
You must `kompile` with the option `--hook-namespaces KRYPTO`, otherwise the frontend will omit the `hook` attribute. `KRYPTO` is excluded from the default set of hooks by the frontend because the concrete backends require linking with extra dependencies to use it.
