### ISSUE TITLE
Unable to narrow on results of uninterpretted functions

### ISSUE THREAD

**Issue by nishantjr** [kframework/kore#2010]
The following definition crashes with (ErrorRewritesInstantiation)

```
module TEST
    imports BOOL
    imports INT

    syntax MaybeInt ::= "Some" Int
                      | "None"
    syntax MaybeInt ::= f() [function, functional, no-evaluators]

    configuration <k> f() </k>

    rule <k> None => true ... </k>
    rule <k> Some I => I ... </k>
endmodule
```

We expect it to narrow to two cases:

* one with `f() ==K None` and the K cell contains `true`
* one where `f() :=K Some I:Int` and the K cell contains `I`

**Comment by ttuegel** [comment]
We should change [this check](https://github.com/kframework/kore/blob/master/kore/src/Kore/Log/ErrorRewritesInstantiation.hs#L165) so that any configuration that is not concrete is considered symbolic for the purpose of allowing narrowing.
