### ISSUE TITLE
Refute side condition by transitivity of equality

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2095]
Follow-up to #2089.

This is another unsatisfiable side condition which is not detected by Z3 or the backend itself:

```
    #Ceil ( #lookup ( 'QuesUnds'3 , int , 'QuesUnds'4:Int , int ) )
  #And
    {
      #lookup ( 'QuesUnds'3 , int , 'QuesUnds'4:Int , int )
    #Equals
      None
    }
  #And
    {
      #lookup ( 'QuesUnds'3 , int , 'QuesUnds'4:Int , int )
    #Equals
      Some I3:Int
    }
```

This side condition is unsatisfiable because `None` and `Some` are distinct constructors. `#lookup` isn't translated for the SMT solver because it is a partial function. However, it is known to be defined, so we could take advantage of that fact. (How?)

We could also use the first equality as a substitution to simplify the second equality. This would also solve #2032. We would need some heuristic for doing this; maybe: given `\equals(function, constructor-at-top)`, substitute the right-hand side for the left-hand side everywhere.

**Comment by ttuegel** [comment]
@sskeirik Please replicate the `kore-exec` run that produced this condition, with the option `--bug-report issue-2095`, and attach the result to this issue.

**Comment by sskeirik** [comment]
Here is the issue tarball: https://drive.google.com/file/d/1rrLns6ARLqUC_KtJQY1xV1BmS10vC--P/view?usp=sharing

**Comment by virgil-serbanuta** [comment]
"However, it is known to be defined, so we could take advantage of that fact. (How?)"
We could translate `a == b` by first replacing it with `(ceil(a) and ceil(b) and a==b) or (not ceil(a) and not ceil(b))`, then simplifying the new expression. Then, in the resulting expression, we can translate `a==b` without caring about definedness.

The equality simplification thing is also a nice option.

**Comment by ttuegel** [comment]
Bug report: [issue-2095.tar.gz](https://github.com/kframework/kore/files/5152684/issue-2095.tar.gz)

**Comment by ttuegel** [comment]
> We could also use the first equality as a substitution to simplify the second equality. This would also solve #2032. We would need some heuristic for doing this; maybe: given `\equals(function, constructor-at-top)`, substitute the right-hand side for the left-hand side everywhere.

I'm thinking of taking this approach because I realized it is a simple extensions of what I am doing in #2107.

**Comment by ttuegel** [comment]
@sskeirik Could you please take a look at the results here, and confirm if this is the expected result? https://github.com/kframework/kore/pull/2147#issuecomment-693469254

**Comment by ttuegel** [comment]
We need to extend this to handle these cases:

- [ ] `\equals(function, constructor-at-top)`
- [ ] `\equals(function, sort-injection-at-top)`
- [ ] `\equals(function, builtin)`

**Comment by sskeirik** [comment]
I wonder if this restricted rule might be sufficient for many cases?

`\equals(function, term)`

where `term` is a combination of:

1. constructors
2. injections
3. variables
4. (maybe) builtins (I'm not sure if builtins include functions as well)

Depending on how (4) is defined, this will ensure that the `term` is normalized. Restricting to (1)-(3) would seem to guarantee it.

And I think (1)-(3) are enough for my case, since what I appear to appear to have is:

`\equals( function, injection(variable) )`

**Comment by ttuegel** [comment]
@sskeirik Would it be possible to get the original files that produced this bug report?

**Comment by sskeirik** [comment]
@ttuegel They should be part of the issue tarball link that is attached earlier in the comments, if I understand correctly. If that's not the case, I doubt I can get the original files.
