### ISSUE TITLE
`==Int` not correctly simplified by Kore

### ISSUE THREAD

**Issue by sskeirik** [kframework/kore#2109]
I have a test that generates a configuration with a constraint of the form:

```
{ I2 +Int 1 ==Int I3 +Int 1 #Equals false }
```

which, as far I understand, Kore should be able to further simplify, but does not.

Here is the `kore-exec` dump using `--bug-report`: https://drive.google.com/file/d/1v-oIJEou_AQ4qPKn7sIzFQy6ZdZXXsk7/view?usp=sharing

**Comment by ttuegel** [comment]
Attached: [issue-2109.tar.gz](https://github.com/kframework/kore/files/5151604/issue-2109.tar.gz)

**Comment by ttuegel** [comment]
This should be handled [here](https://github.com/kframework/kore/blob/master/kore/src/Kore/Builtin/EqTerm.hs#L71). We should start by adding more unit tests.
