### ISSUE TITLE
Inefficient Equation renaming

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2120]
Renaming Equations with [`Kore.Equation.Application.targetEquationVariables`](https://github.com/kframework/kore/blob/8ee3470041bd6b5e6a9460fc775bda29036b01b5/kore/src/Kore/Equation/Application.hs#L401) is a significant inefficiency because it traverses the entire Equation every time it is attempted, even if there is nothing to rename. We cannot use the same approach as with [`Kore.Rewriting.RewritingVariable.RewritingVariableName`](https://github.com/kframework/kore/blob/master/kore/src/Kore/Rewriting/RewritingVariable.hs#L64) because the variable parameter of the equations may vary during execution.

The `Target` variable type is used by the matcher so that it prefers to instantiate variables from the equation rather than from the term. It is not strictly necessary to have a distinct type for this, and that would eliminate the overhead of `targetEquationVariables`, but it leaves the overhead of the first `Equation.mapVariables` call, which is paid at every attempt of an equation.

My best suggestion is that we consider _fixing_ the variable type parameter so that we can use the `RewritingVariableName` approach (map all the equation variable names at initialization).

---

#### Plan

- [x] Fix all the `variable` type parameters to `RewritingVariableName` in `Kore.Equation.Application`. Do not remove the type parameter from any data types, but only fix the parameter where it appears. Follow the **Mikado Method** described below. (appetite: M)
- [x] Add an `EquationVariableName` to `RewritingVariableName`. It should be the "smallest" constructor according to `compare`. (appetite: S)
- [ ] Initialize all `Equation` to have `EquationVariableName` variables. (appetite: S)
- [ ] Don't change the variable type to `Target` in `Kore.Equation.Application`. Check before matching that the term has no free `EquationVariableName`s. Check after matching and unification that there are no free `EquationVariableName`s.

#### Mikado Method

The Mikado Method is a technique for making large changes to complex interdependent systems incrementally. The result should be a clean Git history showing incremental changes while refactoring the code to be more malleable. We will use `git stash` as a stack of pending changes.

1. **Goal:** Make the change we want to see (the "goal"). At the first iteration, this will be: fixing the type parameters of [`Kore.Equation.Application.attemptEquation`](https://github.com/kframework/kore/blob/3fd34f99a05745bbc792538042c0513724c3cf37/kore/src/Kore/Equation/Application.hs#L152).
2. **Test:** Build and run tests.
    1. **Pass:** If everything passes, we are done with this goal. Make a commit (`git commit ...`). Get the next pending goal (`git stash pop`) and **Test** again. If there are no more stashed changes, we are done.
    2. **Fail:** If the build or tests fail, identify the source of the failure. This will be the new goal. Stash your changes so far (`git stash`) and begin again at **Goal**.

Description: http://www.methodsandtools.com/archive/mikado.php

**Comment by andreiburdusa** [comment]
For the first checkbox, so far I changed the following files:
```
	modified:   kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs
	modified:   kore/src/Kore/Builtin/AssociativeCommutative.hs
	modified:   kore/src/Kore/Builtin/Builtin.hs
	modified:   kore/src/Kore/Builtin/EqTerm.hs
	modified:   kore/src/Kore/Builtin/Int.hs
	modified:   kore/src/Kore/Builtin/KEqual.hs
	modified:   kore/src/Kore/Builtin/List.hs
	modified:   kore/src/Kore/Builtin/Map.hs
	modified:   kore/src/Kore/Builtin/Set.hs
	modified:   kore/src/Kore/Builtin/String.hs
	modified:   kore/src/Kore/Builtin/Verifiers.hs
	modified:   kore/src/Kore/Equation/Application.hs
	modified:   kore/src/Kore/Equation/Registry.hs
	modified:   kore/src/Kore/Equation/Sentence.hs
	modified:   kore/src/Kore/Equation/Simplification.hs
	modified:   kore/src/Kore/ModelChecker/Simplification.hs
	modified:   kore/src/Kore/ModelChecker/Step.hs
	modified:   kore/src/Kore/Rewriting/RewritingVariable.hs
	modified:   kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
	modified:   kore/src/Kore/Step/Function/Evaluator.hs
	modified:   kore/src/Kore/Step/Rule/Combine.hs
	modified:   kore/src/Kore/Step/Search.hs
	modified:   kore/src/Kore/Step/Simplification/And.hs
	modified:   kore/src/Kore/Step/Simplification/AndPredicates.hs
	modified:   kore/src/Kore/Step/Simplification/AndTerms.hs
	modified:   kore/src/Kore/Step/Simplification/Application.hs
	modified:   kore/src/Kore/Step/Simplification/Ceil.hs
	modified:   kore/src/Kore/Step/Simplification/Condition.hs
	modified:   kore/src/Kore/Step/Simplification/Equals.hs
	modified:   kore/src/Kore/Step/Simplification/Exists.hs
	modified:   kore/src/Kore/Step/Simplification/Iff.hs
	modified:   kore/src/Kore/Step/Simplification/Implies.hs
	modified:   kore/src/Kore/Step/Simplification/In.hs
	modified:   kore/src/Kore/Step/Simplification/Not.hs
	modified:   kore/src/Kore/Step/Simplification/NotSimplifier.hs
	modified:   kore/src/Kore/Step/Simplification/OrPattern.hs
	modified:   kore/src/Kore/Step/Simplification/Pattern.hs
	modified:   kore/src/Kore/Step/Simplification/Rule.hs
	modified:   kore/src/Kore/Step/Simplification/Simplify.hs
	modified:   kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
	modified:   kore/src/Kore/Step/Simplification/TermLike.hs
	modified:   kore/src/Kore/Step/Step.hs
	modified:   kore/src/Kore/Step/Substitution.hs
	modified:   kore/src/Kore/Unification/Procedure.hs
	modified:   kore/src/Kore/Unification/SubstitutionSimplifier.hs
	modified:   kore/src/Kore/Unification/UnificationProcedure.hs
	modified:   kore/src/Kore/Verified.hs
```

**Comment by ttuegel** [comment]
It seems that we won't be able to specialize the type of variables before we remove the `Target` wrapper, so we will do that first. It's helpful to understand why we have `Target` in the first place. When we do matching or unification, sometimes we get _variable-renaming_ substitutions with the form:

```
X:S{} = Y:S{}
```

This substitution is completely symmetric: we could replace variable `X` by `Y` everywhere, or the other way around. But in practice there we usually prefer one of these over the other. For example, if we are applying a rule to the configuration, and `X` comes from the configuration and `Y` comes from the rule, then we would prefer to replace the `Y`s. That's what `Target` is for: we wrap the `Y`s in `Target` and the `X`s in `NonTarget`, and then the substitution normalization routine automatically sorts any variable-renaming substitutions correctly. The purpose of the `Target` type is to feed extra information into the substitution normalization routine.

Here's how we will get rid of `Target`: substitution normalization won't sort the variable-renaming substitutions anymore. We will sort any variable-renaming substitutions after normalization. We will add a function

``` haskell
orientSubstitution
    :: InternalVariable variable
    => (SomeVariableName variable -> Bool)  -- ^ 'True' if the variable should be on the left-hand side of the substitution
    -> Map (SomeVariableName variable) (TermLike variable)
    -> Map (SomeVariableName variable) (TermLike variable)
```

`orientSubstitution` should find all the `X = Y` pairs and, whenever the provided function returns `True` for `Y` and `False` for `X`, it should swap the order to `Y = X`. To keep the substitution normalized, the new substitution should be applied to every `TermLike` in the map.

After that function is implemented, use it in `Kore.Equation.Application.applyMatchResult` to fix the order of the substitution. The  first argument to `orientSubstitution` should return `True` if the variable occurs in the `Equation`. Remember to apply the oriented substitution to the `predicate` in the match result, too!

After all that is done, we can remove the `Target` type from `Kore.Equation`.
