### ISSUE TITLE
Remove the bogus _PREDICATE sort

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2152]
Follow up on #1442.

We can remove this after we implement a specialized simplifier for `Predicate`.

**Comment by ttuegel** [comment]
> We can remove this after we implement a specialized simplifier for `Predicate`.

I don't think this is really true, because the simplifier doesn't really look at the sort.

**Comment by ttuegel** [comment]
This task includes writing a new `Predicate` simplifier.

**Comment by Boarders** [comment]
In the TODO in the code it says:
```
Add a constructor

> data Sort = ... | FlexibleSort

to use internally as a placeholder where the predicate sort is not yet
known. Using the sort _PREDICATE{} is a kludge; the backend will melt down if
the user tries to define a sort named _PREDICATE{}. (At least, this is not
actually a valid identifier in Kore.)

Until this is fixed, the identifier _PREDICATE is reserved in
Kore.ASTVerifier.DefinitionVerifier.indexImplicitModule.
```

Is this still a preferred solution or should a flexible sort always be passed as an extra argument as suggested above?

**Comment by ttuegel** [comment]
That TODO is out of date, but neither should a flexible sort be passed as an extra argument. A _fixed_ sort should be passed as an argument wherever it may be required; the backend should use fixed sorts everywhere.

**Comment by Boarders** [comment]
I'm still unclear on what is wanted for example in `Kore.Sort` is a function:
```haskell
rigidSort :: Sort -> Maybe Sort
rigidSort sort
    | sort == predicateSort = Nothing
    | otherwise = Just sort
```
along with other functions that implicitly make use of this sort. Should such functions no longer exist or should they take predicateSort as an argument that is deferred to the call site in each instance?

**Comment by Boarders** [comment]
When trying to remove `predicateSort` I then remove the various `mkFoo_` methods that rely on it. I'm not quite sure what to do with the method in `Kore.Internal.Predicate` e.g.
```
instance InternalVariable variable => Pretty (Predicate variable) where
    pretty = unparse . fromPredicate_
 ```
 I don't think I can have any `Sort` available at this point so should I remove such methods or something else?

**Comment by ttuegel** [comment]
This instance is very suspicious to me. Where is it used?

**Comment by Boarders** [comment]
I'm not sure quite yet, I'm removing the relevant functions first and then working out using type error, but I'll see if that instance can just be deleted later on.

**Comment by Boarders** [comment]
I aim wondering if a `Implication` has a natural sort. It is defined [here](https://github.com/kframework/kore/blob/dfbaeed02fb9327a08089969c160d5931118ed89/kore/src/Kore/Step/Implication.hs#L96). The left field has a `Pattern RewritingVariableName` which has a sort but I don't know if that is the same sort as the `right` sort (when it has one).
