### ISSUE TITLE
Rules with function in LHS don't work

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#2187]
Rules with `[simplification]` or `[priority(40)]` that contain functions in LHS output weird results. First category in tests below is expected to work, while for rules with priority LHS functions should be rejected by the front-end, I guess.

File `verif.k`:
```
module VERIF
    syntax KItem ::= init1(    Int )
                   | init2(    Int )
                   | state1(   Int )
                   | state2(   Int )
                   | stateFoo( Int )
                   | stateBar( Int )

    syntax Int ::= foo( Int ) [function]
                 | bar( Int ) [function]

    rule <k> init1(I)        => state1(   I ) ... </k>
    rule <k> init1( foo(I) ) => stateFoo( I ) ... </k> [simplification]
    rule <k> init2(I)        => state2(   I ) ... </k>
    rule <k> init2( bar(I) ) => stateBar( I ) ... </k> [priority(40)]
endmodule
```

File `test-foo-spec.k`
```
module TEST-FOO-SPEC
    imports VERIF

    rule <k> init1(foo(I)) => stateFoo(I) ... </k>
endmodule
```
Result:
```
#Ceil ( foo ( I ) )
#And
 #Not ( {
  I
#Equals
  I0
} )
#And
<k>
  stateFoo ( I0 ) ~> _DotVar1 ~> .
</k>
#And
{
  foo ( I )
#Equals
  foo ( I0 )
}
```

File `test-bar-spec.k`
```
module TEST-BAR-SPEC
    imports VERIF

    rule <k> init2(bar(I)) => stateBar(I) ... </k>
endmodule
```

Result: similar to above.

File `test-state1-spec.k`
```
module TEST-STATE1-SPEC
    imports VERIF

    rule <k> init1(I) => state1(I) ... </k>
endmodule
```

Result:
```
#Ceil ( foo ( I0 ) )
#And
<k>
  stateFoo ( I0 ) ~> _DotVar1 ~> .
</k>
#And
{
  I
#Equals
  foo ( I0 )
}
```

File `test-state2-spec.k`:
```
module TEST-STATE2-SPEC
    imports VERIF

    rule <k> init2(I) => state2(I) ... </k>
endmodule
```

Result: similar to above.

https://github.com/kframework/k/tree/a6a9268cd7b568bb4a310da66f6c623ebb037629/k-distribution/tests/regression-new/func-lhs-haskell

**Comment by ttuegel** [comment]
`simplification` should only apply to function rules, and the frontend should reject it being applied elsewhere. The backend won't do anything with it on a rewrite rule, but it may affect how the rule is translated into Kore.

The frontend is supposed to reject _any_ rewrite rule with functions on the left-hand side. I think the results you are seeing are what I would expect from trying to rewrite with functions.

**Comment by denis-bogdanas** [comment]
That is not what pending documentation says. It explicitly states that `[simplification]` can be applied to any rules: https://github.com/kframework/k/blob/master/pending-documentation.md#simplification-attribute-haskell-backend

In fact the semantics described above, of applying simplification without reminder, is quite useful.

**Comment by ttuegel** [comment]
I guess that you are reading this sentence:

> Note that the simplification attribute can be applied to any rule, not just function rules, and that simplification rules are tried before rules from the semantic definition.

Neither clause of that sentence is true, or ever has been true, so I don't know what that's about.

**Comment by denis-bogdanas** [comment]
So you mean documentation is incorrect? Then it should be discussed and fixed.
