### ISSUE TITLE
Simplification rule not applied before regular rules in a specific setting

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#2190]
Test excerpt from KEVM, file `verif.k`:
```
module VERIF
    imports DOMAINS

 // KEVM code
 // -----------------------------------------------------------

    syntax Set ::= "#precompiledAccounts" "(" ")" [function]
 // -----------------------------------------------------------
    rule #precompiledAccounts()           => SetItem(1) SetItem(2)

    syntax KItem ::= OpCode
    syntax OpCode ::= NullStackOp | InternalOp
    syntax NullStackOp   ::= PrecompiledOp
    syntax PrecompiledOp ::= #precompiled ( Int ) [function]
 // --------------------------------------------------------
    rule #precompiled(1) => ECREC
    rule #precompiled(2) => SHA256

    syntax PrecompiledOp ::= "ECREC" | "SHA256"

    syntax InternalOp ::= "#precompiled?" "(" Int ")"
 // --------------------------------------------------------------
    rule <k> #precompiled?(ACCTCODE) => #next [ #precompiled(ACCTCODE) ] ... </k>
      requires         ACCTCODE in #precompiledAccounts()
    rule <k> #precompiled?(ACCTCODE) => .                                ... </k>
      requires notBool ACCTCODE in #precompiledAccounts()

    syntax InternalOp ::= "#next" "[" OpCode "]"
 // --------------------------------------------------------
    rule <k> #next [ OP ] => OP ... </k>

    syntax Int ::= #newAddr ( Int , Int )         [function]
    rule #newAddr(ACCT, NONCE) => ACCT +Int NONCE [concrete]

 // ERC20 verifier code
 // -----------------------------------------------------------
    rule <k> #precompiled?(ACCTCODE) => #next [ #precompiled(ACCTCODE) ] ... </k>
      requires         #inPrecompiledAccounts(ACCTCODE)                            [priority(40)]
    rule <k> #precompiled?(ACCTCODE) => .                                ... </k>
      requires notBool #inPrecompiledAccounts(ACCTCODE)                            [priority(40)]

    syntax Bool ::= #inPrecompiledAccounts ( Int )                                 [function, functional]
    rule #inPrecompiledAccounts(ACCTCODE)  => ACCTCODE in #precompiledAccounts()
    rule #inPrecompiledAccounts(#newAddr(_,_)) => false                            [simplification]

endmodule
```

File `precompiled-newaddr-spec.k`:
```
module PRECOMPILED-NEWADDR-SPEC
    imports VERIF

    rule <k> #precompiled?(#newAddr(_, 1)) => . ... </k>
endmodule
```

Result:
```
  #Ceil ( #newAddr ( _0 , 1 ) )
#And
  #Ceil ( #precompiled ( #newAddr ( _0 , 1 ) ) )
#And
  <k>
    #precompiled ( #newAddr ( _0 , 1 ) ) ~> _DotVar1 ~> .
  </k>
#And
  {
    #newAddr ( _0 , 1 ) in SetItem ( 1 )
    SetItem ( 2 )
  #Equals
    true
  }
```

We expect `[simplification]` rule to apply for `#inPrecompiledAccounts(#newAddr(_,_))`, while it looks like regular rule applies.

https://github.com/kframework/k/tree/649744eb6291bf123c9d58670d8badbf329c2ec2/k-distribution/tests/regression-new/priority-simpl-combohttps://github.com/kframework/k/tree/649744eb6291bf123c9d58670d8badbf329c2ec2/k-distribution/tests/regression-new/priority-simpl-combo

In full ERC20 verifier a funnier thing happens. `#precompiled ( #newAddr ( ... )` gets evaluated further on as if it's a non-function symbol, one branch apparently picks ECMUL, and K gets stuck with:
```
      <k>
        #ecmul ( ( #asWord ( b"70a08231" ++ ( #buf ( 32 , ?ACCT ) [ 0 .. 28 ] ) ) , #asWord ( #buf ( 32 , ?ACCT ) [ 28 .. 32 ] ) ) , 0 ) ~> #pc [ #precompiled ( #newAddr ( ?ACCT , 1 ) ) ] ~> #execute ~> #return 1728 32 ~> #pc [ STATICCALL ] ~> #execute ~> #successOrRevert ~> #setKAssertCount ~> .
      </k>
```
https://office.runtimeverification.com/jenkins/blue/organizations/jenkins/erc20-verification/detail/PR-150/11/pipeline/

Maybe it's a different bug.

This is required for ERC20 verifier.

**Comment by denis-bogdanas** [comment]
Marking the last rule in definition with `[priority(40)]` doesn't change the result.

But defining last function like this leads to kompilation error:
```
    syntax Bool ::= #inPrecompiledAccounts ( Int )                                 [function]
    rule #inPrecompiledAccounts(ACCTCODE)  => ACCTCODE in #precompiledAccounts()   [concrete]
    rule #inPrecompiledAccounts(#newAddr(_,_)) => false                            [simplification]
```

Result:
```
[Error] Compiler: Found concrete attribute without simplification attribute on
function with one or more non-concrete rules.
        Source(/home/denis/erc20-verification/deps/evm-semantics/deps/k/k-distribution/tests/regression-new/priority-simpl-combo/./verif.k)
        Location(43,10,43,81)
```
Error points on rule with `[concrete]`.

Looks like front-end has issues with last rule.

**Comment by denis-bogdanas** [comment]
1. If priorities are not supposed to work with function rules, where should they be rejected?

2. What's your proposal for the separate bug on full KEVM? If this example couldn't reproduce it, then I don't know what triggers it. Should I open a separate issue and keep a special ERC20 branch for it? Seems rather serious.

**Comment by ttuegel** [comment]
> If priorities are not supposed to work with function rules, where should they be rejected?

`priority` does work with function rules. You cannot nest functions on the left-hand side of a function rule, unless you use the `simplification` attribute. (This should be detected by the frontend, see kframework/k#1588.)

> What's your proposal for the separate bug on full KEVM? If this example couldn't reproduce it, then I don't know what triggers it.

There is a guard in the backend that prevents narrowing when applying function rules. I think it's too liberal in the case where the rule binds no variables. I will try to make a minimal example.

**Comment by ttuegel** [comment]
> In full ERC20 verifier a funnier thing happens. `#precompiled ( #newAddr ( ... )` gets evaluated further on as if it's a non-function symbol, one branch apparently picks ECMUL...

I created a minimal example to investigate this, and I am convinced that the backend is doing the correct thing here. It's not evaluating `#precompiled( #newAddr(_, _) )`. You can see that this term remains unevaluated in the configuration. Actually, a rewrite rule has `ECMUL` on the left-hand side, and tries to unify with `#precompiled( #newAddr(_, _) )`, producing `#precompiled( #newAddr(_, _) ) #Equals ECMUL`. There is nothing in the definition to contradict this branch, so execution continues. Here is a small definition and spec which reproduces this behavior:

`test-2.k`:
```.k
module TEST-2
  import INT

  syntax Bool ::= fun ( Int ) [function]
  rule fun(1) => true
  rule fun(2) => false

  syntax Int ::= i ( Int ) [function]

  syntax KItem ::= "#true" | "#false" | "#assert" Bool

  rule <k> #assert true => #true </k>
  rule <k> #assert false => #false </k>
endmodule
```

`test-2-spec.k`:
```
module VERIFICATION
  import TEST-2
endmodule

module TEST-2-SPEC
  import VERIFICATION
  claim <k> #assert fun(i(X:Int)) => #true </k>
endmodule
```
