### ISSUE TITLE
Solver reset interval should be configurable

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2207]
- [ ] Replace [this constant](https://github.com/kframework/kore/blob/289f9d520e6a506e9ea6f1558589e576af3a5c1b/kore/src/SMT.hs#L353) with a field in the [SMT configuration](https://github.com/kframework/kore/blob/289f9d520e6a506e9ea6f1558589e576af3a5c1b/kore/src/SMT.hs#L426).
- [ ] Add a command-line option `--solver-reset-interval` which takes a positive integer and sets the appropriate value in the configuration.

**Comment by ttuegel** [comment]
@ehildenb This would allow you to tweak the reset interval for the SMT solver and work around the issues you're having with KEVM. In the worst case, you could set `--solver-reset-interval 1` and every query would run in a fresh solver (at some performance penalty).

**Comment by ehildenb** [comment]
@ttuegel maybe instead if the backend detects a solver anomaly, it should reset the solver immediately and re-try the query?

You could still set a manual reset interval, but I think the backend should try to recover from solver anomalies automatically if possible.
