### ISSUE TITLE
Rule merger should identify duplicate rules in error message

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2228]
The error message for "duplicate rules" in the rule merger should:

- [ ] state the duplicated identifier for the user, and
- [ ] distinguish between duplicate unique identifiers and duplicate user-specified labels.

Fixes #2226 

The error message is coming from [`Kore.Exec.extractRules`](https://github.com/kframework/kore/blob/11e10fbb61a31ef555f15d44721dc6253ab787e7/kore/src/Kore/Exec.hs#L564).

**Comment by ehildenb** [comment]
@ttuegel I don't understand how this fixes #2226. The rules it's asking to merge there are not duplicates, it's just 2 rules which run in sequence (b18de3fcecea8fe42c86c6b41a523e6544dfa722b88a941bf2092e1d2fd23bb6 followed by 284ca93dc98993cc05a483d24d065f72abba0a7d899ec58cd3c694f04ab4e444).

Moreover, there _are_ rule merges I want to do which have the same rule repeated multiple times (for example, a rule which processes a list of elements one at a time and runs maybe 10 times in a row).

Maybe I'm not fully understanding the notion of "duplicate rule" here though.

**Comment by ttuegel** [comment]
The message about duplicate rules means that there are two distinct rules in the semantics which were given the same name. If the backend would identify the duplicate name and the rules involved, then the root cause should appear.
