### ISSUE TITLE
Missing hook: LIST.make

### ISSUE THREAD

**Issue by gtrepta** [kframework/kore#2253]
With this small k definition:
```
requires "domains.md"

module TEST
    imports DOMAINS
    imports ARRAY

    configuration
        <k> $PGM:KItem </k>

endmodule
```

Trying to krun `arr ( .List , 10 , 0 ) [0]` returns `#Bottom`. The LLVM backend will return 0.

Trying to krun `arr ( .List , 10 , 0 ) [0 <- 1]` gives an error for a missing LIST.make hook.

It looks like it's these rules in `domains.md:164` for the array update:
```
  syntax List ::= ensureOffsetList(List, Int, KItem) [function]
  rule ensureOffsetList(L::List, IDX::Int, D::KItem) => #if IDX >=Int size(L) #then updateList(makeList(IDX +Int 1, D), 0, L) #else L #fi

  rule arr(L::List, I::Int, D::KItem) [ IDX::Int <- VAL::KItem ] => arr(ensureOffsetList(L, IDX, D) [ IDX <- VAL ], I, D)
```

**Comment by ttuegel** [comment]
The backend does not provide an implementation of `ARRAY`, so the bugs are in the symbolic implementation provided with the frontend.

**Comment by gtrepta** [comment]
How about LIST.make? The symbolic rules for an array update try to use it, so unless we find a way without it should we still get that implemented?

This rule for the array lookup seems to be working fine when `IDX <Int size(L)`, but returns `#Bottom` otherwise, do you know why this would be the case?:
```
  rule arr(L::List, _, D::KItem) [ IDX::Int ] => #if IDX >=Int size(L) #then D #else L[IDX] #fi
```

**Comment by dwightguth** [comment]
ARRAY is an unusual case because it is only actually hooked in the ocaml backend. The actual missing hook here is LIST.make which the Haskell backend ought to be able to easily implement.

**Comment by dwightguth** [comment]
This is because #if is not short circuiting, isn't it? Is there a simple workaround or do we need to bite the bullet and do something more difficult?

**Comment by ttuegel** [comment]
> This is because #if is not short circuiting, isn't it? Is there a simple workaround or do we need to bite the bullet and do something more difficult?

Yes, it's because it's not short-circuiting: `L[IDX]` is not defined. You have two easy options:

1. Write two rules:

```.k
rule arr(L::List, _, D::KItem) [ IDX::Int ] => L[IDX] requires IDX <Int size(L)
rule arr(L::List, _, D::KItem) [ IDX::Int ] => D [owise]
```

2. Add a `_ [ _ ] orDefault _` function for `List` as there is for `Map`, and then we implement that hook in the backend.

**Comment by ehildenb** [comment]
I'm fine with either of @ttuegel 's suggestions, they both seem reasonable, but I lean towadrs (1). I think we should avoid #ite if possible.

It seems that (1) is the quicker option for @gtrepta to test, maybe we can try that.

The problem with `_orDefault_` is that it changes the semantics of `Array` from a bounded-length array to a conceptually infinite array. I guess this is only the case if the user explicitly uses `_orDefault_`, but then they can roll their own version of `_orDefault_` like we do in KEVM with `#lookup`

**Comment by ttuegel** [comment]
> The problem with `_orDefault_` is that it changes the semantics of `Array` from a bounded-length array to a conceptually infinite array.

I don't understand; according to the rule cited by @gtrepta, array indexing is never supposed to fail. :thinking:

**Comment by gtrepta** [comment]
The second parameter in arr( List, Int, KItem ) is supposed to be the length of the array, but it isn't used in the lookup...

**Comment by ehildenb** [comment]
Ah I see, so tehy are conceptually infinite-length arrays anyway.

Then I would say the `_orDefault_` syntax makes sense to me.
