### ISSUE TITLE
Add Strict to our Haskell dialect

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2283]
We should investigate if adding `Strict` to our default extensions helps to solve minor issues as seen e.g. in #2229. (In that issue, laziness does not seem to be the primary problem, but it makes the profiling data weird.)

**Comment by ttuegel** [comment]
The most interesting performance tests are `test/regression-evm` and `test/regression-wasm`. We should add `Strict` one module at a time and test performance with those regression tests.

**Comment by Boarders** [comment]
One useful move I've found here is to test `Strict` on a per module basis and then if it leads to improvement try to track that down with bang patterns the precise location where to avoid thunks. It is useful to do a similar sort of A/B testing with `INLINE` pragmas which are generally unhelpful but can lead to some huge improvements if they lead to the possibility of fusion or unboxing.

**Comment by ttuegel** [comment]
We have found the reverse procedure to be useful: if turning on `Strict` causes a problem, find what needs to be lazy. Too-strict and too-lazy are both a problem, but we have found it's easier to debug too-strict. When the program is too strict, you can usually just walk down the call graph to the offending cost center, but too-lazy often gives "spooky action at a distance".

**Comment by Boarders** [comment]
Ah, that works just as well.
