### ISSUE TITLE
remove unnecessary branches

### ISSUE THREAD

**Issue by grosu** [kframework/kore#23]
Guys, once you merge a branch, please delete it.  We now have 10 branches besides the master.  I know it for sure that some of them are not needed anymore.  Can each of you check and remove your branches if they have been merged?

**Comment by cos** [comment]
We're losing track of them a bit. [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) might help keep things clean. @msaxena2 and I will try it for a while and see how it goes. There's a `develop` branch that should contain all work in progress, and we'll merge to master on releases.

**Comment by grosu** [comment]
@cos and @msaxena2 : guys, can you please clean this repo up of unnecessary branches?

**Comment by msaxena2** [comment]
@ehildenb @lucaspena @daejunpark - Is there any branch that you guys have relevant work in? If not, I think we can safely delete all branches but master and develop. As @cos suggested, we'd like to have 2 branches - develop and master.

**Comment by grosu** [comment]
@msaxena2 , @cos : please do so.  Also, in general, let us move faster.  There is no reason why this issue has been here for 15 days.

**Comment by msaxena2** [comment]
@cos , Please delete the other branches. I cannot since I don't have administrative privileges for this repo.

**Comment by msaxena2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cleanup Branches In Kore](https://trello.com/c/02wKZsya/14-cleanup-branches-in-kore)

**Comment by cos** [comment]
Some time ago I cleaned up my own branches and all branches that had their changes merged. 

I didn't trim further as the other branches have unmerged work that's not mine and I'm not sure if it's still useful. @msaxena2, two of the branches are yours. Could you look into them by any chance?

**Comment by grosu** [comment]
Guys, it is now 3 weeks since I posted this issue.  Get in touch with the people who own those branches and clean them up, please.  Please do it now.  @msaxena2, any reason why you didn't answer @cos' message sent 4 days ago?

**Comment by msaxena2** [comment]
@cos all the work that I need is in develop. You can delete the rest.

**Comment by msaxena2** [comment]
Closing this issue. All branches in Kore except develop and master have been deleted. Just to be on the safer side, I still have a fork with the old branches. If you guys think that some useful work may have been deleted from the main repo, let me know, and we can revive it.
