### ISSUE TITLE
Slow performance of concrete iele tests

### ISSUE THREAD

**Issue by gtrepta** [kframework/kore#2320]
[bug-report.tar.gz](https://github.com/kframework/kore/files/5705397/bug-report.tar.gz)

The above was kompiled and ran with commit `28f43244b` of K, and commit `c7999d7` of iele-semantics. It took over two hours to run.

@ehildenb speculated that the `strict` attribute could have something to do with the performance, as it is being used a lot more in iele than it is in kevm, where the performance is much better.

**Comment by ttuegel** [comment]
I don't see any uses of `strict` alone in KIELE. Using `strict(_)` is fine, and so is `seqstrict(_, ...)`, but `strict` by itself is non-deterministic. That's what would cause performance problems.

I don't know why we would expect KIELE performance to be similar to KEVM.

**Comment by ehildenb** [comment]
Well, we wouldn't expect it to be the same, but I would expect the ratio of LLVM[KEVM] : Haskell[KEVM] to be similar to the LLVM[KIELE] : Haskell[KIELE], which seems to not be the case. The haskell backend has had some tuning work done to it to make it perform better on KEVM, so I expect that there are some performance blind spots that KIELE exercises. KEVM explicitly avoids any of the `strict` variants as much as possible, so I was supposing that maybe this was causing problems with KIELE

**Comment by ttuegel** [comment]
It's certainly possible that strictness is involved! The frontend might be generating more complex rules, for example. I only meant, there is a canonical example where strictness causes a huge penalty, but that doesn't seem to happen here.

**Comment by ttuegel** [comment]
We should get an overview first by running [Kore profiling](https://github.com/kframework/kore/wiki/Profiling#kore-profiling) instead of Haskell profiling.

**Comment by gtrepta** [comment]
[bug-report.tar.gz](https://github.com/kframework/kore/files/5710587/bug-report.tar.gz)

Here is a bug report for a test with a much lower execution time, about 5 minutes.

**Comment by ttuegel** [comment]
I'm going to close this for now because we identified several ways to improve performance significantly. We can open another issue if there are new problems.
