### ISSUE TITLE
Unify Equation arguments at initialization

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2326]
Function definitions are instantiated by unifying their arguments, to allow `\or` patterns on the left-hand side. We can solve the unification problems at initialization to produce a conjunction of equations that can each be applied by simple matching. This would improve performance because our matching algorithm re-orders constraints while our unification algorithm does not.

---

- [ ] Make [`Kore.Equation.Simplification.simplifyEquation`](https://github.com/kframework/kore/blob/770f15d72a8e8f3f364ed666e8c193a198852c88/kore/src/Kore/Equation/Simplification.hs#L70) return a `MultiAnd` of equations.
- [ ] Use `Logic.scatter` instead of [`expectSingleResult`](https://github.com/kframework/kore/blob/770f15d72a8e8f3f364ed666e8c193a198852c88/kore/src/Kore/Equation/Simplification.hs#L104).
- [ ] Also simplify the `argument` (if any) and apply the substitution to the whole `Equation`.

**Comment by ana-pantilie** [comment]
Does this also mean we don't want to simplify with the `argument` [here](https://github.com/kframework/kore/blob/5b29c15315753aa84a064fa391b63ec2d3cdb31f/kore/src/Kore/Equation/Application.hs#L254) anymore?
