### ISSUE TITLE
Display location and klabel when warning about uninterpreted functions

### ISSUE THREAD

**Issue by radumereuta** [kframework/kore#2355]
I get this warning message from the haskell backend, and it's really annoying to try to pinpoint where it comes from:
```
kore-exec: [315764] Warning (WarnFunctionWithoutEvaluators):
    (InfoReachability) while applying claims:
    No evaluators for function symbol:
        Lblconst'LParUndsRParUnds'V'Unds'Bool'Unds'Int{}
```
Is it possible to return the filename and location of where the symbol was declared in the .k file?
If needed, I can modify the front-end to provide the location information.

Also, sometimes I get this error message:
```
kore-exec: [272523] Warning (WarnFunctionWithoutEvaluators):
    (DebugAttemptEquation) while applying equation at /home/radu/work/k/k-distribution/target/release/k/include/kframework/builtin/domains.md:831:8-831:37:
    No evaluators for function symbol:
        Lblconst'LParUndsRParUnds'V'Unds'Bool'Unds'Int{}
```
Not sure how helpful is the location info for the equation you are trying to apply when the warning is about no evaluators.

How to reproduce:
issue: regression-new/itp/nth-ancestor/haskell/
command: kprove ../nth2-spec.k -m V (or just run make)

**Comment by ttuegel** [comment]
The warning message should display the location where the symbol is declared and the `klabel` attribute.
