### ISSUE TITLE
Add location information to bounded model checker warnings

### ISSUE THREAD

**Issue by radumereuta** [kframework/kore#2360]
I found another warning message where there is no location information attached to the warning message.
When running the regression tests, this kind of warnings is very difficult to pinpoint the exact source because tests are run in parallel and the output is combined.
```
radu@radu:~/work/k/k-distribution/tests/regression-new/kbmc$ kbmc --raw-spec unknown-test1-spec-bmc.k   -d . --depth 20
kore-exec: [671965] Warning (LogMessage):
    The pattern does not terminate within the bound. []
#Top
```
How to reproduce:
issue: regression-new/kbmc
command: kbmc --raw-spec unknown-test1-spec-bmc.k   -d . --depth 20 (or just run make)

**Comment by ttuegel** [comment]
The bounded model checker warnings must be promoted to proper log entry types and made to print the location. The location information can be extracted from the claim attributes.
