### ISSUE TITLE
Update to K (and haskell backend) causes KEVM functional proof to fail

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#2361]
I've narrowed down the first failing Haskell backend commit to this one: https://github.com/kframework/kore/pull/2339

The proof in question looks like this:

```
    claim <k> runLemma ( #range(M [ 32 := #buf(1, BUF) ] , 31 , 2) ) => doneLemma ( #range(M, 31, 1) ++ #buf(1, BUF) ) ... </k>
```

But ends in this final state:

```
kore-exec: [3795550] Warning (WarnStuckClaimState):
    (InfoReachability) while checking the implication:
    The proof has reached the final configuration, but the claimed implication is not valid.
Created bug report: kevm-bug-lemmas.tar.gz
  #Ceil ( #buf ( 1 , BUF ) )
#And             
  #Not ( {               
    #range ( M , 31 , 1 ) ++ #buf ( 1 , BUF )
  #Equals            
    #range ( M , 31 , 1 ) ++ b"00"
  } )             
#And            
  <kevm>           
    <k>            
      doneLemma ( #range ( M , 31 , 1 ) ++ b"00" ) ~> _DotVar2 ~> .
    </k>               
```

Bug report attached: 
[kevm-bug-lemmas.tar.gz](https://github.com/kframework/kore/files/5857851/kevm-bug-lemmas.tar.gz)

**Comment by ttuegel** [comment]
@emarzion tracked this down to commit 3d10ab9e8f087a0df81aae567a07ca430fe5114e actually. That makes more sense; this commit changes how function rules are applied.

@ana-pantilie I think this is relevant to the problem you are debugging.

@ehildenb Do you happen to know what lemma should be applied to finish this proof? @ana-pantilie was looking at a similar problem with a much larger proof and I think having trouble finding which rule was not applied correctly.

**Comment by ehildenb** [comment]
I would first expect this rule to apply: https://github.com/kframework/evm-semantics/blob/master/tests/specs/lemmas.k#L297

Then I would expect this rule to apply on the second sub-term that is generated under the `_++_`: https://github.com/kframework/evm-semantics/blob/master/tests/specs/lemmas.k#L302
