### ISSUE TITLE
Remove build date from version information

### ISSUE THREAD

**Issue by emarzion** [kframework/kore#2362]
The time being supplied to `mainVersion` comes from `getZonedTime`, but we should be splicing it in, similar to how the git data is being supplied.  

A quick search suggests that this might work: https://hackage.haskell.org/package/th-nowq

**Comment by ttuegel** [comment]
We should remove the "build date" entirely because it doesn't provide useful information and it ruins any hope of having a reproducible build.

**Comment by ttuegel** [comment]
While we are at it, we should:

1. Note after the commit hash if the repository was clean or dirty using [`gitDirty`](https://hackage.haskell.org/package/gitrev-1.3.1/docs/Development-GitRev.html#v:gitDirty).
2. Provide a way to supply the revision information manually, for the Nix build.
