### ISSUE TITLE
in_keys not evaluated

### ISSUE THREAD

**Issue by virgil-serbanuta** [kframework/kore#2367]
The attached archive is from a proof which fails, and the stuck predicate contains an unevaluated in_keys predicate:
```
  #Not ( {
      true
    #Equals
      I:Usize in_keys ( I:Usize |-> None
      _0 )
    }
```

FWIW, I am using the latest K master and the Haskell backend included in that (commit d8510a03c7d3b560df9bc07947ef802c38d72e77 ). This seems to work with an older K (Haskell backend commit 73b95255df53d54b499b61c370f262ec327842e2 ).

[in_keys.tar.gz](https://github.com/kframework/kore/files/5869348/in_keys.tar.gz)

**Comment by ttuegel** [comment]
I think this might be related to kframework/k#1868. I'd like to retry after that is merged.

**Comment by ana-pantilie** [comment]
I ran this on master and the proof passes, so the issue seems to have been fixed.
