### ISSUE TITLE
Unevaluated function

### ISSUE THREAD

**Issue by virgil-serbanuta** [kframework/kore#2399]
A function with a simple rule stays unevaluated in the following example. In order to minimize this, the example works only in the repl (outside it will fail on a different branch first). This is reproducible with the haskell backend at commit 5014eb9656bb1176fd310420623ce6ce75d1a017 (and also at least one of the earlier ones).

Most changes I tried to make to `tmp.k`, no matter how small, make the problem go away.

tmp.k:
```k
module TMP
  imports BOOL
  imports MAP

  imports INT

  syntax Usize ::= u(Int)

  syntax KItem ::= #splitMap(key:KItem, Map)
  rule  #splitMap(K:KItem, (K |-> V:A _:Map) #as M:Map) => V

  syntax A ::= "a"
  rule _:A => .K
  syntax KItem ::= A

  syntax KItem ::= call(Map, Usize) | end(Map, Usize)
  rule call(M, U:Usize) => (#splitMap(u(10), M) ~> end(M, U))

  syntax Map ::= keysMap(Map)  [function, functional]
  rule keysMap(K:KItem |-> _:KItem M:Map) => K |-> 0 keysMap(M)
    [simplification]

  syntax Bool ::= condition(Map)  [function, functional]
  rule condition(M:Map) => true

  syntax Bool ::= ensuresClaim(numProposers:Usize, userIdToRole:Map)
    [function, functional]
  rule ensuresClaim(u(NumProposers:Int), UserIdToRole:Map)
      => condition(keysMap(UserIdToRole))
endmodule
```

tmp-proof.k:
```k
module TMP-PROOF
  imports TMP

  claim call(_:Map, u(_:Int)) => end(?M:Map, ?U:Usize)
    ensures ensuresClaim(?U, ?M)
endmodule
```

Command line:
```sh
kompile tmp.k --backend haskell && kprove tmp-proof.k --debugger --debug-script kast.kscript
```

Then, inside the repl:
```
step 2
select 2
step 2
select 5
konfig
```

Note the unevaluated `condition ( keysMap ( _2 ) u ( 10 ) |-> 0 )` call and note this rule in tmp.k: `rule condition(M:Map) => true`.

**Comment by ttuegel** [comment]
I think that the backend cannot infer that the argument of `condition` is defined, so it won't apply the rule. You can verify with `--debug-equation`.

**Comment by virgil-serbanuta** [comment]
Ah, you're right, I got confused because things like changing `u(NumProposers:Int)` to `X:Usize` in the `ensuresClaim` rule, or completely removing that argument, make the problem go away for some reason.
