### ISSUE TITLE
Consider using `:rlimit` instead of `:timeout` for deterministic timeouts.

### ISSUE THREAD

**Issue by nishantjr** [kframework/kore#2407]
Whether a proof fails or succeeds due to a timeout depends on the specific hardware being used to run the proof.
This means that proofs that times out on the CI server may work on our machines locally. 
Or worse, may work on a laptop when plugged in to a power source but not otherwise, making debugging difficult.

Z3's `:rlimit` allows setting a "resource limit" in terms of various compute and memory resources used that is deterministic (for a particular version of `z3`). This would make debugging easier.

https://stackoverflow.com/questions/45457131/what-is-the-relation-between-options-rlimit-and-timeout/45458651#45458651

**Comment by ttuegel** [comment]
Thanks for the link! Unfortunately, it seems like `rlimit` terminates the solver process (`timeout` does not), so we would have to completely rewrite our interaction with the solver to take advantage of this.

**Comment by nishantjr** [comment]
I see, that makes sense. Thanks!

**Comment by nishantjr** [comment]
@ttuegel  It looks like `:rlimit` does not terminate the solver, at least on version 4.8.8 and 4.5.1
I looked through the Release notes and Issue tracker for Z3 but wasn't able to find any mentioning the possible regression you found. Even if there is a regression on some version I feel this is a valuable feature to have.

Test for 4.5.1:

```$ cat test.smt 
(set-option :rlimit 30)

(push)
(assert (= (+ 2 2) 4))
(check-sat)

(pop) (push)
(assert (= (+ 2 2) 4))
(assert (= (+ 2 2) 4))
(assert (= (+ 2 2) 4))
(check-sat)
(get-info :reason-unknown)

(pop) (push)
(assert (= (+ 2 2) 4))
(check-sat)

$ z3 test.smt 
sat
unknown
(:reason-unknown "(incomplete (theory arithmetic))")
sat```

This works on https://rise4fun.com/Z3 version 4.5.1

```(set-option :rlimit 9)

(push)
(assert (= (+ 2 2) 4))
(check-sat)

(pop) (push)
(assert (= (+ 2 2) 4))
(assert (= (/ 2 3) 0))
(check-sat)
(get-info :reason-unknown)

(pop) (push)
(assert (= (+ 2 2) 4))
(check-sat)

(get-info :version)```
```sat
unsat
(:reason-unknown "unknown")
sat
(:version "4.5.1 - build hashcode 5714f830b03208d8d47717d22963a4a8395d8364")```

**Comment by andreiburdusa** [comment]
I added the `:rlimit` option but didn't remove `:timeout`. Can this issue be closed?

**Comment by andreiburdusa** [comment]
I added the `:rlimit` option but didn't remove `:timeout`.
