### ISSUE TITLE
kore-exec: --log suppresses output from --debug-equation

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2427]
The option `--log` redirects the log of `kore-exec` from standard error to a named file. When `--debug-equation` is also used, the output from equation debugging is neither redirected nor printed to standard error; it is lost entirely.

**Comment by andreiburdusa** [comment]
I'm not able to reproduce this bug. I ran `krun` with the flag `--dry-run` in the `kprove` file, then added `--debug-equation _+Int_ --log logFile.txt` to the printed command.
```
andrei@q:~/kore/test/kprove$ /home/andrei/kore/.build/kore/bin/kore-exec /home/andrei/kore/test/kprove/./.kprove-2021-03-09-13-50-35-721-129eb875-d481-476b-94b2-a0f803a3490a/vdefinition.kore --module VERIFICATION --prove /home/andrei/kore/test/kprove/./.kprove-2021-03-09-13-50-35-721-129eb875-d481-476b-94b2-a0f803a3490a/spec.kore --spec-module SUM-SPEC --debug-equation _+Int_ --log logFile.txt
/* D Sfa */ \top{R}()
```
The file `logFile.txt` was created and it looks right.
[logFile.txt](https://github.com/kframework/kore/files/6108313/logFile.txt)
