### ISSUE TITLE
SideCondition.andCondition is unexpectedly quadratic

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2454]
The regression involves `SideCondition.fromCondition` and `SideCondition.andCondition`.

**Comment by ttuegel** [comment]
The particular test is the `sum-to-n-spec.k` in `test/regression-evm'.

**Comment by ttuegel** [comment]
This likely first appeared in c4278195b.

**Comment by ttuegel** [comment]
The problem in [`andCondition`](https://github.com/kframework/kore/blob/858004428c6e9ff4a2e5733aee3b4d8909a3e13f/kore/src/Kore/Internal/SideCondition.hs#L276) seems to be related to the fact that we take the whole `SideCondition` apart and simplify it again. We can't naively combine the fields of `SideCondition` because that would violate invariants, but we should try to combine them in a way that doesn't duplicate work.

**Comment by ttuegel** [comment]
Fixed in #2447.

**Comment by ttuegel** [comment]
This was actually not fixed. The problem is related to the way `SideCondition.andCondition` disassembles the existing `SideCondition`, combined with the way that `simplifyPredicates` breaks apart a `Predicate` and constructs a new `SideCondition` at every step; the effect is that `andCondition` is used in a quadratic way. The problem is not with hashing per se, that is just a symptom of it.

**Comment by ttuegel** [comment]
We have been brainstorming ways to improve the performance of `andCondition`. Essentially, we would like the cost of adding each new clause to be constant (with respect to the size of the existing `SideCondition`), while maintaining the invariants of a `SideCondition`.

One option, suggested by @ana-pantilie, is to use a dynamic topological sort algorithm. Such algorithm can keep a graph topologically sorted while adding and deleting edges and vertices. We already use a topological sort to normalize `Substitution`; we would be normalizing the generalized substitutions under `SideCondition` the same way. We would need to use a dynamic algorithm because edges can be added by applying generalized substitutions. (Applying substitutions for variables only cannot add edges to the graph, so we have not dealt with this before.)

Another option is to use a static topological sort algorithm, but over-approximate dependencies between nodes, so that we never need to add edges to the graph. Exact dependencies appear when the left-hand side of any generalized substitution appears as a sub-term of another substitution. There are many ways to over-approximate dependencies, but one way is to consider merely the symbols present in each term, and not the exact sub-terms. The over-approximate dependencies could create false cycles in the graph, but this is not a fatal problem because all false cycles can be resolved by repeated substitution, and all true cycles can be reduced to a single generalized substitution.

**Comment by ttuegel** [comment]
I left a [comment](https://github.com/kframework/kore/pull/2551#issuecomment-821229362) with a troublesome example, which I will reproduce here:

Suppose we already have the side condition:

```
f(g(a)) = h(a)
f(b) = h(b)
```

and then we want to add:

```
g(a) = b
```

**Comment by ttuegel** [comment]
Actually, I have thought of an algorithm that is reasonably efficient and can be made incremental.

We begin with a (denormalized) set of generalized substitutions:

```
Lᵢ :-> Rᵢ  -- Lᵢ and Rᵢ are arbitrary terms, hence "generalized"
```

We will topologically sort these substitutions so that they can be applied linearly.
Connect the pairs in a graph with edges

```
i -> j  when Lᵢ ∈ Rⱼ ∨ subterms(Rⱼ) or Lᵢ ∈ subterms(Lⱼ) or Rⱼ ∈ subterms(Lᵢ)
```

Here, `subterms(_)` denotes _strictly_ the subterms, not including the term itself. The (static!) topological sort of this graph gives the correct order for the generalized substitutions to be applied linearly. We can remove any cycles from the graph, regarding them as side conditions rather than generalized substitutions.

**Comment by ttuegel** [comment]
I forgot to say, this can be made incremental by observing that, to add a substitution to the normalized set, we only need to consider the substitutions that intersect the new one, so: Calculate edges in and out of the new pair. If it creates a loop, set the new pair aside. Otherwise, apply all relevant substitutions to it. Then, apply it everywhere that it is relevant.

**Comment by ttuegel** [comment]
At the meeting this morning, we discussed the incremental algorithm for normalizing a set a generalized substitutions, and I realized it's not quite clear from my comments above how to do that. Here is the procedure, presented inductively.

### Definitions

A **generalized substitution** is a pair `Lᵢ :-> Rᵢ` where `Lᵢ` and `Rᵢ` are arbitrary terms (hence, "generalized"). Logically, this is equivalent to the clause `Lᵢ = Rᵢ`, but we have added an orientation. We will further restrict ourselves to cases where `Lᵢ` is a function pattern (as opposed to a constructor or the like).

A set of generalized substitutions is **normalized** if the `Lᵢ` do not appear in any other clause of the set, that is:

```
∀ i , j. Lᵢ ∉ terms(Rⱼ)
  and
∀ i ≠ j. Lᵢ ∉ terms(Lⱼ)
```

where `terms(_)` refers to a term and all its sub-terms.

A clause or set of clauses is **denormalized** if it cannot be made into a normalized set of clauses by applying substitutions, or if the clause(s) do(es) not meet the criteria to be a generalized substitution. That is, "denormalized clause" can refer to arbitrary predicates.

**Comment by ana-pantilie** [comment]
This is my first attempt at piecing together an algorithm for our issue. It might be wrong, or make wrong assumptions, or it might actually be horribly inefficient, so I need to double check it with a rested mind.

Initial remarks:
- In the following comment, substitution means generalized substitution.
- Removing an edge from the graph doesn't change its topological sort.
- As described in detail in [A Dynamic Topological Sort Algorithm for Directed Acyclic Graphs](https://www.doc.ic.ac.uk/~phjk/Publications/DynamicTopoSortAlg-JEA-07.pdf) (Algorithm PK), inserting an edge `x -> y` will only require reordering some of the nodes in the affected region of the graph. This set of nodes is constructed from the nodes which are reachable from `y` and the ones from which `x` is reachable. This algorithm also detects if the newly added edge introduces any cycles.
- If `p` and `q` are terms of the form `LHS = RHS`, a dependency (edge) `p -> q` is created by the LHS of `p` being a subterm (including the term itself) of the LHS of `q`.

(Rough) algorithm overview:
1. We start with a normalized set of substitutions, meaning its associated dependency graph doesn't contain any edges (all the dependencies have been previously resolved). This means we can do a static topological sort when adding a new set of (de-normalized) substitutions. We compute the new set of dependencies, and apply the topological sort. This results in an ordered set of substitutions. 
2. We traverse the set, applying each substitution one-by-one. The method for applying substitutions is the following:
     - apply substitution
     - remove associated edge from graph and modify the term accordingly
     - check for new dependencies: if any new dependencies appear, add each edge to the graph doing a dynamic topological sort
3. Resume applying substitutions: if the topological sort didn't change go to the next substitution, if it did change go to the "left-most change" and resume.

Performance-wise, one part I'm not sure about is that we would have to check for new dependencies every time we apply a substitution. How expensive is this check? In general, do the operations needed by this algorithm have considerable overhead?

**Comment by ttuegel** [comment]
Any approach that we take here needs an efficient way to calculate dependencies between generalized substitutions. For ordinary substitutions, we track the free variables of each term in the pattern attributes. To handle generalized substitutions, I suggest we track the free sub-terms in the pattern attributes. We need to study the feasibility of this approach; will tracking the sub-terms degrade performance much? Before we continue, we should try adding a `subterms :: HashSet (TermLike variable)` to the pattern attributes. We would not use this field anywhere (yet), but we can determine the cost of keeping it around.

**Comment by ttuegel** [comment]
We have determined that tracking subterms as an attribute of `TermLike` is not feasible because it creates circular dependencies.

We also examined `Kore.Step.Simplification.Condition.simplify` and `simplifyPredicates` and found that these functions do not really work together as intended. We believe we can improve performance by simplifying this interaction, with some changes to the behavior of `SideCondition`.

### `SideCondition`

We will make it possible to construct a `SideCondition` with only one of the fields populated. We will add a separate smart constructor for each field. We will combine `SideCondition`s by simply combining their fields, instead of using `simplifyConjunctionByAssumption`.

### `simplifyPredicates`

We will change `simplifyPredicates` to have this type:

``` hs
simplifyPredicates :: SideCondition -> MultiAnd Predicate -> simplifier (MultiAnd Predicate)
```

I have omitted some obvious type parameters and constraints, for brevity. The new function will work like this:

1. Apply `simplifyConjunctionByAssumption`, keeping only the resulting `MultiAnd Predicate`.
2. Using the previous result, simplify each predicate using the others as a side condition. This step will be detailed below.
3. Loop until stable; that is: until either 1 or 2 does not change the predicates, but run both at least once.

To simplify the individual predicates,

1. Pair each predicate with the `SideCondition` constructed from the remaining unsimplified predicates. To maximize sharing, this should be done by `zip predicates $ scanr _ SideCondition.top $ tail predicates`.
2. Initialize a state monad with the original `SideCondition`. This is the simplified side condition.
3. Simplify each predicate by combining the unsimplified side condition with the simplified side condition. Add the result to the simplified side condition as an assumption for function evaluation only.
