### ISSUE TITLE
Create a tool to check function definitions

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2472]
We will create a tool tentatively called `kore-check-functions` which will check the following properties of function definitions:

1. For every equation in a function definition, the right-hand side of the equation is a function pattern.
2. For every pair of equations in a function definition, the equations cannot match the same term.

Recall the [interpretation](https://github.com/kframework/kore/blob/master/design-decisions/2020-05-02-function-rules.md#solution) of function rules in Kore. We will use that notation in the following.

To check the first property is very simple, so we will use that task as an opportunity to set up infrastructure: taking the definition as input, validating it, getting the list of equations, etc.

To check the second property, we will instantiate the pair of equations `E₁` and `E₂` at the same term e.g. `fun({X})` and evaluate

```
Pre₁({Y}) ∧ Args₁({X}, {Y}) ∧ Prio₁({X}) ∧ Pre₂({Y}) ∧ Args₂({X}, {Y}) ∧ Prio₂({X})
```

If this predicate is unsatisfiable, then the equations can never match the same term.

**Comment by ana-pantilie** [comment]
@dopamane For the second part, remember that equations are grouped according to the symbol at the top. Let `[E1, E2, ..., En]` be one of these groups, we should generate all unordered pairs `(Ei, Ej)` and evaluate the predicate in the description. We need to check that all of the results are `\\bottom`, for every group of equations.
