### ISSUE TITLE
Control function evaluation from a high level

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2520]
@virgil-serbanuta pointed out to me that, because we never need to re-evaluate functions unless the side condition changes, we don't actually need to keep the side condition in the simplification marker that annotates every node in the syntax tree. The side condition can only change when we apply a rewrite rule or a claim; at all other times, we don't need to evaluate functions. Even then, we only need to evaluate functions if the side condition changes. Actually, we also need to evaluate functions on the right-hand side of the current claim when the condition on the left-hand side changes. For that, the prover can track the previous claim and simplify the right-hand side after rewriting.

First, we should implement a prototype of this. We will add a field to `SideCondition` which is simply a `Bool` indicating if we should or should not evaluate functions. We will remove the checks from the `TermLike` simplifier that look at the `isSimplified` flag. We will add a check to the function evaluator that looks at the field in `SideCondition`. Then, we should be able to remove the `Simplified` attribute from patterns.

If the prototype is successful, I propose we make the function evaluator configurable in #2474 instead of passing flags around in the `SideCondition` as a hack.

**Comment by ttuegel** [comment]
> First, we should implement a prototype of this. We will add a field to `SideCondition` which is simply a `Bool` indicating if we should or should not evaluate functions. We will remove the checks from the `TermLike` simplifier that look at the `isSimplified` flag. We will add a check to the function evaluator that looks at the field in `SideCondition`. Then, we should be able to remove the `Simplified` attribute from patterns.

The implementation actually needs to be slightly more sophisticated: we should collect all the sub-terms of the current configuration, and we should not attempt to re-simplify them. This should wait until the first part of #2454 is done.

**Comment by virgil-serbanuta** [comment]
I'm sorry, I'm re-reading this after my vacation, after losing a lot of context - what do you mean by "The side condition can only change when we apply a rewrite rule or a claim"?

My first reading was that it can't happen during simplification, but that would not be completely true since simplification rules can have `ensures` clauses (e.g. this one https://github.com/kframework/k/blame/master/k-distribution/include/kframework/builtin/domains.md#L433 ).

**Comment by ttuegel** [comment]
For the `Simplify` step, we will not make any assumptions about what functions are evaluated. For `ApplyClaims` and `ApplyAxioms`, we will assume that the left-hand side of the current claim (goal) is fully simplified and add any non-constructor-like function terms to the metadata field in the `SideCondition`.

In [`evaluateApplicationFunctions`](https://github.com/kframework/kore/blob/c2ce560a2e36f443948eb9a4e5072e5c9b76ae4c/kore/src/Kore/Step/Simplification/Application.hs#L124), we can check if the function term is in the metadata field. If it is, we will just mark it simplified and return it. Otherwise, we will continue with function evaluation as we do already.

**Comment by ttuegel** [comment]
As an intermediate step toward removing the `Simplified` attribute, we can remove the `SideCondition` argument it stores, in favor of the changes described above. That way, we get a lot of the performance benefit of removing the attribute without all of the behavior changes at once. We would just have to reset the `Simplified` status of any conditionally-simplified attributes after each rewrite step.
