### ISSUE TITLE
Backend crashed during rewriting with exit code 1

### ISSUE THREAD

**Issue by kheradmand** [kframework/kore#2549]
```
...
kore-exec: [780336716] Error (ErrorException):
    user error (Unexpected result from the SMT solver:
      Command: (push 1 )
      Expected: success
      Result: (error "line 21658 column 8: canceled" )
    )
Created bug report: kore-exec.tar.gz
[Error] Critical: Backend crashed during rewriting with exit code 1
```

[kore-exec.tar.gz](https://github.com/kframework/kore/files/6310049/kore-exec.tar.gz)

K version (installed from Homebrew)
```
 krun --version
RV-K version 1.0-SNAPSHOT
Git revision: 
Git branch: UNKNOWN_BRANCH
Build date: Thu Mar 25 04:00:09 IRDT 2021
```

Source code:
https://github.com/kframework/p4-semantics/blob/master/src/cli/cli-symbolic.k

Command to kompile:
```
kompile --backend haskell cli-symbolic.k --syntax-module CLI-SYMBOLIC-SYNTAX --main-module CLI-SYMBOLIC-SEMANTICS
```

Command to run:
```
krun                                                   \
     --directory src/cli                                                \
     -cPGM="`cat a.p4`"                                                 \
     -pPGM="kast -s P4Program -m P4-SYNTAX --directory src/cli -o kore" \
     -cCLI="`cat b.cli`"                                                \
     -pCLI="kast -s CLIPgm -m CLI-SYMBOLIC-SYNTAX --directory src/cli -o kore"   \
      --verbose --save-temps --depth 136                                                 \
```

Input files:
[a.p4](https://github.com/kframework/p4-semantics/blob/master/test/semantics/basic_routing/basic_routing.p4)

```
b.cli:
@sympacket
```

It does not crash if depth is <136.

**Comment by kheradmand** [comment]
Increasing ` --smt-timeout` eliminates the crash, so probably the crash is related to handling SMT query timeout.

**Comment by ttuegel** [comment]
The result from the SMT solver indicates that the solver crashed because it didn't handle the timeout correctly. There is really nothing that the backend can do, other than report that error and terminate.
