### ISSUE TITLE
make test-k randomly breaks in new installation

### ISSUE THREAD

**Issue by radumereuta** [kframework/kore#2557]
I tried running `make test-k` for the first time today and some tests fail.
Example:
```
make[2]: Entering directory '/home/radu/work/k/haskell-backend/src/main/native/haskell-backend/test/tiny'
diff -u test-save-partial-proof.sh.out.golden test-save-partial-proof.sh.out || ( mv test-save-partial-proof.sh.out test-save-partial-proof.sh.out.fail && false )
--- test-save-partial-proof.sh.out.golden	2021-03-09 15:19:27.569913172 +0200
+++ test-save-partial-proof.sh.out	2021-04-16 23:00:27.268066859 +0300
@@ -1,4 +1 @@
-12c12
-<                     /* Fl Fn D Sfa Cl */ Lbla'Unds'TINY'Unds'S{}()
----
->                     /* Fl Fn D Sfa Cl */ Lblb'Unds'TINY'Unds'S{}()
+Error: Expected main module name not found in partial-a-to-c.kore.
make[2]: *** [/home/radu/work/k/haskell-backend/src/main/native/haskell-backend/test/tiny/../include.mk:148: test-save-partial-proof.sh.out] Error 1
make[2]: Leaving directory '/home/radu/work/k/haskell-backend/src/main/native/haskell-backend/test/tiny'
```
A few others as well. If I go into that directory and run make again, the tests pass. On other tests, they didn't.

@ttuegel suggested running the same script used by CI `./scripts/integration-k.sh`. This time all tests passed.
One difference I noticed is the script exports some paths which I'm pretty sure I haven't set up.

Other info: I was trying to test some changes to the front end, so I used my own version of kompile, which was set in PATH. So I didn't use the docker image as the documentation suggested.

**Comment by ttuegel** [comment]
The `integration-k.sh` script is just supposed to be an optimization: it sets some variables once so that they aren't repeatedly set by each recursive call to `make`. But it seems that the settings in the `Makefile` were lost at some point.

**Comment by ttuegel** [comment]
We did find one issue with the master branch, but otherwise we weren't able to reproduce this problem.
