### ISSUE TITLE
Overhaul predicate simplifier

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2570]
This issue is the first part of addressing the issues raised in #2400. See also: #2566.

We will move `Condition.simplifyPredicate` to its own module and implement a `Predicate.simplify` similar to `TermLike.simplify`. It must not call `simplifyCondition` or `simplifyTermLike`. `Predicate.simplify` will simplify a `Predicate` from the bottom up; at each level, it will iterate until the predicate does not change.

Questions:

- What should be the return type of `Predicate.simplify`? Two reasonable-seeming options are a disjunction of `Condition`s, or a disjunction of `MultiAnd (Predicate _)`. In the former case, the `Condition` will not be simplified. What does the condition simplifier expect?

**Comment by ttuegel** [comment]
@ana-pantilie I would appreciate your thoughts on this.

**Comment by ttuegel** [comment]
As for the return type of `Predicate.simplify`, I'm inclined to return the disjunction of `MultiAnd (Predicate _)` for these reasons:

- I can't think of any reason the `Predicate` simplifier shouldn't return something that isn't basically a predicate.
- The implementation will be simpler.
- The `Condition` simplifier that calls `Predicate.simplify` can easily break down a `MultiAnd (Predicate _)` into a `Condition _`.

**Comment by ana-pantilie** [comment]
I think that from the point of view of the `Condition` simplifier, a disjunction of `MultiAnd (Predicate ..)` would be fine. We already go back and forth between `Condition` and `MultiAnd` there.

One thing is that the ML pattern simplifiers return disjunctions of `Pattern`s or of `Condition`s, so we'd still have to turn that into a `MultiAnd (Predicate _)` at the end, unless there's something nicer we could do.

**Comment by ana-pantilie** [comment]
Equals, In -> similar to Ceil
Floor -> just desugar it to Not Ceil Not
Forall -> just desugar it, unless there's only one predicate under it (inside the Or collection)

**Comment by ttuegel** [comment]
`\equals(_, _)` and `\in(_, _)` have simplifiers in `Kore.Step.Simplification`. We can use them directly as long as they already return `OrCondition`. If they don't, they could easily be changed to do it. (After we remove the old `TermLike` simplifier, we need to make these simplifiers be non-recursive.)

I think `\floor(_)` and `\forall(_, _)` need to be desugared usually. Simplifying their children will return a `MultiOr`, and these don't distribute over `\or(_, _)` the way their counterparts `\ceil(_)` and `\exists(_, _)` do. The exception to this rule is that, if simplifying their children produces only one result in the `MultiOr`, then for simplicity we probably shouldn't desugar. These do distribute over `\and(_, _)`, that is:

```
\floor(\and(_, _)) = \and(\floor(_, _))
\forall(_, \and(_, _)) = \and(\forall(_, _), \forall(_, _))
```

so we should probably do that when it appears.
