### ISSUE TITLE
Unsatisfiable state containing `==String` not pruned by backend

### ISSUE THREAD

**Issue by sskeirik** [kframework/kore#2586]
I have a proof which generates the following conjunction in its path condition as it executes:

```
\and{SortGeneratedTopCell{}}(
  \not{SortGeneratedTopCell{}}(\equals{SortString{}, SortGeneratedTopCell{}}(VarSender0:SortString{},VarTokenAddress0:SortString{})),
\equals{SortBool{}, SortGeneratedTopCell{}}(\dv{SortBool{}}("true"),
  Lbl'UndsEqlsEqls'String'UndsUnds'STRING-COMMON'Unds'Bool'Unds'String'Unds'String{}(VarSender0:SortString{},VarTokenAddress0:SortString{})))
)
```

I expect that the backend will prune this state, but currently, this functionality is not implemented.

Please note that this check is a blocker for us on our dexter proof.

**Comment by ttuegel** [comment]
We need to determine why [`Kore.Builtin.String.unifyStringEq`](https://github.com/kframework/kore/blob/cb2c54e82996963595e1d9f25a592351a07db6f1/kore/src/Kore/Builtin/String.hs#L459) is not applied to the second clause.

**Comment by ana-pantilie** [comment]
Could you please supply a way to reproduce this issue?

**Comment by sskeirik** [comment]
Repro steps:

```sh
git clone https://github.com/runtimeverification/michelson-semantics.git
git checkout string-equality-test
make deps-k dexter-prove
```

Or if you want I can paste the backend output. What is the flag to cause `kore-exec` to dump its final state?

**Comment by MirceaS** [comment]
@sskeirik I get this error when I try to reproduce the issue with your steps:
```
cd ext/k && mvn package -DskipTests -U -Dproject.build.type=FastBuild
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.076 s
[INFO] Finished at: 2021-05-06T17:00:32+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/mirceas/work/RV/michelson-semantics/ext/k). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
make: *** [Makefile:94: ext/k/k-distribution/target/release/k/lib/java/kernel-1.0-SNAPSHOT.jar] Error 1
```

**Comment by sskeirik** [comment]
I missed a `git submodule update --init --recursive` originally and that added that back in my comment later. Please try that. Thanks. @MirceaS

**Comment by ehildenb** [comment]
From the frontend, you can do `--haskell-backend-command "kore-exec --bug-report YOUR_NAME"` to get the haskell bakcend to generate the correct report.

**Comment by sskeirik** [comment]
Here is a bug report that I created from the branch: [2586.tar.gz](https://github.com/kframework/kore/files/6462434/2586.tar.gz)

It should be reproducible using the following instructions:

```
git clone https://github.com/runtimeverification/michelson-semantics.git
git checkout string-equality-test
git submodule update --init --recursive
make deps-k
make dexter-prove KPROVE_OPTIONS='--haskell-backend-command "kore-exec --bug-report 2586"'
```

**Comment by sskeirik** [comment]
Adding the following simplification rule appears to solve many issues I have with string equality. Is it sound and does it make sense? @ttuegel 
 
```
rule X::String ==String Y::String => false
  requires #Not ( { X #Equals Y } ) [anywhere,simplification]
```

**Comment by sskeirik** [comment]
@MirceaS @ttuegel  I would appreciate you looking at the lemma above and also at the bug report I created. This issue is blocking us on a proof for a client.

**Comment by ttuegel** [comment]
@sskeirik The rule is sound. The `anywhere` attribute doesn't do anything, because this is not a constructor rule. That is the same as the rule I cited above which is implemented internally by the backend. We will investigate why that is not effective, but it sounds like you have a workaround for your specific issue.
