### ISSUE TITLE
Add more regression tests from evm-semantics

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2592]
We should look at what tests are run in the evm-semantics repository and import some of them to our regression tests. This will also improve performance regression testing.

**Comment by ana-pantilie** [comment]
@emarzion I think we can start with adding one of each type of test from this issue: https://github.com/kframework/kore/issues/2508. They're tests which have been (and might still be) impacted by performance regressions in the past, so I think they're good candidates for having them run on our CI as well.

I was thinking something like:
```
tests/specs/functional/lemmas-spec.k 
tests/specs/benchmarks/storagevar03-spec.k
tests/specs/erc20/ds/totalSupply-spec.k
```

I think we should make sure they run under ~5m. If any of these are too slow, we can try to replace them with others from the same category (if `tests/specs/erc20/ds/totalSupply-spec.k` is too slow but `tests/specs/erc20/hkg/totalSupply-spec.k` isn't, for example).
