### ISSUE TITLE
Failing to simplify equality

### ISSUE THREAD

**Issue by hjorthjort** [kframework/kore#2595]
At the end of execution, I have the following in my path conditions:

```
#And
  {
    true          
  #Equals                                                                                                                                                                     
notBool ( Source:Address ~> . ) ==K ( Source:Address ~> . ) orBool ( ( KnownAddresses [ TokenAddress:Address ] ~> . ) ==K ( #Contract ( _A , T ) ~> . ) andBool notBool ( T:Type ~> . ) ==K ( pair .AnnotationList address .AnnotationList contract .AnnotationList nat .AnnotationList ~> . ) )
  }  
```

Basically I would want the second term of the `orBool` clause to be true (I think that would make my proof go through), and it seems clear the prover should be able to deduce that the first term is false. I don't know how I would even give it a further hint. Any ideas?

[bug-report-name.tar.gz](https://github.com/kframework/kore/files/6427555/bug-report-name.tar.gz)

**Comment by ttuegel** [comment]
@hjorthjort Could you please also point us to the K source, so that we can try to minimize the example if necessary?

**Comment by ttuegel** [comment]
I think we have code that should trivially simplify `( Source:Address ~> . ) ==K ( Source:Address ~> . )` because the patterns are literally equal. It is possible that code is not activated because the patterns are also symbolic. We should investigate why it is not activated.

**Comment by andreiburdusa** [comment]
I'm not able to reproduce the error (anymore) using the bug report because I get
```
kore-exec: [1800990] Error (ErrorVerify):
    Error:
      module 'KSEQ':
      axiom declaration:
      (vdefinition.kore 19:16):
        Expected variable, but found:
            /* Fl Fn D Sfa Cl */ dotk{}()
        The equation that the above occurs in is:
    ...
```
This is probably related to #2585.

And when I clone the repository from the [previous comment](https://github.com/kframework/kore/issues/2595#issuecomment-833510980) link and run the command I get  `#Top`.

**Comment by hjorthjort** [comment]
@andreiburdusa Did you checkout the branch linked, or did you run on `master`? Because on the branch linked, called `==k-simplification-bug`, I'm still getting this error.

**Comment by andreiburdusa** [comment]
> @andreiburdusa Did you checkout the branch linked, or did you run on `master`? Because on the branch linked, called `==k-simplification-bug`, I'm still getting this error.

That was the problem indeed. I cloned the repository but didn't checkout the branch.

**Comment by ttuegel** [comment]
We can handle this by separating the code [here](https://github.com/kframework/kore/blob/dfbaeed02fb9327a08089969c160d5931118ed89/kore/src/Kore/Builtin/KEqual.hs#L157) for `==K` and `=/=K`. These functions can always return `true` (or `false` respectively) when the input patterns are exactly equal, even if the patterns are not constructor-like.
