### ISSUE TITLE
Allow formatting log options from the command-line

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#2596]
From: https://runtimeverification.slack.com/archives/CC360GUTG/p1620225947427000

I'd like to be able to see (in the log to stderr) the rules that are being applied, and the timestamps associated with them. Something like:

```
0001 000000403 evm.md 41:4-42:8
0002 000000890 ktoken-verification.k 453:2-454:18
...
STEP_NUMBER TIMESTAMP SEMANTIC_RULE_LOCATION_INFORMATION
```

Maybe this could be achieved using `--log-format=oneline`, which then provides a one-line format for each log entry (so omit kore output, and any extra debug info beyond just timestamps and rule source location, for example).

**Comment by ttuegel** [comment]
1. `shortDoc` should be called `contextDoc`, because it's completely unclear what it's used for.
2. Add `oneLineDoc :: entry -> Maybe (Pretty.Doc ann)` that prints a one-line entry.
3. Modify `makeKoreLogger` to take a format option, and print using the appropriate format.
