### ISSUE TITLE
display all steps

### ISSUE THREAD

**Issue by gelisam** [kframework/kore#2617]
I currently run `krun` with `--depth=0`, `--depth=1`, ..., `--depth=N` to see each step of the execution. This takes about a second each time, regardless of the depth, which indicates that most of the cost is in the startup time and not in the execution itself (at least for my small examples). In order to display step N, the execution must go through each of the previous steps, so I assume it would be moderately easy to print all N steps in a single execution? This would allow me to see all the steps in 1 second rather than N, which would be a huge quality-of-life improvement for me. Thanks!

**Comment by ehildenb** [comment]
Which backend are you using? If it's the LLVM (default), or Haskell, you can use `--debugger` to step through the execution interactively.

If it's the Java backend, you can use the state-logger and KLab to do the same.

**Comment by gelisam** [comment]
Thanks! I'm currently using the Haskell backend, but I could switch to a different one if that's easier. So far, it doesn't look easy at all!

In particular, I see that the `--debugger` flag drops me in C's `gdb` debugger, not Haskell's `ghci` debugger, so I don't think I can step through the Haskell code from there. But that gave me an idea: I can use `--dry-run` to get the `kore-exec` command, and then run ghci on that command in order to step through the Haskell code interactively. Unfortunately, that didn't go too well:

```
$ stack ghci kore:lib kore:exe:kore-exec
λ> :break exec
Breakpoint 0 activated at .../kore/src/Kore/Exec.hs:(226,9)-(271,40)
λ> :main .../lambda-kompiled/definition.kore --module LAMBDA --pattern .../.krun-2021-05-11-21-17-03-wDoU3VTzhX/tmp.in.l8PtOjsP0i --depth 1
Stopped in Kore.Exec.exec, .../kore/src/Kore/Exec.hs:(226,9)-(271,40)
<interactive>: internal error: allocation of 1673264 bytes too large (GHC should have complained at compile-time)
    (GHC version 8.10.4 for x86_64_apple_darwin)
    Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
Abort trap: 6
```

The next thing I plan to try is to tweak the LogicT computation to return the list of states it stepped through instead of just the final state.

**Comment by ttuegel** [comment]
> I see that the `--debugger` flag drops me in C's `gdb` debugger, not Haskell's `ghci` debugger,

You are using the LLVM backend, not the Haskell backend. Although, using `--debugger` will not get you `ghci`, but rather our own debugger for Kore.

If you are using `krun`, you can pass the `--search-all` to see all the states, though they will all be printed at once and not incrementally.
