### ISSUE TITLE
Do not convert OrPattern to TermLike in Rewrites simplifier

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2623]
The `Rewrites` simplifier shall not convert `OrPattern`s into `TermLike`s. If necessary, the `Rewrites` alias should be de-sugared instead.

**Comment by ttuegel** [comment]
Basically, don't call `toTermLike` [here](https://github.com/kframework/kore/blob/dfbaeed02fb9327a08089969c160d5931118ed89/kore/src/Kore/Step/Simplification/Rewrites.hs#L74).

**Comment by ana-pantilie** [comment]
I think I have a vague recollection of what we discussed about this issue, that we basically shouldn't ever get to simplifying `\\rewrites`. So I believe the next step here would be to remove the `Rewrites` simplifier entirely and just not simplify `Rewrites` in the term simplifier (maybe call `doNotSimplify` like [here](https://github.com/kframework/kore/blob/dfbaeed02fb9327a08089969c160d5931118ed89/kore/src/Kore/Step/Simplification/TermLike.hs#L371)?). @MirceaS @ttuegel what do you think? Is this what was discussed?
