### ISSUE TITLE
Fix failing KWASM regression test

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2624]
A regression test is [failing](https://github.com/kframework/kore/pull/2616/checks?check_run_id=2569294736) after update, but there haven't been any relevant changes to the semantics or the backend. It is likely due to changes in the test harness, i.e. we are now running that proof from the wasm-semantics Makefile.

**Comment by ttuegel** [comment]
I just checked [wasm-semantics](https://github.com/kframework/wasm-semantics) and it is up-to-date with the latest frontend and backend releases. Therefore, the problem must be with the test harness. @MirceaS please do not debug this further, I need to take this issue elsewhere.

**Comment by ana-pantilie** [comment]
https://github.com/kframework/kore/blob/5fddbb087dedd928b08414a23bca6c13dd672d59/scripts/generate-regression-tests.sh#L92

**Comment by ttuegel** [comment]
Unless we can make progress on a solution here very soon, we should just switch to running the regression tests from a clone of the upstream repositories, invoking the frontend every time.

**Comment by ana-pantilie** [comment]
I had a similar discussion with @ehildenb on this topic. There's one problem with doing that: for tests where the expected output is a kore pattern (not `\\top`), if the backend needs to change that output we won't be able to update the backend until the downstream project updates its output, and this will turn into a circular dependency. So we'd need a solution for that, like specifying the branch of downstream project to run the tests on or something.

**Comment by ana-pantilie** [comment]
> So we'd need a solution for that, like specifying the branch of downstream project to run the tests on or something.
@ttuegel suggests [feature flags](https://www.martinfowler.com/articles/feature-toggles.html) would solve this issue and give us better control.

We discussed looking into this issue one last time, since cloning the repositories would require running the regression tests only on master builds due to the increased run time.
