### ISSUE TITLE
Does Z3 support rules with ensures?

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2625]
See: https://runtimeverification.slack.com/archives/CC360GUTG/p1620932331011900

**Comment by ttuegel** [comment]
We should check with the `--solver-transcript FILENAME` option, to make sure that the lemma with an `ensures` clause is sent to the solver the way we expect.

**Comment by andreiburdusa** [comment]
> We should check with the `--solver-transcript FILENAME` option, to make sure that the lemma with an `ensures` clause is sent to the solver the way we expect.

I replaced
```
rule test(X) => X >Int 5 [simplification, concrete, smt-lemma]
```
in `test/smt-lemma/smt-lemma.k` with
```
  rule test(X) => X >Int 5 ensures X <Int X +Int 1 andBool X <=Int X
    [simplification, concrete, smt-lemma]
```

In the solver transcript file, the line
```
(assert (forall ((<0> Int ) ) (= (smt_test <0> ) (> <0> 5 ) ) ) )
```
was replaced with
```
(assert (forall ((<0> Int ) ) (and (= (smt_test <0> ) (> <0> 5 ) ) (= (and (< <0> (+ <0> 1 ) ) (<= <0> <0> ) ) true ) ) ) )
```

**Comment by ttuegel** [comment]
Can you update [this section](https://github.com/kframework/k/blob/master/pending-documentation.md#smt-lemma-lemma-and-trusted-attributes) of the frontend documentation? It says that side conditions are not supported for `smt-lemma` rules, but that isn't true.
