### ISSUE TITLE
Remove explainBottom

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2639]
The function `explainBottom` is a no-op, and it should be removed. We should replace it with a log entry that captures the match data, after #2396.

**Comment by ana-pantilie** [comment]
We should turn `explainBottom` into a log entry instead.

In kore-repl we should temporarily turn on this log entry [here](https://github.com/kframework/kore/blob/77f99c0e6c8ad19f06c7f4c34e64c838bdf91cb0/kore/src/Kore/Repl/State.hs#L622).

**Comment by ana-pantilie** [comment]
Replace the default logger [here](https://github.com/kframework/kore/blob/5fddbb087dedd928b08414a23bca6c13dd672d59/kore/test/Test/Kore/Repl/Interpreter.hs#L708) with some implementation of `MonadLog` which records the logs.
