### ISSUE TITLE
Allow specifying max number of counter-examples

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#2648]
This is low priority, because it only affects the generation of automatic optimizations, which is not a _needed_ feature. However, there is no workaround that I'm aware of.

Currently, I'm running a proof like this:

```
kevm prove --backend haskell exp-spec.k OPTIMIZE --concrete-rules-file tests/specs/mcd/concrete-rules.txt --depth 10
```

On `exp-spec.k` which looks like this:

```
requires "lemmas/mcd/verification.k"

module OPTIMIZE
    imports INT
    imports LEMMAS-MCD
    imports EVM
endmodule

module EXP-SPEC
    imports OPTIMIZE

    claim <k> (#next [ EXP ] => #halt) ~> #execute ... </k>
          <schedule> SCHED </schedule>
          <program>  PGM   </program>
          <pc>         PCOUNT       => PCOUNT +Int #widthOp(EXP) </pc>
          <wordStack>  W0 : W1 : WS => ?_                             </wordStack>
          <localMem>   LM           => ?_                             </localMem>
          <gas>        #gas(GAVAIL) => ?_                             </gas>
          <memoryUsed> MU           => ?_                             </memoryUsed>
      requires #stackNeeded(EXP) <=Int #sizeWordStack(W0 : W1 : WS)
       andBool #sizeWordStack(W0 : W1 : WS) +Int #stackDelta(EXP) <=Int 1024


endmodule
```

I happen to know (out of band) that there are _two_ failure cases, one for `W0 ==Int 0` and one for `W0 =/=Int 0`.

Currently, the backend only gives me the one counterexample, for `W0 ==Int 0`.

I would like to be able to specify something like `--max-counterexamples 10`, to tell the backend to keep searching for counterexamples and to disjunct them together.

**Comment by ana-pantilie** [comment]
Keep list of stuck claims, modify https://github.com/kframework/kore/blob/23c6c22f91ddd491e2e7c0669fb112822d674665/kore/src/Kore/Reachability/Prove.hs#L162 to keep State as well.

**Comment by ana-pantilie** [comment]
@ttuegel suggests to test if we actually need `throwUnproven`: we can write `claim a => a ensures false` and run it with depth 1 it should not report depth limit exceeded. If we do need it, just factor out common elements between `throwUnproven` and `throwStuckClaims`.

**Comment by andreiburdusa** [comment]
> @ttuegel suggests to test if we actually need `throwUnproven`: we can write `claim a => a ensures false` and run it with depth 1 it should not report depth limit exceeded. If we do need it, just factor out common elements between `throwUnproven` and `throwStuckClaims`.

We only emit `WarnDepthLimitExceeded` when using `koreRun`. Should we add the warning for `koreProve` as well or remove `throwUnproven`?

**Comment by ana-pantilie** [comment]
> We only emit WarnDepthLimitExceeded when using koreRun. Should we add the warning for koreProve as well or remove throwUnproven?

Well, when using `koreRun` we don't really have this concept of "stuck" or "unproven" configuration. I'm not sure about adding the warning, though.

So, do we actually need `throwUnproven` there, did the test show anything?

**Comment by andreiburdusa** [comment]
> > We only emit WarnDepthLimitExceeded when using koreRun. Should we add the warning for koreProve as well or remove throwUnproven?
> 
> Well, when using `koreRun` we don't really have this concept of "stuck" or "unproven" configuration. I'm not sure about adding the warning, though.
> 
> So, do we actually need `throwUnproven` there, did the test show anything?

The only place we call `warnDepthLimitExceeded` is in `exec`, which is called by `koreRun`. Doesn't it mean there's no way for `koreProve` to emit `WarnDepthLimitExceeded`, and therefore making the test useless?

**Comment by andreiburdusa** [comment]
The test doesn't emit `WarnDepthLimitExceeded`, but the only place we call `warnDepthLimitExceeded` is in `exec`, which is only called by `koreRun` from what I see, so I don't think that's relevant.

**Comment by andreiburdusa** [comment]
> > We only emit WarnDepthLimitExceeded when using koreRun. Should we add the warning for koreProve as well or remove throwUnproven?
> 
> Well, when using `koreRun` we don't really have this concept of "stuck" or "unproven" configuration. I'm not sure about adding the warning, though.
> 
> So, do we actually need `throwUnproven` there, did the test show anything?

The test doesn't emit WarnDepthLimitExceeded, but the only place we call warnDepthLimitExceeded is in exec, which is only called by koreRun from what I see, so I don't think that's relevant.

**Comment by ana-pantilie** [comment]
> The test doesn't emit WarnDepthLimitExceeded, but the only place we call warnDepthLimitExceeded is in exec, which is only called by koreRun from what I see, so I don't think that's relevant.

Oh, got it. And actually, I just realized, this test should get stuck during the first rewrite step, so I'm confused about how it could help us figure out what's happening here.

**Comment by ehildenb** [comment]
These are the two rules I expect it to branch on (and both should fail):

```
    rule <k> #gasExec(SCHED, EXP _ 0)  => Gexp < SCHED > ... </k> 
    rule <k> #gasExec(SCHED, EXP _ W1) => Gexp < SCHED > +Int (Gexpbyte < SCHED > *Int (1 +Int (log256Int(W1)))) ... </k> requires W1 =/=Int 0 
```

https://github.com/kframework/evm-semantics/blob/master/evm.md#execution-gas
