### ISSUE TITLE
Poor Productivity Warnings

### ISSUE THREAD

**Issue by JKTKops** [kframework/kore#2670]
While working on migrating `evm-semantics` proofs to the Haskell backend, we started seeing some warnings like these:
```
kevm prove tests/specs/benchmarks/storagevar01-spec.k VERIFICATION  --backend haskell --format-failures  --concrete-rules-file tests/specs/benchmarks/concrete-rules.txt
kore-exec: [590432748] Warning (WarnIfLowProductivity):
    Productivity dropped to: 89%
    Relevant K files include:
        /home/jenkins-slave/workspace/evm-semantics_PR-1034@2/tests/specs/benchmarks/verification.k
        /home/jenkins-slave/workspace/evm-semantics_PR-1034@2/././tests/specs/benchmarks/storagevar02-overflow-spec.k
    Poor productivity may indicate a performance bug.
    Please file a bug report: https://github.com/kframework/kore/issues
#Top

kevm prove tests/specs/functional/infinite-gas-spec.k VERIFICATION  --backend haskell --format-failures  --concrete-rules-file tests/specs/functional/concrete-rules.txt
kore-exec: [520083085] Warning (WarnIfLowProductivity):
    Productivity dropped to: 89%
    Relevant K files include:
        /home/jenkins-slave/workspace/evm-semantics_PR-1034@2/tests/specs/benchmarks/verification.k
        /home/jenkins-slave/workspace/evm-semantics_PR-1034@2/././tests/specs/benchmarks/storagevar01-spec.k
    Poor productivity may indicate a performance bug.
    Please file a bug report: https://github.com/kframework/kore/issues
#Top
```

The mentioned verification file is [here](https://github.com/kframework/evm-semantics/blob/0cb565e85b54a9d9e5c12acfb38f5236d039a303/tests/specs/benchmarks/verification.k) and the specs are [storagevar01-spec](https://github.com/kframework/evm-semantics/blob/0cb565e85b54a9d9e5c12acfb38f5236d039a303/tests/specs/benchmarks/storagevar01-spec.k) and [storagevar02-overflow-spec](https://github.com/kframework/evm-semantics/blob/0cb565e85b54a9d9e5c12acfb38f5236d039a303/tests/specs/benchmarks/storagevar02-overflow-spec.k).

Everett pointed out that the performance fixes already in the works might also fix this, but @ana-pantilie asked that we open an issue to keep track of it in case it's unrelated.

**Comment by ttuegel** [comment]
I don't think there is any problem here. First, 89% is really borderline (the cut-off to see the warning is 90%). Second, these warnings are happening on Jenkins. If there is any resource contention on Jenkins, for example anything that would slow down Z3, then I would expect the value to drop. You can re-open the issue if you can reproduce it locally.
