### ISSUE TITLE
Using `--bug-report` does not work for proofs which loop in initial simplification step

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#2696]
If you have a proof which loops in the initial simplification step, even if you supply `--bug-report FILE_NAME`, if does not produce a bug report. Or if the user kills the process prematurely (eg. a `timeout NNN kprove ...` command, or `Ctrl+C`), no bug report is produced.

So I guess we should produce the bug report _first_ if the user supplies the `--bug-report` option, _then_ do the execution. In all other cases that bug reports are produced, it still makes sense to produce them when the error occurs.

**Comment by ana-pantilie** [comment]
@ttuegel suggests we could add a separate tool which just generates the bug reports without doing any execution.

**Comment by ana-pantilie** [comment]
@ehildenb suggests this should be implemented in the frontend.
