### ISSUE TITLE
Remove duplicated code between ==K, ==Int, and ==String

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2701]
There is a lot of duplicated code between the unification handlers for `==K`, `==Int`, and `==String`. The implementation of these unification handlers should be identical.

**Comment by ana-pantilie** [comment]
See https://github.com/kframework/kore/blob/0f992a35622bbb6d77b904a782317ef6f31b9a7d/kore/src/Kore/Builtin/Int.hs#L520, https://github.com/kframework/kore/blob/0f992a35622bbb6d77b904a782317ef6f31b9a7d/kore/src/Kore/Builtin/KEqual.hs#L272 and https://github.com/kframework/kore/blob/0f992a35622bbb6d77b904a782317ef6f31b9a7d/kore/src/Kore/Builtin/String.hs#L570
