### ISSUE TITLE
Fix error message

### ISSUE THREAD

**Issue by nishantjr** [kframework/kore#2751]
Note that the `initial.kore` is generated by a non-frontend tool. All inputs are uploaded as attachments.

When running the following initial configuration:

```
  #Not ( #Not ( #Exists iver3:Int . #Not ( ( #Not ( {
          ?I:Int
        #Equals
          ?V3:Int
        }
      #And
        {
          ?I0:Int
        #Equals
          iver3:Int
        } )
    #Or
      {
        true
      #Equals
        true
      } )
  #And
    ( #Not ( {
        ?I:Int
      #Equals
        ?V3:Int
      } )
    #Or
      {
        true
      #Equals
        true
      } )
  #And
    ( #Not ( #Not ( {
        ?I:Int
      #Equals
        ?V3:Int
      } ) )
    #Or
      {
        true
      #Equals
        true
      } ) ) ) )
#And
  <boogie>
    <k>
      false ~> #freezerrestoreLocals(_,_)_BOOGIE-RUNTIME_KItem_Expr_Map0_ ( this |-> value ( ?V3:Int , ref , true ) ~> . ) ~> #freezerforallbinderheated1_ ( ?I:Int ~> . ) ~> .
    </k>
    ...
  </boogie>
```

I see the following error:

```
$ kore-exec .build/defn/verification/boogie-kompiled/definition.kore --module BOOGIE --pattern initial.kore 
kore-exec: [2448099] Error (ErrorException):
    Prelude.maximum: empty list
Created bug report: kore-exec.tar.gz
```

It should apply the cooling rule for this construct:

```
    syntax KItem ::= restoreLocals(Expr, Map) [strict(1)]                                                               
    rule <k> restoreLocals(E:ValueExpr, Locals) => E ... </k>                                                           
         <locals> _ => Locals </locals>
```

[initial.kore.txt](https://github.com/kframework/kore/files/6821025/initial.kore.txt)
[kore-exec.tar.gz](https://github.com/kframework/kore/files/6821027/kore-exec.tar.gz)
[initial.pretty.txt](https://github.com/kframework/kore/files/6821028/initial.pretty.txt)

**Comment by ana-pantilie** [comment]
First, we should run this with the [-xc](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#rts-flag--xc) GHC flag to see the full stack trace, and find where the error is coming from.

**Comment by RaoulSchaffranek** [comment]
I ran this test with the following command to record a [stack trace](https://github.com/kframework/kore/files/6862383/stacktrace.txt).

~~~bash
env GHCRTS='-xc'\
   kore-exec ../issues/kore/2751/kore-exec/definition.kore\
   --module BOOGIE\
   --pattern ../issues/kore/2751/initial.kore 2>stacktrace.txt
~~~

However, I don't find it particularly useful.
Since the original error message mentioned the `maximum`-function I scanned the code-base and found that we only use this function once here: https://github.com/kframework/kore/blob/78ec7647e9b9eca9045544fe4a8c6c1fead93587/kore/src/Kore/Exec.hs#L261

I am still investigating what's going on. I'm currently running interactive debugging sessions with GHCi.

**Comment by nishantjr** [comment]
Aaah! Looks like the issue is that the initial configuration is unsatisfiable. I can reproduce it with this definition:

```
module TEST
    imports INT

    syntax Foo ::= "foo"
    configuration <k> foo </k>
endmodule
```

and this initial configuration:
```
#Not ( {
    foo
  #Equals
    foo
  } )
#And
  <k>
    foo ~> .
  </k>
```

```
    \and{SortGeneratedTopCell{}}(
        /* Fl Fn D Sfa Cl */
        Lbl'-LT-'generatedTop'-GT-'{}(
            /* Fl Fn D Sfa Cl */
            Lbl'-LT-'k'-GT-'{}(
                /* Fl Fn D Sfa Cl */
                kseq{}(
                    /* Fl Fn D Sfa Cli */
                    /* Inj: */ inj{SortFoo{}, SortKItem{}}(
                        /* Fl Fn D Sfa Cl */ Lblfoo'Unds'TEST'Unds'Foo{}()
                    ),
                    /* Fl Fn D Sfa Cl */ dotk{}()
                )
            ),
            /* Fl Fn D Sfa Cl */
            Lbl'-LT-'generatedCounter'-GT-'{}(
                /* Fl Fn D Sfa Cl */ \dv{SortInt{}}("0")
            )
        ),
        /* Sfa */
        \not{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortFoo{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ Lblfoo'Unds'TEST'Unds'Foo{}(),
                /* Fn Sfa */ Lblfoo'Unds'TEST'Unds'Foo{}()
            )
        )
    )
```

Bug report:
[kore-exec.tar.gz](https://github.com/kframework/kore/files/6864291/kore-exec.tar.gz)

**Comment by ana-pantilie** [comment]
I think you're right, if we fix the `maximum` call I think this should return `#Bottom`.
