### ISSUE TITLE
Unexpected and slow interaction between #hashedLocations and #computeValidJumpDests

### ISSUE THREAD

**Issue by Riib11** [kframework/kore#2761]
(This is extracted from a slow proof from the `evm-semantics` repository.)

This is simplified example where, simplifying `#computeValidJumpDests` and `#hashedLocation` in the same configuration takes much longer than simplifying either one of these functions by themselves (on the same inputs respectively).

| enabled | time (min:sec) |
|---|---|
| both | 7:30 |
| just `#computeValidJumpDests` | 0:36 | 
| just `#hashedLocation` | 0:07 |

To build the file `evm-simple.k` run:
```sh
make build
```

To run the example proof `tests/allowance-spec.k` run:
```sh
make prove
```

Version info:
```
> kompile --version
K version:    5.1.64
Build date:   Tue Jun 15 22:32:32 UTC 2021

> kprove --version
K version:    5.1.64
Build date:   Tue Jun 15 22:32:32 UTC 2021
```

[evm-simple.zip](https://github.com/kframework/kore/files/6864869/evm-simple.zip)

**Comment by ana-pantilie** [comment]
We should first look at https://github.com/kframework/kore/issues/2757 to get a better understanding of `#computeValidJumpDests` by itself.

**Comment by JKTKops** [comment]
#2779 appears to have fixed this issue.
