### ISSUE TITLE
Investigate long running z3 commands.

### ISSUE THREAD

**Issue by RaoulSchaffranek** [kframework/kore#2778]
While working on https://github.com/kframework/evm-semantics/pull/1102, I noticed that the proof takes roughly an hour to complete. About 40 minutes are spent waiting for z3.

So far, I've recorded an smt-transcript, which shows some suspicious behavior. There are multiple very long sequences of `declare-fun`-commands followed by one `assert`-command with one giant conjunction over all the declared symbols:

~~~lisp
(declare-fun <0> () Bool )
; success

(declare-fun <1> () Bool )
; success

; ...

(declare-fun <9183> () Bool )
; success

(assert (and <2> (and <3> (and <4> .... (and <9182> <9183>) ... ))))
~~~

I am not sure if this is where z3 spends most of its 40 minutes, but it seems suspicious.

[z3.1.log](https://github.com/kframework/kore/files/6929746/z3.1.log)

**Comment by ana-pantilie** [comment]
Where we translate patterns for the SMT: https://github.com/kframework/kore/blob/master/kore/src/Kore/Rewrite/SMT/Translate.hs
Where we send predicates to the SMT: https://github.com/kframework/kore/blob/29888c3567cb479fc5ee619f21a1545d88ff66e8/kore/src/Kore/Rewrite/SMT/Evaluator.hs#L179

**Comment by ana-pantilie** [comment]
We should still investigate what's happening here, but if a workaround in KEVM was found then we can postpone this for a bit.

**Comment by RaoulSchaffranek** [comment]
I have implemented a [workaround](https://github.com/kframework/evm-semantics/pull/1102#issuecomment-895840984) for the issue where I first observed this behavior. However, the simplification rules that I added there are rather specific to the test case under question. I don't expect a general speed-up from these rules.

Meanwhile, @calin1304 took a look at [tests/specs/mcd/vat-move-diff-rough-spec.k](https://github.com/kframework/evm-semantics/blob/8a07c45ca7b6d571cc114e8d9a38b612222f223f/tests/specs/mcd/vat-move-diff-rough-spec.k) and also found it very slow. A quick look at the smt-transcript revealed the same pattern I described above, so this is likely related. This test case might be a better start for investigation because the behavior can be reproduced in the first proof-step.

We also found that we are both working on a Windows+WSL2. It would be interesting to know if this issue can be reproduced on a native Linux or Mac, just to rule out the possibility that this is some weird WSL behavior.

**Comment by calin1304** [comment]
I was able to reproduce the issue on native Linux. I just installed a fresh copy of Ubuntu 21.04 and tried to run [tests/specs/mcd/vat-move-diff-rough-spec.k](https://github.com/kframework/evm-semantics/blob/8a07c45ca7b6d571cc114e8d9a38b612222f223f/tests/specs/mcd/vat-move-diff-rough-spec.k) and had the same issue as when running it on WSL2. After about 3-5 minutes memory usage increases past 20+ GB, taking up all my memory.

**Comment by RaoulSchaffranek** [comment]
This performance issue is solved as a side-effect of https://github.com/kframework/kore/pull/2800.
The problem was that we were sending big concrete sets to the solver.

https://github.com/kframework/kore/pull/2814 adds the original evm-test, which revealed this behavior to our regression-test-suite.
