### ISSUE TITLE
`SideCondition.definedTerms`: check if AC terms are always defined before caching them  

### ISSUE THREAD

**Issue by ana-pantilie** [kframework/kore#2779]
In [SideCondition.definedTerms](https://github.com/kframework/kore/blob/726faa4c269a70f0ad8d2045561beebb9350a829/kore/src/Kore/Internal/SideCondition.hs#L168) we keep a set of terms we assume to be defined during execution. See [assumeDefined](https://github.com/kframework/kore/blob/726faa4c269a70f0ad8d2045561beebb9350a829/kore/src/Kore/Internal/SideCondition.hs#L705) and [isDefined](https://github.com/kframework/kore/blob/726faa4c269a70f0ad8d2045561beebb9350a829/kore/src/Kore/Internal/SideCondition.hs#L787).

For AC structures, we build a minimal set of AC collections from which the definedness of any sub-collection can be inferred. In practice, people have noticed that we keep very large numbers of concrete ACs in memory for this purpose, and this should be avoided.

We can fix this by adding two checks:
1. If the initial collection is always defined, do not generate the minimal set.
2. After generating the minimal set, we should remove the ones which we know are always defined.

Unit tests should be modified/added accordingly.

**Comment by JKTKops** [comment]
The KEVM proof port team observed this issue while looking at `tests/specs/mcd/cat-file-addr-pass-rough-spec.k`. Turn on any `DebugAttemptEquation` log (I had it on for a specific equation of `#hashedLocation`, but I don't think that should matter). After the initial simplification, you will be able to observe the large number of 2-element sets in the `Assumed to be defined` section.

**Comment by JKTKops** [comment]
From the KEVM Proof port team, we have a suspicion that this might be the root cause of #2761, but that's just a thought. Everett thinks we may have been underestimating the impact this one has on the evm proofs.
