### ISSUE TITLE
Add `oneLineDoc` implementations to all existing `Entry`-instances

### ISSUE THREAD

**Issue by RaoulSchaffranek** [kframework/kore#2781]
The Haskell backend supports a short logging format that only logs the source locations of log entries, but no descriptive messages.

Log entries which relate to specific source locations should implement the following method:
https://github.com/kframework/kore/blob/29888c3567cb479fc5ee619f21a1545d88ff66e8/kore/src/Log/Entry.hs#L61-L62

However, not all `Entry`-instances implement this function yet.

Here is an example of an instance which implements the method:
https://github.com/kframework/kore/blob/29888c3567cb479fc5ee619f21a1545d88ff66e8/kore/src/Kore/Log/DebugBeginClaim.hs#L33-L34

Here is an example of instance which doesn't implement the method:
https://github.com/kframework/kore/blob/29888c3567cb479fc5ee619f21a1545d88ff66e8/kore/src/Kore/Log/WarnDepthLimitExceeded.hs#L35-L38

The first step to solve this issue would be to identify all `Entry`-instances which lack an appropriate implementation. The second step is implementing these functions.

The short logging format is enabled by passing `--log-format oneline` command-line argument to `kore-exec`.

**Comment by JKTKops** [comment]
One line logs don't have to be source locations, they could just be the minimal information relevant for the log, designed for readability in a script as opposed to by a person. For example, `WarnDepthLimitExceeded` should print the limit that was exceeded.

If an Entry doesn't have relevant information to print, it should probably return an empty doc. `oneLineDoc`'s type can change from `Entry e => e -> Maybe Doc` to just `Entry e => e -> Doc`, unless we think there's a good reason to keep around the "One line logging not implemented for this entry" behavior.

I think the flag to enable the format is `--log-format oneline`.

**Comment by ana-pantilie** [comment]
We should probably remove the default implementation for `oneLineDoc` and switch the type to `Entry e => e -> Doc`, as @JKTKops suggested.
