### ISSUE TITLE
haskell-backend test failures when running test suite with updated equation format and latest llvm-backend

### ISSUE THREAD

**Issue by SchmErik** [kframework/kore#2811]
The new equation format implemented [here](https://github.com/kframework/k/pull/2061) causes several test suite issues failures. I've attached the typescript file running with the latest llvm-backend commits. This file contains the output from running make -j8 -O -k in the regression-new directory in the k repo.
[typescript.txt](https://github.com/kframework/kore/files/7016754/typescript.txt)

**Comment by ehildenb** [comment]
The new encoding format: https://github.com/kframework/k/issues/1945
The changes to ModuleToKore: https://github.com/kframework/k/pull/2061

**Comment by radumereuta** [comment]
Try to replicate the issue @SchmErik found:
```
/home/erik/k/k-distribution/bin/kompile --syntax-module TEST --no-exc-wrap --backend haskell  test.k -d .
Error:
  module 'TEST':
  axiom declaration:
  \implies (definition.kore 6599:21):
  \equals (definition.kore 6623:26):
  \and (definition.kore 6625:12):
  (definition.kore 6625:12, definition.kore 228:128):
    Expecting sort R but got SortString{}.
```
It might be as simple as switching the `\equals` parameters.

**Comment by ana-pantilie** [comment]
Oh, so this failure is on the PR for updating the frontend to generate the new equation encoding, right? I initially didn't understand where the error was coming from. If that's the case, we need to make the backend accept both encodings until we get this frontend update released. @dopamane

**Comment by dopamane** [comment]
I am able to reproduce the issue. I do not think switching the `\equals` parameters is the solution. According to the documentation it is correct; see [kore-implicits.md](https://github.com/kframework/kore/blob/master/docs/kore-implicits.md#predicates). Therefore I am working on updating the backend to support both encodings.

**Comment by ana-pantilie** [comment]
After looking through the changes made to the backend, it turned out that the backend already accepts both encodings, so this is either a bug in the frontend or in the backend.

I believe the error is coming from [assertSameSort](https://github.com/kframework/kore/blob/994c5cbcf87ac7b1526a74af41d0d72df0ddca30/kore/src/Kore/Validate/PatternVerifier/PatternVerifier.hs#L287). @dopamane can you please add a comment with the axiom declaration from `definition.kore` this fails on?

**Comment by dopamane** [comment]
There are multiple test failures that report `Expecting sort R but got _`. Here is the axiom declaration from `regression-new/issue-1879-kproveTrans/haskell`:
```  axiom{R} \implies{R} (
    \and{R}(
      \equals{SortBool{},R}(
        Lbl'Unds-GT-Eqls'Int'Unds'{}(VarI1:SortInt{},VarI2:SortInt{}),
        \dv{SortBool{}}("true")),
      \and{R} (
          \in{SortInt{}, R} (
            X0:SortInt{},
            VarI1:SortInt{}
          ),\and{R} (
          \in{SortInt{}, R} (
            X1:SortInt{},
            VarI2:SortInt{}
          ),
          \top{R} ()
        ))),
    \equals{SortInt{},R} (
      LblminInt'LParUndsCommUndsRParUnds'INT-COMMON'Unds'Int'Unds'Int'Unds'Int{}(X0:SortInt{},X1:SortInt{}),
      \and{R} (
        VarI2:SortInt{},
        \top{R}())))
  [org'Stop'kframework'Stop'attributes'Stop'Location{}("Location(1114,8,1114,57)"), org'Stop'kframework'Stop'attributes'Stop'Source{}("Source(/home/davos/github.com/kframework/k/k-distribution/target/release/k/include/kframework/builtin/domains.md)"), org'Stop'kframework'Stop'definition'Stop'Production{}("syntax #RuleContent ::= #RuleBody \"requires\" Bool [klabel(#ruleRequires), symbol]"), UNIQUE'Unds'ID{}("e1effeabf96bb3a3beffd5b679ad5df95c4f8bbf42872b0793331e52a8470fb3")]
```

Which failed with error:
```
Error:                                                                              
  module 'TEST':                                                                    
  axiom declaration:                                                                
  \implies (definition.kore 2335:21):                                               
  \equals (definition.kore 2351:23):                                                
  \and (definition.kore 2353:12):                                                   
  (definition.kore 2353:12, definition.kore 2354:15):                               
    Expecting sort R but got SortInt{}.  

```
