### ISSUE TITLE
kore-repl: don't crash when system doesn't support graph visualizer

### ISSUE THREAD

**Issue by ana-pantilie** [kframework/kore#2817]
`kore-repl` shouldn't crash when the system doesn't support the graph visualizer for some reason. We should try to reproduce the crash on a macOS machine by running the `graph` command.

**Comment by emarzion** [comment]
My output when running `graph`:

```
Kore (0)> graph
kore-repl: [2176878] Error (ErrorException):
    Error running utility program: Error messages from dot:
    Format: "xlib" not recognized. Use one of: bmp canon cgimage cmap cmapx cmapx_np dot dot_json eps exr fig gd gd2 gif gv icns ico imap imap_np ismap jp2 jpe jpeg jpg json json0 mp pct pdf pic pict plain plain-ext png pov ps ps2 psd sgi svg svgz tga tif tiff tk vdx vml vmlz vrml wbmp webp xdot xdot1.2 xdot1.4 xdot_json
[Error] Critical: Haskell Backend execution failed with code 1 and produced no
output.
```

**Comment by ana-pantilie** [comment]
Test if `graph filename` works.

Catch the error when `graph` fails.

**Comment by emarzion** [comment]
Looks like `graph filename` still works for me.

**Comment by ana-pantilie** [comment]
Cool! Then I think we can just catch the error for now, and open another issue for trying to find a way to support graph visualization inside the repl for MacOS as well.
