### ISSUE TITLE
Allow simplification rules in spec file

### ISSUE THREAD

**Issue by ana-pantilie** [kframework/kore#2930]
See https://github.com/kframework/k/issues/2287#issuecomment-965113610

**Comment by radumereuta** [comment]
Thank you for looking into this.
I'm expecting the transition to kprovex to be a lot less painful if we can support this feature.
I've added a test that should pass once the backend can handle simplification rules in the `spec.kore` file.
Another thing that I have to check after that is if I'm applying the correct kompile steps for those rules, but that is a front-end issue, and I need support from the backend first.
