### ISSUE TITLE
Allow users to specify `non-executable` on rule/simplification rules

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#2933]
We need a way to feed lemmas to only the smt-solver, but _not_ use them as K reductions. To achieve this, I'd like to write:

```
rule LHS => RHS requires REQ [smt-lemma, non-executable]
```

This just means that the rule should not be considered for rewriting (whether it's a simplification rule or not).

This needs to also interact correctly with `no-evaluators`, that is when you put `no-evaluators` on a symbol it should only have `non-executable` rules present for that symbol.

This may also require a small update to the frontend, to make it aware of this new attribute.

**Comment by ehildenb** [comment]
This is in support of smt-encoding exponentiation properly: https://github.com/kframework/k/issues/2308

**Comment by ana-pantilie** [comment]
@ehildenb In order to avoid any issues with needing to encode this on function definition rules, I'd only implement this attribute for simplification rules. Does that sound fine to you?

**Comment by ana-pantilie** [comment]
> This needs to also interact correctly with no-evaluators, that is when you put no-evaluators on a symbol it should only have non-executable rules present for that symbol.

This check should be done in the frontend, together with checking that the rule also has the `simplification` attribute.

The backend will just filter out any equations with this attribute when it builds the function evaluators during initialization. I have to make sure, though, that this doesn't have as a consequence not sending it to Z3 either, so I have to investigate this first.

**Comment by ana-pantilie** [comment]
I actually thought about this a bit more, and I think it's actually safe to allow only `non-executable` on equations (without the `simplification` attribute). That could just be another indicator that the equation is "outside the semantics", and would probably less confusing to users than if they had to specify both `non-executable` and `simplification`. I think we'd only have to make sure that it doesn't get treated internally (in the frontend) as a function definition rule.

**Comment by ana-pantilie** [comment]
Blocked on https://github.com/kframework/k/issues/2388
