### ISSUE TITLE
Integration test suite: separate kompilation from execution

### ISSUE THREAD

**Issue by ana-pantilie** [kframework/kore#2954]
We should remove the `VERIFICATION` module where it's not needed. This means we need different ways of running tests: the specs which depend on such a module will be run as they are now (by re-kompiling the definition for each spec), and those which don't should just be run simply.

**Comment by andreiburdusa** [comment]
We decided we're going to proceed a different way:
Change the testing infrastructure such that
- `make build-test` kompiles everything needed for the tests
- `make test-k` runs the tests without kompiling anything
- `make test-k SIMPLIFIERX=true` runs the tests without kompiling anything, with the `--simplifierx` flag
