### ISSUE TITLE
Standardize running KEVM performance testing on simplifierx

### ISSUE THREAD

**Issue by ana-pantilie** [kframework/kore#2983]
@andreiburdusa and @JKTKops please add ideas here.

Edit: see discussion https://docs.google.com/document/d/1rWjSSMpvMCbTLfXiK4cVYm-5A-yM7vQAyjH__I_Ed-4/edit?usp=sharing

**Comment by andreiburdusa** [comment]
So far I wrote this script which I plan to use for generating performance reports for different backend commits:

`runTestsSimplifierX.sh`
```sh
#!/usr/bin/bash
cd /home/andrei/evm-semantics/deps/k/haskell-backend/src/main/native/haskell-backend
git checkout $1
cd /home/andrei/evm-semantics
make k-deps
make build-provex
rm logs/$1/profile/without-simplifier-x
rm logs/$1/profile/with-simplifier-x
make test-prove TEST_SYMBOLIC_BACKEND=haskell KEVM="profile logs/$1/profile/without-simplifier-x timeout 3000 kevm" -k -j4
export KORE_EXEC_OPTS=--simplifierx
make test-prove TEST_SYMBOLIC_BACKEND=haskell KEVM="profile logs/$1/profile/with-simplifier-x timeout 3000 kevm" -k -j4
```

**Comment by ana-pantilie** [comment]
@andreiburdusa Are you 100% sure that the second `make` command is receiving the `--simplifierx` flag correctly? I remember having to add the `-e` option for the commands run by `make` to have access to external environment variables.

**Comment by andreiburdusa** [comment]
> @andreiburdusa Are you 100% sure that the second `make` command is receiving the `--simplifierx` flag correctly? I remember having to add the `-e` option for the commands run by `make` to have access to external environment variables.

Adding
```
export KORE_EXEC_OPTS="--bug-report indeedBugReport"
```
before the first `make` command causes a bug report to be produced, so I suppose the `--simplifierx` flag is also received correctly.
