### ISSUE TITLE
Version numbers should be monotonic

### ISSUE THREAD

**Issue by nishantjr** [kframework/kore#30]
The `develop` branch is ahead of `master` by several commit.
`master` is at version `1.0-SNAPSHOT`, but `develop` is at `0.6-SNAPSHOT`.

I think we should correct the version of `develop` to `1.1` or `1.0.1`.

**Comment by nishantjr** [comment]
@cos @msaxena2

**Comment by cos** [comment]
yes, and we've been using it for quite a while, so let's merge into master soon.

**Comment by cos** [comment]
it will be a bit involved as there are quite a few changes, we have to make sure everything is clean, and make sure K is building using it

**Comment by cos** [comment]
@nishantjr, could you take the lead on this?

**Comment by nishantjr** [comment]
@cos I don't think that I'm the best person to review changes  because I'm not familiar with the code base. If tests are passing under the CI, wouldn't that be enough?

**Comment by cos** [comment]
@nishantjr, I meant open a PR and follow through to its merge, making sure the code is clean and all parties are happy with the code. we aim to keep kore minimal and very clean, so all tests passing is not enough.

**Comment by nishantjr** [comment]
@cos, Could you take a quick look at `njr/cleanup` and let me know if those can be brought into `develop` before I make the PR

**Comment by ehildenb** [comment]
@nishantjr can this be closed now with the new `develop-rebased` branch?

**Comment by nishantjr** [comment]
Sorry, didn't see your message @ehildenb
