### ISSUE TITLE
Mishandled octal escape sequences

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#409]
When the backend outputs an octal escape sequence such as `\316`, the front-end displays `\x0316`, which is the escape `\x03` followed by two characters `16`; the correct output is `\xce`. I am not sure if the bug is in the backend or the frontend, but changing the backend to output Unicode escapes (`\u00ce`) avoids the issue entirely. (The Java Language Specification recommends to [avoid octal escapes](https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.10.6).)

See also: #404

**Comment by ttuegel** [comment]
@traiansf Should I try to track this bug down so that octal escapes work between the frontend and the backend, or should we just use Unicode escapes? I can also update _The Semantics of K_ to be explicit about the escapes we recognize.

**Comment by traiansf** [comment]
I think that the decision to use C strings was just picking up something, so I would be ok to using Java strings (I think that we want to support things like \n), or something similar. You should confirm this with Dwight and Xiaohong, though.

**Comment by dwightguth** [comment]
I'm fine with whatever escape syntax we choose as long as it's one of the ones that the K frontend already supports.

**Comment by ttuegel** [comment]
@dwightguth @hreada @traiansf 
I would like to propose that Kore support only the Java shorthand escapes:
```
EscapeSequence:
\ b (backspace BS, Unicode \u0008)
\ t (horizontal tab HT, Unicode \u0009)
\ n (linefeed LF, Unicode \u000a)
\ f (form feed FF, Unicode \u000c)
\ r (carriage return CR, Unicode \u000d)
\ " (double quote ", Unicode \u0022)
\ ' (single quote ', Unicode \u0027)
\ \ (backslash \, Unicode \u005c)
```
the UTF-16 escapes `\uhhhh` and UTF-32 escapes `\Uhhhhhhhh`. 

I think we should reject the octal escapes because they don't seem to be handled correctly now, and even Java admits they were a bad idea. The Haskell backend also recognizes these escapes from C which are not supported in the frontend Kore parser:
```
\?  (question mark ?, used in C to avoid trigraph expansion, but useless in Kore)
\xhh (UTF-8, not supported in Java)
```

If there is no objection, I will make these changes to the Haskell backend, the frontend, and document the change in _The Semantics of K_.
