### ISSUE TITLE
SMT not simplifying predicate with uninterpreted functions.

### ISSUE THREAD

**Issue by traiansf** [kframework/kore#468]
Steps to reproduce:

On branch https://github.com/kframework/kore/tree/prove-issue-1  (PR #456)

```bash
make
cd src/main/k/working/smc
make prove/add-stack-spec.kprove
```

currently fails with the following output.
```
  <T>
    <k>
      1 ~> 1 ~> + ~> sum =
    </k>
    <mem>
      sum |-> I
    </mem>
    <stack>
      S
    </stack>
  </T>
#And
    stackSize ( S ) <=Int 6
  #Equals
    true
#And
  #Not ( stackSize ( S ) <Int 8
  #Equals
    true )
#And
  #Not ( stackSize ( S ) >=Int 8
  #Equals
    true )
```

Note that the condition is unsat.  However, the SMT fails to refute it, returning `Nothing`

**Comment by ttuegel** [comment]
@u-- We have unit tests for `P ∧ ¬P`, but it would be useful to add cases where `P` contains uninterpreted functions.

**Comment by traiansf** [comment]
Here is not exactly `p /\ ~p` but Presburger arithmetic should render it unsat.
