### ISSUE TITLE
Avoid redundant constraints applying rules that produce one child

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#705]
When applying a rule produces only one child pattern, we know that the initial constraint subsumes the constraints on the rule; therefore, it is redundant to add the new constraints.

**Comment by ttuegel** [comment]
This can be achieved partly by keeping a `MultiAnd` of constraints and removing duplicates.

**Comment by virgil-serbanuta** [comment]
Could you give an example? This is a bit unclear to me, e.g. what do you mean by "initial constraint" and "new constraints"?

**Comment by ttuegel** [comment]
Sure, let
```
φ, L, R :: Term
P, Pre, Post :: Predicate
```
Starting from a configuration `φ∧P`, we apply a rule 
```
L ∧ Pre ⇒ R ∧ Post
``` 
to get
```
R ∧ Post ∧ ⌈L ∧ φ⌉ ∧ Pre ∧ P
```
or remainders. If the remainders are `⊥`, then we know that 
```
¬Pre ∧ P = ⊥
```
and therefore `Pre ∧ P = P`, which we can use to simplify the result above. This is useful in bounded model checking because we tend to accumulate new constraints `Pre`s that are less restrictive than the initial constraint `P`.

**Comment by ttuegel** [comment]
See also: #793

**Comment by traiansf** [comment]
Question:
Rather than checking that we have no remainder, wouldn't it be better to use Z3 to check that `⌈L ∧ φ⌉ ∧ P -> Pre` and, if so, to not add `Pre` to the predicate.
In addition to making the code simpler, this would also be usable when doing all-path where we don't compute the remainder after applying each rule.

**Comment by ttuegel** [comment]
Yes, that might be better, if we think that calls to Z3 are not too expensive. Eventually we will need to remove all the calls to Z3, but that gets us moving.
