### ISSUE TITLE
Apply substitutions under predicates during simplification

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#706]
During simplification, we can apply predicates under predicates such as `\ceil` to simplify them more completely; for example, the predicate
```
I:Int = 0 ∧ ⌈f(1 / I)⌉
```
can be simplified by taking the substitution under the `\ceil`,
```
⌈I:Int = 0 ∧ f(1 / I)⌉
```
and applying it to find
```
⌈f(1 / 0)⌉ = ⊥
```

**Comment by virgil-serbanuta** [comment]
There's some chance that I misunderstood the intent.

However, during simplification, we should extract [I=0] as a substitution in both cases, and I think that, in both cases, we won't apply it unless we find a quantifier for `I` (so just moving it under the `ceil` wouldn't be enough). I think that the main problem here is that we don't apply substitutions at the top, where the quantifiers are implicit. So, why shouldn't we state this as "Apply substitutions at the top during simplification (and re-simplify if needed)"?

Also, if we would have a formula for `ceil(f(x))`, most likely we wouldn't need to apply substitutions.

**Comment by ttuegel** [comment]
>  I think that the main problem here is that we don't apply substitutions at the top, where the quantifiers are implicit.

In the specific case I'm seeing, that will help only if we move all the disjunctions to the top, because we have the predicate `I:Int = 0 ∧ ⌈f(1 / I)⌉` in a disjunction with other predicates on `I`.

I don't think having a formula for `⌈f(X)⌉` will help here, either, because we still need to know if `X` is defined.

**Comment by virgil-serbanuta** [comment]
Ah, thanks, I see, I forgot that we don't move disjunctions to the top for predicates. I wonder if it's worth doing that when substitutions are involved... Possibly not, but it's worth keeping in mind. And it wouldn't help with other connectors, unless we transform everything to and/or/not.

So then the proposed rule is "apply substitutions each time we `and` two things", right? I guess that we could also apply substitutions each time we are transforming them into predicates (as we do when we make an 'or'), but this seems to complicate things without much benefit.

**Comment by ttuegel** [comment]
I think this is largely irrelevant since we iteratively simplify substitutions now.
