### ISSUE TITLE
Unifying domain values and constructors

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#715]
We need to decide if we will allow domain values and constructor symbols in the same sort. The frontend currently allows this, but there is some question if that is desirable. The options are:

1. Allow domain values and constructor symbols in the same sort. The declared constructors and domain values are disjoint. The backend will be updated to dis-unify domain values and constructors (it's currently an error). The frontend will be updated so that the generated no-junk and no-confusion axioms correctly include domain values.
1. Disallow domain values and constructor symbols in the same sort. The backend and frontend should reject definitions which declare constructors in a domain-valued sort. Some semantics will need to be updated.

**Comment by dwightguth** [comment]
For what it's worth, I'm amenable to number 2. It shouldn't be hard to update everything; you just will need to create a new sort for the domain values and introduce injections.

**Comment by ttuegel** [comment]
@ehildenb @traiansf Do you both still feel the same way?

**Comment by traiansf** [comment]
I would also much more prefer number 2.

**Comment by virgil-serbanuta** [comment]
I'll start working on the second solution, rejecting DVs and constructors in the same sort during verification. This may also need frontend changes.
