### ISSUE TITLE
Run without an SMT solver

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#717]
We would like to have a "null" implementation of the solver interface which does not send queries to an external solver, but reports every constraint as satisfiable. This is still useful for concrete execution. Most of our unit tests also do not require access to the solver.

---

Add an implementation of `MonadSMT` that:
- [x] Reports `unknown` for every query.
- [x] Emits a warning if any query is made. (Maybe?)
- [ ] Connect with frontend's `--smt none` flag.

**Comment by dwightguth** [comment]
you can hook this up to the K frontend with the --smt none kprove and krun flag.

**Comment by dwightguth** [comment]
I would think what you actually want though is to report every constraint as unknown.

**Comment by ttuegel** [comment]
Add an implementation of `MonadSMT` that:
- [ ] Reports `unknown` for every query.
- [ ] Emits a warning if any query is made.
- [ ] Connect with frontend's `--smt none` flag.
