### ISSUE TITLE
Interface with kprove

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#718]
There are a few annoyances surrounding our interface with the frontend's `kprove`:

- [x] `kprove` does not report the backend's exit code.

We use `kprove --dry-run --debug` to get the command line arguments to pass to `kore-repl`, but that combination of flags throws an embarrassing `NullPointerException`.

- [x] Don't throw that exception in the frontend.
- [ ] Support starting `kore-repl` directly from `kprove` automatically.

**Comment by traiansf** [comment]
The https://github.com/kframework/k/pull/553 PR I've just opened in the K repo should fix the second item above; apparently the first one works out of the box (anything output from the haskell-backend which cannot be parsed to `#True` generates an exit code `1`).
