### ISSUE TITLE
Create REPL aliases to allow filtering REPL configs through kast.

### ISSUE THREAD

**Issue by traiansf** [kframework/kore#738]
In the latest K version, one can use the command 
```
kast -i kore -o pretty -d <definition_dir> <file.kore>
````
 to format a kore term as a K term.

Note that the output of the REPL configurations might need some fiddling as last time I checked it was not valid KORE :-)

**Comment by vladciobanu** [comment]
Does `kast` work with pipes instead of an input file? Like `cat file.kore | kast -i kore -o pretty -d .`?

**Comment by traiansf** [comment]
I don't know, but it shouldn't be hard to make it accept input from stdin.

**Comment by ana-pantilie** [comment]
- [ ] fix kore unparser: https://github.com/kframework/kore/pull/762
- [ ] split repl output
- [ ] use kast with pipe (or workaround from repl)
- [ ] create repl script with aliases
