### ISSUE TITLE
Evaluating functions with undefined arguments

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#752]
Symbols with ⊥ arguments evaluate to ⊥, but we do not account for this when constructing remainders. For example, given an application pattern
```
f(φ)  // f is any symbol, φ is a possibly-undefined pattern
```
and an axiom such as
```
axiom f(x) = A
```
we will produce
```
f(φ) = A ∨ (f(φ) ∧ ¬⌈φ⌉)  // EDIT: This is not quite right, see below.
```
even though the condition attached to the latter makes the second disjunct ⊥. Consequently, we leave a mess of remainders around whenever partial patterns are involved.

I propose to solve this by adding definedness conditions to the initial condition during function application. We recognize that
```
f(φ) = f(φ) ∧ ⌈φ⌉
```
so that we can add `⌈φ⌉` to the initial conditions during rule application, which will prevent the messy remainders from ever being formed. When `φ` is a defined pattern, this condition becomes trivial, so in most cases this will not affect evaluation at all.

CC: @yzhang90 
See also: #729, #748

**Comment by grosu** [comment]
@ttuegel This seems pretty reasonable.  In fact, that also happens in separation logic proofs, when people prove that `HeapPattern1 -> HeapPattern2`, then assume `HeapPattern1` defined.

What concerns me, though, is the consistency of function definitions.  For example, if one says that `_/Int_` is a `[function]` and then that `I /Int 0 = \bot`, then we got an inconsistent definition.  Many FOL provers, including Z3, assume that all the functions are total (and implicitly also terminate, not only totally defined).  For example, `3/0 = 0` in Z3.  I think we may want to do the same with symbols declared as `[function]`.  The attribute is a hint, so the function can be used as such, but when we generate proof objects later on we'll need to check the claim and reject functions which are not total.

**Comment by ttuegel** [comment]
In _The Semantics of K_, what you are calling `function` is actually `functional`. `function` indicates a partial function, so I think the definition above is fine.

**Comment by vladciobanu** [comment]
Does this still hold if `f` is a `const` function?

**Comment by ttuegel** [comment]
@vladciobanu Yes, the semantics of symbols are such that `symbol(φ) = ⊥` if `φ = ⊥`.

**Comment by ttuegel** [comment]
@virgil-serbanuta pointed out during the meeting this morning that the result of applying the axiom for `f(x)` is actually:
```
f(φ) = (A ∧ ⌈φ⌉) ∨ ( f(φ) ∧ ¬⌈φ⌉ )
```
because binding `x = φ` introduces the condition `⌈φ⌉`. I originally suggested to introduce the argument-defined condition _before_ evaluating the function, 
```
f(φ) = ( (A ∧ ⌈φ⌉) ∨ ( f(φ) ∧ ¬⌈φ⌉ ) ) ∧ ⌈φ⌉
f(φ) = (A ∧ ⌈φ⌉ ∧ ⌈φ⌉) ∨ ( f(φ) ∧ ¬⌈φ⌉ ∧ ⌈φ⌉ )
f(φ) = A ∧ ⌈φ⌉ ∧ ⌈φ⌉
f(φ) = A ∧ ⌈φ⌉
```
but because it is already introduced in the result, we could as easily introduce it only in the remainder,
```
f(φ) = (A ∧ ⌈φ⌉) ∨ ( f(φ) ∧ ¬⌈φ⌉ ∧ ⌈φ⌉ )
f(φ) = A ∧ ⌈φ⌉
```

**Comment by yzhang90** [comment]
Given ```axiom f(x) = A```, when evaluating f(φ), when need to check that φ is a functional pattern (which means it evaluates to one and only one element).  Now, what we check is the defineness of φ. Will we miss something?

**Comment by ttuegel** [comment]
> Given `axiom f(x) = A`, when evaluating f(φ), we need to check that φ is a functional pattern

I do not think this is correct: the unifier `⌈x ∧ φ⌉` is defined even if φ is not functional. However, that is irrelevant: we only ever apply symbols if their arguments are at least `function`, so being defined on top of that is the same as being `functional`.

**Comment by yzhang90** [comment]
ok. got it. thanks

**Comment by ttuegel** [comment]
The function evaluator is [`Kore.Step.Axiom.EvaluationStrategy.evaluateWithDefinitionAxioms`](https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Axiom/EvaluationStrategy.hs#L294). The remainders after applying all the rules are [modified](https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Axiom/EvaluationStrategy.hs#L327) so that we do not continually try to evaluate them. Before marking the remainders with `mkEvaluated`, we should assemble the arguments-defined condition and combine it with the remainder's existing conditions. We will need to write a function which extracts the children of a `TermLike` if it is an `Application` at the top, then use [`Kore.Step.Simplification.Ceil.makeEvaluate`](https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Simplification/Ceil.hs#L112) to make the definedness condition.

**Comment by ttuegel** [comment]
This is blocking:
- `SWAP-summary-0-spec`
- `DUP-summary-0-spec`
