### ISSUE TITLE
Differentiate `Not Matching` and `Not implemented` when matching for function rules

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#769]
Now matching algorithm will return `bottom` for both cases (not matching and not implemented). We may want to differentiate them and log some information when `Not implemented` case is encountered.

**Comment by ttuegel** [comment]
In `master` "not implemented" is `Left` and "not matching" is `\bottom`. In #733, I first planned to make both `\bottom`, but we decided not to do that; see the discussion on that ticket for all the details.
