### ISSUE TITLE
Refactor builtin tests to property tests

### ISSUE THREAD

**Issue by vladciobanu** [kframework/kore#772]
There are many cases of unit tests which could be refactored into property tests. I am thinking specifically of the newly added unit tests for builtin matching, but I'm sure there are plenty of other examples.

**Comment by virgil-serbanuta** [comment]
If we're doing that, I have a few questions and requests:

1. When a property test fails, the diff is usually hard to read, it just says that two long chunks of text (usually a serialized pattern) are different. The non-property tests usually use assertEqualsWithExplanation, which, although it's suboptimal, it allows one to easily see the thing that's actually different. Could we fix this issue first?

2. In many cases, I'm not sure exactly what we gain by running property tests. Most of the tests with which I worked lately were like "get some random ints; get some random vars; make two terms out of them; unify". What do we gain by making the ints and the vars random? To me, it seemed that it made the test harder to write: substitutions are oriented, so I had to sort the vars first to be able to produce the expected substitution. So, how about using property tests only when we gain something compared to regular tests?

**Comment by ttuegel** [comment]
>     The non-property tests usually use assertEqualsWithExplanation, which, although it's suboptimal, it allows one to easily see the thing that's actually different. Could we fix this issue first?

The best way to fix this while retaining the benefits of `hedgehog` is to avoid testing equality of large structures. Currently, each test culminates in a single equality check. I think we should prefer to check a sequence of many smaller predicates.

>     So, how about using property tests only when we gain something compared to regular tests?

I agree. [This blog series](https://wickstrom.tech/programming/2019/03/02/property-based-testing-in-a-screencast-editor-introduction.html) is a great resource for learning to maximize the benefits of property testing.

**Comment by virgil-serbanuta** [comment]
> > ```
> > The non-property tests usually use assertEqualsWithExplanation, which, although it's suboptimal, it allows one to easily see the thing that's actually different. Could we fix this issue first?
> > ```
> 
> The best way to fix this while retaining the benefits of `hedgehog` is to avoid testing equality of large structures. Currently, each test culminates in a single equality check. I think we should prefer to check a sequence of many smaller predicates.
> 
We already do this in some of our tests, e.g. https://github.com/kframework/kore/blob/master/kore/test/Test/Kore/Builtin/Map.hs#L829 , and it helps, but the structures are still large.
