### ISSUE TITLE
Poor performance of some EVM summaries

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#823]
These EVM summaries time-out after 5 minutes:

- `SDIV-summary-0-spec`
- `SGT-summary-0-spec`
- `MLOAD-summary-0-spec`
- `MSTORE-summary-0-spec`
- `MSTORE8-summary-0-spec`
- `SLT-summary-0-spec`

We should use [`ghc-events-analyze`](https://hackage.haskell.org/package/ghc-events-analyze) to analyze the performance of these proofs.

**Comment by ttuegel** [comment]
The functions to add annotations to the event log are in [`Debug.Trace`](https://www.stackage.org/haddock/lts-13.30/base-4.12.0.0/Debug-Trace.html#g:2). The manual describes how to [enable](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/phases.html?highlight=eventlog#ghc-flag--eventlog) the event log and what [options](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#rts-eventlog) control logging at runtime.

**Comment by virgil-serbanuta** [comment]
First interesting result: I analyzed the first part of proving a summary that takes between 5 and 10 minutes to run without instrumentation on my computer (`SIGNEXTEND-summary-0-spec`). Equality-based simplification takes 352 seconds, was called ~2M times. Out of that, the SMT solver (z3) took 11s, was called 470 times.

Out of that, equality-based simplification for `Lblsignextend'LParUndsCommUndsRParUnds'EVM-DATA'UndsUnds'Int'Unds'Int` (including the SMT and re-simplification) took 230 seconds, was called only 9 times.

Also, the largest queue length in `unfoldWorker` (`Strategy.hs`) was 4.

Still investigating.

**Comment by virgil-serbanuta** [comment]
Below are the full results for `SIGNEXTEND`. The first column is the thing being measured, the second is the time it took in seconds, the third is the call count. If something calls something with the same tag (e.g. itself), directly or indirectly, only the parent call is used for the time column, but both calls are counted in the call count column.

There are three summary tags: `ExecutionQueueLength`, `equalitySimplification`, `SMT`.
* `ExecutionQueueLength` is used to display the strategy queue length, in order to see how much branching we have. As an example, we had a queue length of 7 three times (the queue length does not include the element being currently processed). The time for this tag is a bit harder to explain.
* `equalitySimplification` - calls to apply an equality axiom to a term, includes resimplification.
* `SMT` - calls to the SMT solver. Some of these are also included in the `equalitySimplification` tag.

Notable stuff:
* Total execution time: 1754 seconds = 29 minutes 14 seconds (5-10 min without profiling)
* `equalitySimplification` took most of this time: 1136 seconds = 18 min 56 ssec
* In particular, `equalitySimplification` for `signextend` took 878 seconds = 14 min 38 sec for only 29 calls.
* The SMT solver took only 37 seconds. I'm still wondering if there's a way to call it that wasn't instrumented.

Next steps: focusing only on certain tags (e.g. what happens inside `signextend` calls).

```
ExecutionQueueLength    1753.850681415s    #35
ExecutionQueueLength-0    1753.850681415s    #7
ExecutionQueueLength-3    1696.378924117s    #4
ExecutionQueueLength-2    1667.141703101s    #3
ExecutionQueueLength-1    1667.141685726s    #3
ExecutionQueueLength-4    1325.640741604s    #5
ExecutionQueueLength-5    1142.247052376s    #4
equalitySimplification    1135.843399438s    #9347946
ExecutionQueueLength-6    978.772076535s    #6
ExecutionQueueLength-7    881.52567828s    #3
equalitySimplification-Lblsignextend'LParUndsCommUndsRParUnds'EVM-DATA'UndsUnds'Int'Unds'Int    877.709571458s    #29
equalitySimplification-Lbl'Unds'-Int'Unds'    131.669159227s    #2873307
equalitySimplification-Lbl'UndsStar'Int'Unds'    79.909874127s    #1614194
equalitySimplification-Lbl'Unds'modInt'Unds'    71.047322511s    #1257921
equalitySimplification-Lbl'Unds'andBool'Unds'    70.515192721s    #203068
equalitySimplification-Lbl'UndsPlus'Int'Unds'    65.562260591s    #1614109
equalitySimplification-Lbl'Unds-GT--GT-'Int'Unds'    54.516985272s    #1257921
equalitySimplification-Lblword2Bool'LParUndsRParUnds'EVM-DATA'UndsUnds'Int    48.046560657s    #116
SMT    36.707012329s    #1353
equalitySimplification-Lbl'Unds-LT-Unds-GT-Unds'EVM'UndsUnds'ScheduleConst'Unds'Schedule    13.97697367s    #5517
equalitySimplification-LblnotBool'Unds'    13.123056329s    #46843
equalitySimplification-Lbl'UndsEqlsEqls'Int'Unds'    11.20050281s    #174
equalitySimplification-Lbl'Hash'nBytes'LParUndsRParUnds'EVM-DATA'UndsUnds'Int    11.065185068s    #58
equalitySimplification-Lbl'Unds-GT-Eqls'Int'Unds'    10.944058483s    #227550
equalitySimplification-Lbl'Unds-LT-'Int'Unds'    10.585260695s    #209153
equalitySimplification-Lbl'UndsEqlsSlshEqls'Int'Unds'    10.005786606s    #116
equalitySimplification-Lblbit'LParUndsCommUndsRParUnds'EVM-DATA'UndsUnds'Int'Unds'Int    8.789666233s    #58
SMT-10    8.417732321s    #232
equalitySimplification-Lbl'Hash'nBits'LParUndsRParUnds'EVM-DATA'UndsUnds'Int    5.986878647s    #58
equalitySimplification-Lbl'Unds-LT--LT-'Byte'UndsUnds'EVM-DATA'UndsUnds'Int'Unds'Int    3.876160355s    #87
equalitySimplification-Lbl'Hash'sizeWordStack'LParUndsCommUndsRParUnds'EVM-DATA'UndsUnds'WordStack'Unds'Int    3.582687547s    #9132
SMT-805    3.218407923s    #58
SMT-39    2.859196417s    #90
SMT-303    2.60455971s    #58
SMT-603    2.425813299s    #58
equalitySimplification-Lbl'UndsEqlsEqls'K'Unds'    2.382880639s    #153
equalitySimplification-Lbl'Unds'orBool'UndsUnds'BOOL'UndsUnds'Bool'Unds'Bool    2.123498728s    #6988
equalitySimplification-LblbitRangeInt'LParUndsCommUndsCommUndsRParUnds'INT-COMMON'UndsUnds'Int'Unds'Int'Unds'Int    1.508471124s    #58
SMT-143    1.398665861s    #29
SMT-144    1.324830587s    #29
SMT-10391    1.312511673s    #29
equalitySimplification-Lbl'Unds-GT-'Int'Unds'    1.296860318s    #4550
SMT-162    1.27963963s    #29
SMT-432    1.26547411s    #18
SMT-161    1.255813357s    #29
SMT-10265    1.12039358s    #29
SMT-118    1.040224674s    #29
SMT-119    1.000459098s    #29
SMT-136    0.934411815s    #29
SMT-137    0.910893235s    #29
SMT-393    0.892404359s    #58
equalitySimplification-Lblchop'LParUndsRParUnds'EVM-DATA'UndsUnds'Int    0.886741971s    #3592
SMT-10438    0.784977471s    #29
SMT-5188    0.667943554s    #29
SMT-11204    0.554381825s    #5
SMT-132463    0.495364036s    #1
equalitySimplification-Lbl'Hash'usesMemory'LParUndsRParUnds'EVM'UndsUnds'OpCode    0.460888459s    #1
equalitySimplification-Lbl'UndsEqlsSlshEqls'K'Unds'    0.456081639s    #10
equalitySimplification-Lbl'Hash'stackNeeded'LParUndsRParUnds'EVM'UndsUnds'OpCode    0.453588362s    #15
equalitySimplification-Lbl'Hash'stackUnderflow'LParUndsCommUndsRParUnds'EVM'UndsUnds'WordStack'Unds'OpCode    0.449297834s    #3
equalitySimplification-Lbl'Hash'code'QuesLParUndsRParUnds'EVM'UndsUnds'OpCode    0.449009759s    #2
equalitySimplification-LblisLogOp    0.446411143s    #21
equalitySimplification-Lbl'Unds-LT--LT-'Int'Unds'    0.39752093s    #7695
SMT-6096    0.307991243s    #5
SMT-11175    0.188103808s    #3
equalitySimplification-Lbl'Hash'stackOverflow'LParUndsCommUndsRParUnds'EVM'UndsUnds'WordStack'Unds'OpCode    0.105495091s    #3
equalitySimplification-Lbl'Hash'stackDelta'LParUndsRParUnds'EVM'UndsUnds'OpCode    9.6385246e-2s    #6
equalitySimplification-inj    9.4226138e-2s    #1807
SMT-11029    9.2993813e-2s    #8
SMT-86    7.6233793e-2s    #261
SMT-11105    5.696128e-2s    #5
equalitySimplification-Lbl'Hash'stackAdded'LParUndsRParUnds'EVM'UndsUnds'OpCode    4.8625148e-2s    #9
equalitySimplification-Lbl'UndsPipe'Int'Unds'    3.8993392e-2s    #1830
SMT-11076    3.4148181e-2s    #3
equalitySimplification-Lbl'UndsAnd'Int'Unds'    3.3789058e-2s    #1762
SMT-6067    3.0922389e-2s    #3
SMT-619    2.9712191e-2s    #3
SMT-881    2.3090233e-2s    #58
SMT-650    2.1591726e-2s    #58
SMT-235    1.9817157e-2s    #2
equalitySimplification-Lbl'Hash'changesState'LParUndsCommUndsRParUnds'EVM'UndsUnds'OpCode'Unds'WordStack    1.8321714e-2s    #2
SMT-132592    1.7290618e-2s    #1
SMT-128605    1.6576243e-2s    #1
SMT-108288    1.321963e-2s    #1
equalitySimplification-Lbl'Hash'addr'QuesLParUndsRParUnds'EVM'UndsUnds'OpCode    1.2276057e-2s    #2
equalitySimplification-Lbl'Hash'sizeWordStack'LParUndsRParUnds'EVM-DATA'UndsUnds'WordStack    1.1607082e-2s    #6
equalitySimplification-Lbl'Hash'widthOp'LParUndsRParUnds'EVM'UndsUnds'OpCode    4.889514e-3s    #4
equalitySimplification-LblisPushOp    3.093303e-3s    #5
equalitySimplification-LblisCallOp    2.417016e-3s    #4
equalitySimplification-LblisCallSixOp    2.289767e-3s    #4
SMT-11251    1.677136e-3s    #1
SMT-11152    1.62794e-3s    #1
SMT-11222    1.527939e-3s    #1
SMT-11123    1.40755e-3s    #1
SMT-11059    1.300332e-3s    #1
SMT-11193    1.279809e-3s    #1
equalitySimplification-append    1.215809e-3s    #1
SMT-6143    8.85421e-4s    #1
SMT-6114    8.7716e-4s    #1
SMT-6085    8.55138e-4s    #1
SMT-5952    8.28764e-4s    #1
equalitySimplification-LblisNullStackOp    8.08302e-4s    #1
SMT-532    4.51662e-4s    #1
SMT-694    4.46865e-4s    #1
SMT-637    3.84678e-4s    #1
SMT-676    3.78402e-4s    #1
SMT-516    3.32693e-4s    #1
equalitySimplification-Lbl'Hash'if'UndsHash'then'UndsHash'else'UndsHash'fi'Unds'K-EQUAL'UndsUnds'Bool'Unds'K'Unds'K    1.84673e-4s    #1
```

**Comment by ttuegel** [comment]
Does `equalitySimplification` include recursive calls? I am suspecting that we might recurse into some deep structure there, accounting for the amount of time spent there.

**Comment by virgil-serbanuta** [comment]
Yes, it includes. I am working on detailing that.

**Comment by virgil-serbanuta** [comment]
Something weird happens here. The entire simplification takes 876 seconds for 29 `signextend` calls. We can split that into 227 seconds for applying the axiom, 410 seconds for re-simplifying the result after applying the axiom, and 239 for everything else, which, likely, just includes substitution merging after re-simplification.

The term being simplified looks like this:
```
Lblsignextend'LParUndsCommUndsRParUnds'EVM-DATA'UndsUnds'Int'Unds'Int{}(
    VarR'Unds'W0:SortInt{},
    VarR'Unds'W1:SortInt{}
)
```
so we might try to mark this function as a concrete one.

**Comment by ttuegel** [comment]
> we might try to mark this function as a concrete one.

I think that is a reasonable thing to do.

**Comment by virgil-serbanuta** [comment]
Yep, marking it as concrete seems to be good enough.

**Comment by virgil-serbanuta** [comment]
Opened https://github.com/kframework/evm-semantics/pull/434 which fixes SIGNEXTEND, will send for review after fixing all similar performance issues (if any).

**Comment by ttuegel** [comment]
Only the proof of the `SDIV` instruction continues to have performance problems.

**Comment by virgil-serbanuta** [comment]
Marking things as concrete may help. The main problem is that we shouldn't just mark rules as "concrete", we should also provide an SMT equivalent for them, otherwise we'll have symbols that neither us nor the SMT can handle. (BTW, we already did this for some other evm summary proof, we might want to take another look at https://github.com/kframework/evm-semantics/pull/434).

https://github.com/kframework/kore/pull/924 seemed to prune a lot of branches in its initial version. I think we were doing a cross product for, say, the various options for `sgn(x)` from multiple branches, without checking locally that those branches are compatible, we were checking that only at the top. However, after rebasing on a newer master, it seems to (roughly) have no effect. I'll try to debug this today to see if I can figure out what happens.

Expanding things only when needed should help with this issue, since we should get an exact match between the configuration and the claim's RHS. However, this would be a rather big change.

**Comment by virgil-serbanuta** [comment]
BTW, SMOD is the one I still see timing out.

**Comment by virgil-serbanuta** [comment]
Here are the last stats for SMOD on my laptop:
1. #924 reduces the (intermediate) branch number by ~4x and almost halves the execution time.
(all future times are measured with #924)
2. Almost all the time seems to be spent in `SimplifyRem` (~5-6 sec/step) and `DeriveSeq` (~6 sec/step). For the first steps (I didn't let it run until the end) `SimplifyRem` always takes 5-6 sec, but DeriveSeq also has shorter runs (e.g. 0.4 sec).
3. For some reason, DeriveSeq seems to simplify the entire configuration, which is a bit unexpected to me.
4. Both `SimplifyRem` and `DeriveSeq` seem to have 10 branches at the end of their simplification part, but before calling the SMT (45 branches when running on the master).
5. Most of the time is spent outside of what is being measured by my current profiler hack (#954 , I'll try to clean it and send it for review), which likely means it's spent in z3. If true, this means that the time is being spent in z3+branching.

Questions:
1. Why does `DeriveSeq` simplify the entire configuration?
2. Right now the time-consuming part of simplification seems to be roughly identical between various steps. Why? Doesn't the configuration change?

I'll investigate these tomorrow.

**Comment by virgil-serbanuta** [comment]
Some answers:

1. DeriveSeq removes the destination from the remainder and simplifies the result. https://github.com/kframework/kore/pull/958 makes that explicit.

2. Simplifying a configuration after removing the destination seems to take ~4-6 seconds (depends on the computer on which I run it, not on the step), we do that twice per step, and that's the only time consuming part of a step.

* We should check if we attempt to simplify the RHS of claims before proving, and, if we already do that, we should find out why it does not help.

**Comment by virgil-serbanuta** [comment]
If we would simplify the RHS we would do it here:
https://github.com/kframework/kore/blob/master/kore/src/Kore/Exec.hs#L254
which goes here:
https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Simplification/Rule.hs#L85
which does not simplify the RHS.

We should try that.
