### ISSUE TITLE
Keep prelude.kore in sync between frontend and backend

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#829]
- [x] Move `prelude.kore` to the backend repository.
- [ ] During our Jenkins job, modify the installed frontend with our `prelude.kore`.

**Comment by traiansf** [comment]
@ttuegel did you get the chance to talk with @dwightguth about this?

**Comment by ttuegel** [comment]
We agreed that it would be fine to move `prelude.kore` to the backend repository.

**Comment by traiansf** [comment]
Instead of the second task, I modified the maven archive job to take prelude.kore from its submodule location.
