### ISSUE TITLE
MAP.element is injective

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#853]
The `SLOAD` spec crashes with a [substitution-coverage error](https://github.com/kframework/kore/files/3488055/SLOAD-summary-0-spec.err.txt) because the backend fails to recognize that, in our new internal representation of Map, `element` is injective.

CC: @virgil-serbanuta

**Comment by virgil-serbanuta** [comment]
I took a look at this error and my first guess would be that it's about a unification case that we don't want to implement, i.e. `concat(elem(x1, x2), x3)` vs `concat(elem(alpha, beta), y3)` where `x1`, `x2`, `x3` and `y3` are variables, while alpha and beta are concrete (the part that prevents us from implementing it is that `x3` and `y3` are Map variables).

If you think that's wrong, I can take a more careful look later.

**Comment by ttuegel** [comment]
The case is actually,

```
concat(elem(ACCT_ID, STORAGE), _7) 
/* versus */
concat(elem(ACCT_ID, R_STORAGE), ACCOUNTS)
```

Although everything is symbolic, we know this only has one (inhabited) unifier:

```
STORAGE = R_STORAGE ∧ _7 = ACCOUNTS
```

Should we add a special case for unification with identical symbolic keys?

**Comment by virgil-serbanuta** [comment]
We could do that... I wonder if we could make the symbolic part of the representation a map instead of a list.

**Comment by ttuegel** [comment]
- [ ] Make the symbolic part of AC collections into a `Map`, ensuring that duplicate keys give `\bottom`.
- [ ] Perform unambiguous symbolic lookups as above, ensuring that each symbolic Map is defined.
- [ ] Do the same for Sets.

**Comment by virgil-serbanuta** [comment]
I don't think it's a good idea to make it a map anymore, it needs to have instances for, say, `Functor`, and having a `Map a a` as a `Functor` of `a` might not actually work.

**Comment by virgil-serbanuta** [comment]
So, I think that we were already treating elements as injective, the problem was that, in some cases, we could easily unify when both opaque lists are not empty, but we didn't.
