### ISSUE TITLE
Unit tests are slow

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#858]
The unit tests became suddenly slower at c93f1192a87bec17bb99a8b5aa56ff330d6356fa.

**Comment by ttuegel** [comment]
It is possible that this is due to contention for the lock on the logger, and therefore is not a problem for the usual execution.

- [ ] Run the unit tests in ThreadScope to find out if locking is an issue.
- [ ] Check that the integration tests are not slower around that commit.

If locking in the unit tests is an issue, we may provide a "null" logging implementation that does not even lock. If it is an issue in ordinary execution, we should move the log writer to its own thread and use `STM` channels to push log messages to the writer.

**Comment by vladciobanu** [comment]
Offending commit: c93f1192a
- `stack test`:
- `stack test --test-arguments "-RTS -N1 +RTS":
- `make k-test`:

Commit right before: 10c63c8b0
- `stack test`:
- `stack test --test-arguments "-RTS -N1 +RTS":
- `make k-test`:

**Comment by vladciobanu** [comment]
After running the integration tests a few more times, it seems like the ~10s difference is within the error margin so the difference seems irrelevant. @ttuegel should we just close this for now? Do you want me to investigate further?

**Comment by ttuegel** [comment]
No, I agree, it's not significant at this time.
