### ISSUE TITLE
Replay #847 (Redundant constraints)

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#889]
Revert [40bde26e7226a9aaae856f1fa3a2b255613a6235](https://github.com/kframework/kore/pull/885/commits/40bde26e7226a9aaae856f1fa3a2b255613a6235) to replay #847.

```.sh
git remote add upstream git@github.com:kframework/kore.git
git fetch upstream refs/pull/885/head
git revert 40bde26e7226a9aaae856f1fa3a2b255613a6235
# fix conflicts
```

**Comment by vladciobanu** [comment]
I will keep this updated, but I managed to run each branch once and indeed, there is a 2x slowdown for this PR.

master:
- 474.93user 15.22system 6:44.74elapsed

replay:
- 964.83user 40.00system 13:35.46elapsed

**Comment by ttuegel** [comment]
@vladciobanu 
You should try this after merging #867; if that does not correct the issue, then @yzhang90 and I agree that this is not worth the effort at this time.

**Comment by vladciobanu** [comment]
@ttuegel I updated the original comment. It seems the 2x slowdown is still happening even after reverting from current master (since #867 is merged). I'll follow your lead and give this up for now.
