### ISSUE TITLE
Replay #822 - Add ceils to predicates before SMT

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#891]

**Comment by vladciobanu** [comment]
@ttuegel It seems reverting this has a *huge* performance penalty. Unless I got something horribly wrong (see #914), this doesn't finish in almost 4 times as long (I stopped it after 22 minutes). Should I investigate further?



master:
- 435.24user 14.58system 6:11.20elapsed 121%CPU
- 436.43user 14.31system 6:11.74elapsed 121%CPU
#914 / revert:
- stopped after 22 minutes

**Comment by ttuegel** [comment]
I need to re-run the single-instruction proofs to see if this is really necessary. I will report back.

**Comment by ttuegel** [comment]
I re-ran the single-instruction proofs, and I don't think we need to do this now. In fact, I think this only serves to obscure definedness conditions which are missing from the semantics.
