### ISSUE TITLE
Interface to choose one-path or all-path proofs

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#906]
Needs: #937 

See also: #714

---

- [x] Module and rule attributes in frontend
- [x] Update frontend for backend integration tests
- [x] Allow all-path to be used in the backend ( initial work in PR #1162 )
  - [x] `Goal` instance for `ReachabilityRule` (https://github.com/kframework/kore/pull/1206)
  - [x] `ReachabilityRule` as `Claim` + Generalize `verifyClaimStep` to `ReachabilityRule` (https://github.com/kframework/kore/pull/1232)
- [ ] Update integration tests to use new interface (https://github.com/kframework/kore/pull/1251)

**Comment by traiansf** [comment]
PR at https://github.com/kframework/k/pull/842
