### ISSUE TITLE
Missing hook: STRING.token2string

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#925]
The relevant entries in [`domains.k`](https://github.com/kframework/k/blob/master/k-distribution/include/builtin/domains.k#L792) are:

```
  syntax Id [token]

  syntax String ::= Id2String ( Id )    [function, functional, hook(STRING.token2string)]
  syntax Id ::= String2Id (String) [function, functional, hook(STRING.string2token)]
```

We might as well implement `STRING.string2token` as well.

The `[token]` attribute on `syntax Id` means that `Id` will be a raw domain value, `\dv{SortId{}}("...").

**Comment by ehildenb** [comment]
By the way, this should work for any domain value, not just sort `Id`. For example, in KWasm we declare:

```
    syntax String     ::= #parseWasmString   ( WasmString ) [function, functional, hook(STRING.token2string)] 
    syntax WasmString ::= #unparseWasmString ( String     ) [function, functional, hook(STRING.string2token)] 
```

To allow parsing the correct tokens of sort `WasmString` but still be able to do string operations over them in the semantics.
