### ISSUE TITLE
Check that the configuration being rewritten is "function-like"

### ISSUE THREAD

**Issue by traiansf** [kframework/kore#940]
The document proving the correctness of computing remainders upon rule applications requires that the configuration being rewritten is "function-like" (see https://github.com/kframework/kore/blob/master/docs/2018-11-08-Configuration-Splitting-Simplification.md#problem )

However, nobody remembers actually checking this before attempting to apply a rule.

A simple example of how bad this might fail is this: Consider configuration `a ∨ b` and rule `a => c`.
By applying the rule and computing the remainder, one gets `⌈(a ∨ b) ∧  a⌉ ∧  c` (which is `c`) as the result and remainder `¬ ⌈(a ∨ b) ∧  a⌉ /\ (a ∨ b)` which is `⊥` when instead it should be `b`.

---

- [x] Function evaluation should fail if rule or configuration is not function-like. (#1026)
- [x] Applying rewrite rules should fail if rule or configuration is not function-like. (#1026)
- [ ] Simplification evaluation should fail if ...

**Comment by ttuegel** [comment]
Is the problem here only in the way we construct the remainder expression, or something deeper? As long as we push all the disjunctions to the top during rewriting, will we be OK?

**Comment by traiansf** [comment]
In general, I think yes; otherwise we would have seen erroneous output already.

Same would happen If there were symbols which are not function-like (can evaluate to more than one value), or existential quantifiers.

Also, we should remember this if we ever want to merge disjunct configurations as an optimization; then we would have to devise another method for applying rules.

**Comment by virgil-serbanuta** [comment]
I think that we should not just remember it, we should also add an assertion in out code.
