### ISSUE TITLE
Wrong duplication error?

### ISSUE THREAD

**Issue by radumereuta** [kframework/kore#97]
Input:
```
[]
module INPUT
  sort Layout{} []
endmodule []

module INPUT2
  sort Layout{} []
endmodule []
```
Output:
```
c:\work\kore\src\main\haskell>stack exec -- kore-parser ..\..\..\..\test\test4.kore
"Reading the input fileTimeSpec {sec = 0, nsec = 962023}"
"Parsing the fileTimeSpec {sec = 0, nsec = 3287932}"
"Verifying the definitionTimeSpec {sec = 0, nsec = 21616507}"
kore-parser.EXE: Error in module 'INPUT2': Duplicated name: 'Layout'.
CallStack (from HasCallStack):
  error, called at app\parser\Main.hs:90:49 in main:Main
```
I don't think there should be an error here. The modules are not connected.
Plus, the message is missing location information.
In the java implementation of K, we had a rule - every error message related to the input, had to have location information (line and column).

**Comment by virgil-serbanuta** [comment]
I agree with the missing location information issue, I'll try to fix it. However, that's an actual error, see section (9.1.8 Wellformedness) in 
https://github.com/kframework/kore/blob/master/docs/semantics-of-k.pdf:
```
Every sorts, symbols, and aliases, even if they are in different modules, should all have unique
constructor names; One cannot use the same name for a sort and a symbol, for example.
Similarly, any meta-symbol cannot have the same name as a meta-sort.
```

The reasoning behind that (or, at least, my guess about it) is that there should be a topmost module which imports everything (directly or not), and the two identical names will be visible at the same time in that module. I may be wrong though.

**Comment by virgil-serbanuta** [comment]
BTW, please close this issue if the above answers your question.

**Comment by hreada** [comment]
The design principle of Kore is that it should clearly reflect the underlying matching logic theories, so no overloading of anything sorts or symbols. However, this doesn't mean that we apply the same principle on K syntax. Notice that many Kore definitions will be auto-generated from K definitions by K frontends, and frontend should make sure that all overloading is resolved in the generated Kore definitions.
