### ISSUE TITLE
Support for simplification rules with side conditions

### ISSUE THREAD

**Issue by traiansf** [kframework/kore#973]
Performing symbolic execution in the WASM semantics requires being able to apply (simpification) rules of the form
```
    rule #chop(< ITYPE:IValType > N) => < ITYPE > N
      requires #inUnsignedRange(ITYPE, N)
```

on configurations where `#chop` is nested down in some cell and `#inUnsignedRange(ITYPE, N)` is part of the "top" condition.

Required features:

- [x] rule simplification algorithm should not fail with hard "error" if there is a remainder upon attempting the rule
- [x] condition needs to be propagated and used in applying simplification rules.

**Comment by ttuegel** [comment]
This could be another use case for #945.

**Comment by traiansf** [comment]
> This could be another use case for #945.

maybe, although here, and generally for simplification rules, it's not as clear we have an `if_then_else_` pattern. The other simplification rule for `#chop` is 

```
    rule #chop(< ITYPE > N) => < ITYPE > #unsigned(ITYPE, N)
      requires #inSignedRange (ITYPE, N)
```

and it's not clear you would want this written in an `if_then_else_` pattern because there are values for which both preconditions fail.

**Comment by ttuegel** [comment]
I was thinking that the result of a simplification rule could be,

```
if #inSignedRange (ITYPE, N) then < ITYPE > #unsigned(ITYPE, N) else #chop(< ITYPE > N)
```
