### ISSUE TITLE
[REPL] `log debug file` command not working

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#978]
I'm trying to use `log debug file` command to dump the log during proof debugging in REPL. However, no logging file is created. `log debug stdout` command is not working either.

**Comment by ana-pantilie** [comment]
I haven't been able to replicate the issue. On what commit are you on? 

I'm on the latest `master` (869d470a5a5905e8cd24e8a633cb35a1d38ad48e) and I ran `log debug stdout` and then `step` and the `repl` printed the debugging info to the console output. I then ran `log debug file testingLog.txt` and then `step` and the debugging info was now dumped to `testingLog.txt`. Note that the file is only created after a command which should log debugging info is ran (in this example this would be `step`).

**Comment by yzhang90** [comment]
I find a buggy scenario:
I typed `log debug stdout` first
then `stepf 1`-> nothing is printed
then `step` -> log printed
then `stepf 1` -> log printed
