### ISSUE TITLE
Unfold single constructors in proof goals

### ISSUE THREAD

**Issue by traiansf** [kframework/kore#997]
This is currently blocking https://github.com/runtimeverification/polkadot-verification/issues/8

Whenever specifying a goal one usually only writes the cells needed to express the hypothesis and the conclusion. The rest of the cells are abstracted away by variables.

Nevertheless, some of these cells might be needed during the symbolic execution phase. Currently this is not (no longer) supported by the Haskell backend, because 

- it introduces remainders on constructors, 
- it introduces new variables in the lhs, which are supposed to be universally quantified

One way to solve this, proposed here, is to preprocess claims by unfolding all variables in the lhs whose sorts have a single constructor (including injections) and iterating this process until it stabilizes.

This should produce an equivalent claim and should additionally improve efficiency by easing the SMT's burden by the remainder predicates generated if we were to unfold these by need.

Related to issue #812.

**Comment by traiansf** [comment]
Forgot to mention. Credits for the proposed solution should go to @virgil-serbanuta.

**Comment by ttuegel** [comment]
I'm definitely in favor of any solution that can be implemented modularly! How will this affect the output of `kprove`?
