### ISSUE TITLE
Predicate not simplified to predicate

### ISSUE THREAD

**Issue by virgil-serbanuta** [kframework/kore#998]
When running the SDIV summary proof, after a long time (10-30 min) we get an error at src/Kore/Step/Simplification/Predicate.hs:148:10, where the predicate is being simplified to a term+predicate pair. The term part seems to actually be a predicate that we haven't been able to identify as such:

```
    \implies{_PREDICATE{}}(
        \or{_PREDICATE{}}(
            \and{_PREDICATE{}}(
                \not{_PREDICATE{}}(
                    \equals{SortInt{}, _PREDICATE{}}(
                        VarR'Unds'W1:SortInt{},
                        /* builtin: */ \dv{SortInt{}}("0")
                    )
                ),
                \not{_PREDICATE{}}(
                    \not{_PREDICATE{}}(
                        \equals{SortInt{}, _PREDICATE{}}(
                            VarR'Unds'W1:SortInt{},
                            /* builtin: */ \dv{SortInt{}}("0")
                        )
                    )
                )
            ),
            \equals{SortInt{}, _PREDICATE{}}(
                VarR'Unds'W1:SortInt{},
                /* builtin: */ \dv{SortInt{}}("0")
            )
        ),
        \equals{SortInt{}, _PREDICATE{}}(
            Lbl'Unds'-Int'Unds'{}(
                /* builtin: */ \dv{SortInt{}}("0"),
                Lbl'UndsSlsh'Int'Unds'{}(
                    Lblchop'LParUndsRParUnds'EVM-DATA'UndsUnds'Int{}(
                        Lbl'Unds'-Int'Unds'{}(
                            /* builtin: */
                            \dv{SortInt{}}(
                                "115792089237316195423570985008687907853269984665640564039457584007913129639936"
                            ),
                            VarR'Unds'W0:SortInt{}
                        )
                    ),
                    VarR'Unds'W1:SortInt{}
                )
            ),
            /* builtin: */ \dv{SortInt{}}("0")
        )
    ),
```

I've attached the predicate being simplified.

[predicate.txt](https://github.com/kframework/kore/files/3642582/predicate.txt)

**Comment by ttuegel** [comment]
This is the only case where we use `mkImplies` in the simplifier, I'm almost sure this is the problem:
https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Simplification/Implies.hs#L150-L160

**Comment by ttuegel** [comment]
There is a check above that block to see if the children of `\implies` are `\top` (i.e. simplified to pure predicates). If that check fails, then the actual problem must be in the `\or` or `\equals` simplifier not returning a predicate.

**Comment by ttuegel** [comment]
I cannot reproduce this. @virgil-serbanuta Could you send me (on Slack) the version of the SDIV proof you are using?

**Comment by virgil-serbanuta** [comment]
I can't reproduce with the current master either, so I didn't send the file, but I'll send it if you think it provides some value.

**Comment by ttuegel** [comment]
No, that's alright. I will open a pull request for rejecting non-trivial predicates in a simplified `term`, and otherwise we will consider this closed unless it occurs again.
